Add Warehouse FAQ
rudderlabs/rudderstack-docs pull request #1003
Opened 2022-11-14 10:35 UTC by ameypv-rudder

## What do these changes do?

> Added warehouse FAQ on the automatic type conversions supported by RudderStack

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

2022-11-14 10:44 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +RudderStack automatically handles the data type conversion for some common scenarios **depending on the warehouse column data type**.
```suggestion
RudderStack automatically handles the data type conversion in some common scenarios **depending on the warehouse column data type**.
```

2022-11-14 10:52 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Integer <br /> Float <br /> JSON | String | RudderStack automatically stringifies the non-string data. |
```suggestion
| All data types **except** String, Text, or JSON | String | RudderStack automatically stringifies the incoming data. |
```

2022-11-14 10:53 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Integer | Float | - |
```suggestion
| Integer <br /> BigInt | Float | - | 
```

2022-11-14 10:53 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Float | Integer | - |
```suggestion
| Float | Integer <br /> BigInt | - |
```

2022-11-14 10:55 UTC, achettyiitr requested changes

2022-11-14 10:55 UTC, achettyiitr commented on docs/destinations/warehouse-destinations/faq.mdx
> +| All data types **except** String, Text, or JSON | String | RudderStack automatically stringifies the incoming data. |
```suggestion
| All data types **except** String, Text, or JSON | String or Text | RudderStack automatically stringifies the incoming data. |
```

2022-11-15 06:05 UTC, achettyiitr approved these changes

2022-11-15 06:35 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Incoming data type | Warehouse column data type | Notes |
```suggestion
| Scenario | Incoming data type | Warehouse column data type | Notes |
```

2022-11-15 06:35 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| :----| :------| :------|
```suggestion
| :-----| :----| :------| :------|
```

2022-11-15 06:36 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| All data types **except** String, Text, or JSON | String or Text | RudderStack automatically stringifies the incoming data. |
```suggestion
| 1 | All data types **except** String, Text, or JSON | String or Text | RudderStack automatically stringifies the incoming data. |
```

2022-11-15 06:36 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Integer <br /> BigInt | Float | - |
```suggestion
| 2 | Integer <br /> BigInt | Float | - | 
```

2022-11-15 06:36 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Float | Integer <br /> BigInt | - |
```suggestion
| 3 | Float | Integer <br /> BigInt | - |
```

2022-11-15 06:38 UTC, ameypv-rudder commented on docs/destinations/warehouse-destinations/faq.mdx
> +| Int <br /> Float <br /> Boolean | JSON | RudderStack automatically stringifies the incoming data. |
```suggestion
| 4 | Integer <br /> Float <br /> Boolean | JSON | RudderStack automatically stringifies the incoming data. |
```

2022-11-15 08:31 UTC, ishachopra0401 approved these changes

2022-11-15 08:32 UTC, ishachopra0401 commented
LGTM! just checking if we can add rudder_discards scenario for the rest of the cases.

2022-11-15 08:37 UTC, achettyiitr commented
> LGTM! just checking if we can add rudder_discards scenario for the rest of the cases.

@ishachopra0401 Good point. Anything which is not handled goes to rudder_discards.

2022-11-15 10:01 UTC, ameypv-rudder commented
Thanks for the feedback @achettyiitr and @ishachopra0401 - I've incorporated the suggestion re: `rudder_discards`

2022-11-15 10:49 UTC, ishachopra0401 approved these changes

2022-11-15 10:49 UTC, ishachopra0401 commented on docs/destinations/warehouse-destinations/faq.mdx
> +The incoming data which <strong>cannot</strong> be typecasted into the warehouse column-specific data type is sent to the <code class="inline-code">rudder_discards</code> table.
```suggestion
In any scenario other than the ones covered above, that is, when the incoming data <strong>cannot</strong> be typecasted into the warehouse column-specific data type, it is sent to the <code class="inline-code">rudder_discards</code> table.
```

2022-11-15 10:55 UTC, merged