Session tracking docs optimization
rudderlabs/rudderstack-docs pull request #1062
Opened 2022-12-15 11:03 UTC by ameypv-rudder

## What do these changes do?

> Updated session tracking docs to clarify certain aspects.
> Separated manual session tracking from automatic to not have any scope for confusion.

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +If the session tracking feature is enabled, you can expect the following properties in your event's <code class="inline-code">context</code> object:
> If the session tracking feature is enabled..

Gives a sense that the user needs to enable it but as I understand, it happens by default. May be we can tweak this sentence to clarify this

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +## Session tracking in RudderStack
```suggestion
## Session tracking by RudderStack SDK's
```

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
>  The session tracking feature overrides any <code class="inline-code">sessionId</code> set in the event's <code class="inline-code">context</code> object. Hence, it is strongly recommended to send any
bit confusing.. lets connect on chat/huddle as I want to understand this more

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
> +RudderStack supports manual session tracking that let you define the start and end of a user session.
```suggestion
RudderStack supports manual session tracking that lets you define the start and end of a user session.
```

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
> +    <td>If no parameter is passed, RudderStack creates a new session and passes the current <code class="inline-code">timestamp</code> as the <Link to="/sources/event-streams/sdks/session-tracking/fa
```suggestion
    <td>If you don't pass any parameter, RudderStack creates a new session and passes the current <code class="inline-code">timestamp</code> as the <Link to="/sources/event-streams/sdks/session-tracking/faq/#how-does-rudderstack-determine-the-sessionid"><code class="inline-code">sessionId</code></Link>.</td>
```

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
> +    <td> You can pass a custom <code class="inline-code">sessionId</code> and trigger a new user session. <br/><br/> It is <strong>not recommended</strong> to use a decimal number as the <code class=
```suggestion
    <td> If you pass the <code class="inline-code">sessionId</code> parameter, RudderStack triggers a new user session. <br/><br/> It is <strong>not recommended</strong> to use a decimal number as the <code class="inline-code">sessionId</code>. </td>
```

2022-12-21 09:35 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
> +<strong>Manual session tracking overrides <Link to="/sources/event-streams/sdks/session-tracking/#automatic-session-tracking">automatic session tracking</Link></strong>. <br /><br />If automatic sess
> If automatic session tracking is enabled and you call the <code class="inline-code">startSession()</code> method, then RudderStack disables it <strong>until the app is closed completely

Does it mean that when you call startSession() method, then RudderStack disables the automatic session tracking until the app is closed completely? 

Assuming that manual session tracking overrides the automatic session tracking (which happens by default) whenever a user calls these methods

2022-12-21 09:54 UTC, pallabmaiti requested changes

2022-12-21 09:54 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +4. Otherwise, the SDK updates the session expiration time by adding the last event's <Link to="/event-spec/standard-events/common-fields/#clock-skew-considerations">`timestamp`</Link> to the `timeout
This is not correct for Mobile SDKs. The previous one is the correct one.

2022-12-21 13:04 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +4. Otherwise, the SDK updates the session expiration time by adding the last event's <Link to="/event-spec/standard-events/common-fields/#clock-skew-considerations">`timestamp`</Link> to the `timeout
@pallabmaiti This section is specific to only JS SDK. We have a separate flow explained for Mobile SDKs in the following section.

2022-12-21 13:13 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/manual-session-tracking.mdx
> +<strong>Manual session tracking overrides <Link to="/sources/event-streams/sdks/session-tracking/#automatic-session-tracking">automatic session tracking</Link></strong>. <br /><br />If automatic sess
I used the words `disables it` because `automatic session tracking` is repeated otherwise. Let me think of something to rephrase this in a better way.

2022-12-21 13:26 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
>  The session tracking feature overrides any <code class="inline-code">sessionId</code> set in the event's <code class="inline-code">context</code> object. Hence, it is strongly recommended to send any
Sure - earlier, users sent the session related data like session ID, etc. in the event's [`context`](https://www.rudderstack.com/docs/event-spec/standard-events/common-fields/#contextual-fields) object. Now, with our SDKs automatically setting the `sessionId` and `sessionStart` params in the `context` object (as mentioned above), any session-related info manually supplied by the user will be overridden. Hence the warning to set any other session-related information in the event's `traits` object or properties.

2022-12-21 15:11 UTC, pallabmaiti approved these changes

2022-12-23 10:43 UTC, ishachopra0401 approved these changes

2022-12-23 10:43 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +It is strongly recommended to send any other session-related information in the event's traits or properties. When session tracking is enabled, RudderStack overrides any <code class="inline-code">ses
```suggestion
It is strongly recommended to send any other session-related information in the event's traits or properties as RudderStack's automatic session tracking overrides any <code class="inline-code">sessionId</code> set in the event's <code class="inline-code">context</code> object.
```

2022-12-23 12:22 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +It is strongly recommended to send any other session-related information in the event's traits or properties as RudderStack's automatic session tracking overrides any <code class="inline-code">sessio
```suggestion
It is strongly recommended to send any other session-related information in the event's traits or properties as RudderStack's <Link to="#automatic-session-tracking">automatic session tracking</Link> overrides any <code class="inline-code">sessionId</code> set in the event's <code class="inline-code">context</code> object.
```

2022-12-26 07:58 UTC, merged