PHP SDK initialization snippet update
rudderlabs/rudderstack-docs pull request #1064
Opened 2022-12-16 06:34 UTC by ameypv-rudder

## What do these changes do?

> Added descriptions for the `max_queue_size` and `batch_size` parameters in the initialization snippet.

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

2022-12-16 06:35 UTC, ameypv-rudder commented
As discussed with @MoumitaM, a thorough revamp/update of the SDK doc will be conducted after the SDK audit.

2022-12-16 11:57 UTC, MoumitaM requested changes

2022-12-16 11:57 UTC, MoumitaM commented on docs/sources/event-streams/sdks/rudderstack-php-sdk.mdx
> +  "max_queue_size" => 10000, // Temporary queue to store the in-memory events, defaults to 1000
```suggestion
  "max_queue_size" => 10000, // Temporary queue to store the events, defaults to 1000
```

2022-12-19 04:14 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-php-sdk.mdx
> +  "max_queue_size" => 10000, // Maximum number of events to be stored by the in-memory queue, defaults to 1000
```suggestion
  "max_queue_size" => 10000, // Maximum number of events store in the in-memory queue, defaults to 1000
```

2022-12-19 05:36 UTC, MoumitaM approved these changes

2022-12-19 05:52 UTC, ishachopra0401 approved these changes

2022-12-19 06:30 UTC, merged