iOS SDK updates
rudderlabs/rudderstack-docs pull request #1107
Opened 2023-01-16 10:45 UTC by ameypv-rudder

## What do these changes do?

> Added steps for SPM installation in both the v1 and v2 docs.
> The doc now dynamically loads the SDK version in the shields badge.

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

2023-01-16 14:37 UTC, pallabmaiti requested changes

2023-01-16 14:37 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +  <li>In <strong>Dependency Rule</strong>, select  <strong>Up to Next Major Version</strong> and enter the value as <strong>1.8.0</strong>, as shown:</li>
Can you fetch this version from `package.json`?

2023-01-16 14:37 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +        .package(url: "git@github.com:rudderlabs/rudder-sdk-ios.git", from: "1.8.0")
Can you fetch this version from `package.json`?

2023-01-16 14:37 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
> +  <li>In <strong>Dependency Rule</strong>, select  <strong>Up to Next Major Version</strong> and enter the value as <strong>2.2.5</strong>, as shown:</li>
Can you fetch this version from `package.json`?

2023-01-16 14:37 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/ios-v2.mdx
> +        .package(url: "git@github.com:rudderlabs/rudder-sdk-ios.git", from: "1.8.0")
Can you fetch this version from `package.json`?

2023-01-17 03:48 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +  <li>In <strong>Dependency Rule</strong>, select  <strong>Up to Next Major Version</strong> and enter the value as <strong>1.8.0</strong>, as shown:</li>
I'm not sure how to do that, @pallabmaiti - could you or @1abhishekpandey please suggest the relevant steps/snippet to fetch the version automatically?

2023-01-17 04:11 UTC, pallabmaiti approved these changes

2023-01-17 04:12 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +  <li>In <strong>Dependency Rule</strong>, select  <strong>Up to Next Major Version</strong> and enter the value as <strong>1.8.0</strong>, as shown:</li>
Got it.

2023-01-17 07:30 UTC, 1abhishekpandey approved these changes

2023-01-17 08:32 UTC, ishachopra0401 approved these changes

2023-01-17 09:12 UTC, merged