Facebook custom audience docs
rudderlabs/rudderstack-docs pull request #113
Opened 2021-06-24 10:14 UTC by shrouti1507

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-06-24 12:33 UTC, utsabc requested changes

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +The sources can be customer lists, website or app traffic, or engagement on Facebook.
We are only doing customer list, right?

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +The user informations may include Email, Phone Number, Gender and many others. Find detailed information     [here] (https://developers.facebook.com/docs/marketing-api/audiences/guides/custom-audienc
Suggestion --> Find detailed information on Supported fields [here]

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +| **Cloud mode** | **Supported** | **Supported** | **Supported** |
Maybe for this destination, we might need to give preference to warehouse as source Thoughts @arnab-p  @shrouti1507

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +
The data has to be sent in the same order as set in schema fields -- we should write that too

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +* **Map Specific Events To Audience ID**: In this section, enter the **Event Name(s)** you are going to use to send user data to Rudderstack \(for e.g. `USER_ADD`, `USER_DELETE` etc.\). Also, enter t
Please add different `event name` as examples this will become confusing as we already have 2 arrays with  similar name in our payload properties

2021-06-24 12:33 UTC, utsabc commented on destinations/fb_custom_audience.md
> +The `userListAdd` and `userListDelete` blocks expected inside the `properties` field of the track event.
Suggestion:

The `userListAdd` and `userListDelete` arrays containing the user data objects are expected inside the `properties` field of the track event.

2021-06-30 12:19 UTC, utsabc approved these changes
LGTM

2021-07-01 06:54 UTC, ameypv-rudder approved these changes
Several changes to the doc with @shrouti1507 's help. Looks good to me now :)

2021-07-02 09:05 UTC, utsabc approved these changes
LGTM

2021-07-02 09:11 UTC, arnab-p approved these changes

2021-07-02 09:11 UTC, merged