Onboarding active campaign docs
rudderlabs/rudderstack-docs pull request #16
Opened 2021-01-14 14:50 UTC by utsabc

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-01-19 10:35 UTC, ameypv-rudder requested changes

2021-01-19 10:35 UTC, ameypv-rudder commented on destinations/active-campaign.md
> +Do not add native Adjust SDK to your project as it will prevent you from successful integration. Please refer to the screenshot below for more details:
Please review this - I think it is not relevant for the ActiveCampaign destination.

cc @arnab-p @utsabc

2021-01-19 10:35 UTC, ameypv-rudder commented on destinations/active-campaign.md
> +To send custom fields to ActiveCampaign, you will need to first create the custom fields in ActiveCampaign for each custom field that you want to send. Then when you call `identify` with keys that ma
Rewrote this section for more clarity. Please review.

2021-01-19 11:35 UTC, utsabc commented on destinations/active-campaign.md
> +Do not add native Adjust SDK to your project as it will prevent you from successful integration. Please refer to the screenshot below for more details:
Yep, my bad will fix this

2021-01-19 11:37 UTC, utsabc commented on destinations/active-campaign.md
> +To send custom fields to ActiveCampaign, you will need to first create the custom fields in ActiveCampaign for each custom field that you want to send. Then when you call `identify` with keys that ma
Looks good

2021-01-28 07:46 UTC, arnab-p approved these changes

2021-01-28 07:47 UTC, ameypv-rudder approved these changes

2021-01-28 07:48 UTC, merged