Algolia destination
rudderlabs/rudderstack-docs pull request #185
Opened 2021-09-07 08:49 UTC by abandonned

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-09-07 13:08 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +* `eventType` can only be either `click`, `view` or `conversion`.
What happens if the `eventType` is anything other than these three? Is the event dropped?

2021-09-07 13:09 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +For all the event types (`eventType`), either `filters` or `objectIds` must be passed and **not both**.
what happens otherwise? We should specify this.

2021-09-07 13:10 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +### E-Commerce Events
I added this heading. Please confirm if it looks okay.

2021-09-07 13:12 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +For the `click` event type, if you pass `objectIds`, then you must pass either **both** or **none** of the `positions` and `queryId` fields. Also, the length of `objectIds` and `positions` arrays sho
Again, we should specify what if the condition isn't met.

2021-09-07 13:17 UTC, abandonned commented on destinations/testing-and-personalization/algolia.md
> +* `eventType` can only be either `click`, `view` or `conversion`.
yeah event will be dropped.

2021-09-07 13:18 UTC, abandonned commented on destinations/testing-and-personalization/algolia.md
> +For all the event types (`eventType`), either `filters` or `objectIds` must be passed and **not both**.
event will be dropped if both or none of them is provided.

2021-09-07 13:20 UTC, abandonned commented on destinations/testing-and-personalization/algolia.md
> +For the `click` event type, if you pass `objectIds`, then you must pass either **both** or **none** of the `positions` and `queryId` fields. Also, the length of `objectIds` and `positions` arrays sho
if only one of positions or queryId is provided then we drop the event.
for 2nd part  if objectId and position both have length > 20 , then we keep the first 20 but if it has length <20, and they are not equal then we drop the call.

2021-09-07 13:21 UTC, abandonned commented on destinations/testing-and-personalization/algolia.md
> +### E-Commerce Events
yeah no issues.

2021-09-07 13:28 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +* `eventType` can only be either `click`, `view` or `conversion`.
cool. Will include this bit.

2021-09-07 13:39 UTC, ameypv-rudder approved these changes

2021-09-08 10:28 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +In case you have already specified the mapping in the dashboard, you don't need to send the same `eventType` in the `track` call.
Now that the precedence has changed (track call over dashboard mapping) - will this need to be changed? if track gets a higher precedence, the user might want to specify the eventType in the call rather than specifying it in the dashboard.

2021-09-08 10:33 UTC, abandonned commented on destinations/testing-and-personalization/algolia.md
> +In case you have already specified the mapping in the dashboard, you don't need to send the same `eventType` in the `track` call.
no  no it is still optional. We will give it priority only if it is passed in call.

2021-09-08 11:03 UTC, arnab-p requested changes

2021-09-08 11:03 UTC, arnab-p commented on destinations/testing-and-personalization/algolia.md
> +* `positions` must be an array of integers. It must be passed for only `click` type events. Only first 20 values will be passed.
Lets convert this into a table. It'll be easier to read

2021-09-08 11:21 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +Please note the required criteria of Algolia:
I've already changed this to:

To successfully send events to Algolia, the following criteria must be met:

2021-09-08 11:40 UTC, ameypv-rudder commented on destinations/testing-and-personalization/algolia.md
> +* `eventType` can only be either `click`, `view` or `conversion`. Otherwise, the event will be dropped.
makes sense

2021-09-08 12:51 UTC, arajguha approved these changes

2021-09-08 13:16 UTC, arnab-p approved these changes

2021-09-08 13:19 UTC, merged