Documentation for Cordova SDK
rudderlabs/rudderstack-docs pull request #194
Opened 2021-09-13 13:15 UTC by ameypv-rudder

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-09-16 09:31 UTC, Manashi-1881 approved these changes

2021-09-16 10:06 UTC, pallabmaiti approved these changes

2021-09-16 10:51 UTC, arnab-p requested changes
Two broad comments - 

- Remove the `integrations` from all the scripts except the section where we specifically talk about this. 
- All the headings are in the title case. Sentence case looks better IMO. It goes better with the flow of reading.

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +Refer to the [**GitHub repository**](https://github.com/rudderlabs/rudder-sdk-cordova) to access the SDK's codebase and the sample implementation.
Let's link the sample application to the exact directory in github.

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +RudderClient.initialize( <SOURCE_WRITE_KEY> , {
```suggestion
RudderClient.initialize( WRITE_KEY , {
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "dataPlaneUrl": <YOUR_DATA_PLANE_URL> ,
```suggestion
  "dataPlaneUrl": DATA_PLANE_URL ,
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +```javascript
Lets put a minimal script to initialize the SDK. So many options for the first time, is confusing.

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "integrations": {
Remote the `integrations` block altogether. User might think that it's only available with Mixpanel and Amplitude

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +| `writeKey` | `string` | Required | Your Cordova source write key. |
```suggestion
| `writeKey` | `string` | Required | Your Cordova source `writeKey`|
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "logLevel": 0,
Don't we support `enum` for this? If not, we should. If yes, it's better to point to the enum instead of a blatant integer value

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +As a best practice, make sure `identify` is called at the start of every session or page load for logged-in users, if possible. This will ensure all their latest traits are captured.
```suggestion
As a best practice, we recommend calling `identify` at the start of every session or page load for logged-in users. This will ensure all their latest traits are captured in every subsequent events.
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "birthday": "17/07/1984",
Do we support this format of `dob` in downstream destinations? If not, we should give a better example.

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +The `track` call lets you record the customer events, i.e. the actions that they perform, along with any properties associated with them.
```suggestion
The `track` call lets you record the customer events, i.e. the actions that they perform, along with any properties associated with the action.
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +2. `Application Opened`
Don't we support `Application Backgrounded` and `Application Updated`?

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
Don't we support automatic screen recording?

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +You can use the `reset` method to clear the persisted `traits` for the `identify` call. This is required for the `Logout` operations.
```suggestion
You can use the `reset` method to clear the persisted `traits` from the `identify` call. We recommend calling it at the `Logout` operations.
```

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +{% endhint %}
Remove this section as we don't support device-mode for now

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
May be an extra line by mistake?

2021-09-16 10:51 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
Missing FAQ section. We can put some debug tips in this section.

2021-09-16 10:53 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +Refer to the [**GitHub repository**](https://github.com/rudderlabs/rudder-sdk-cordova) to access the SDK's codebase and the sample implementation.
will do

2021-09-16 11:05 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +| `writeKey` | `string` | Required | Your Cordova source write key. |
fixed and clarified a little more.

2021-09-16 11:07 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +```javascript
> Two broad comments -
> 
> * Remove the `integrations` from all the scripts except the section where we specifically talk about this.
> * All the headings are in the title case. Sentence case looks better IMO. It goes better with the flow of reading.

Got it. We use headings in title case throughout our docs, but in the revamp we plan to change it sentence case. I have made this change throughout the doc.

2021-09-16 11:33 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +2. `Application Opened`
Due to the difference in the `context` object being passed to the underlying Android SDK, it's not detecting the `Application Backgrounded` and `Application Updated` events.  So as of now we are not supporting, but we can try to pick up things like this and add the support for Automatic Recording of Screens and better supporting Life cycle events across Cross platform SDK's like Flutter & Cordova

2021-09-16 11:33 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "birthday": "17/07/1984",
Done.

2021-09-16 11:34 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
Due to the difference in the `context` object being passed to the underlying Android and iOS SDK's, it's not detecting the screen changes automatically.  So as of now we are not supporting, but we can try to pick up things like this and add the support for Automatic Recording of Screens and better supporting Life cycle events across Cross platform SDK's like Flutter & Cordova

2021-09-16 11:35 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "birthday": "17/07/1984",
No, we support `yyyy-MM-dd`  format in destinations. Updating accordingly

2021-09-16 11:35 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "integrations": {
Sure

2021-09-16 11:40 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "logLevel": 0,
No, we are not supporting yet.  Yes, Will do it

2021-09-16 13:02 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "logLevel": 0,
Added support for it to the SDK and updated the docs accordingly

2021-09-20 06:09 UTC, arnab-p requested changes

2021-09-20 06:09 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +| `dataPlaneUrl` | `string` | Your RudderStack Data Plane URL. | [**https://api.rudderlabs.com**](https://api.rudderlabs.com) |
Are we sure it's not `https://hosted.rudderlabs.com`?

2021-09-20 06:09 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
This section is redundant as we have self explanatory names

2021-09-20 06:09 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +You can use the `setAnonymousId` method to override the default `anonymousId`, as shown:
Let's explain how we generate the `anonymousId` as well

2021-09-20 06:09 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +If you run into any issues regarding the RudderStack Cordova SDK, you can turn on the `VERBOSE` or `DEBUG` logging to find out what the issue is.
```suggestion
If you face any unexpected behavior of the SDK, you can turn on the `VERBOSE` or `DEBUG` logging to understand more about it.
```

2021-09-20 06:27 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +  "controlPlaneUrl": "https://api.rudderstack.com"
Done

2021-09-20 06:27 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +* Check the **Configuring your RudderStack Client** section below for detailed information on the parameters you can send in the `configuration` object.
Yeah, Amey said he will take care of it

2021-09-20 06:28 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +RudderClient.initialize( WRITE_KEY , {
Done

2021-09-20 06:28 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +The `identify` call lets you identify a visiting user and associate them to their actions. It also lets you record the traits about them like their name, email address, etc.
Done

2021-09-20 06:29 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +})
Okay Sure, we are having a separate section for `options` object anyway though

2021-09-20 06:33 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +For more information on the behavior of the `integrations` property, refer to the **Enabling/Disabling Events for Specific Destinations** section below.
Yes, updated it accordingly

2021-09-20 06:34 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +| `options` | `JSON Object` | Optional | Extra options for the `group` event. |
Sure

2021-09-20 06:39 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
Yeah removing it

2021-09-20 06:39 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +| `dataPlaneUrl` | `string` | Your RudderStack Data Plane URL. | [**https://api.rudderlabs.com**](https://api.rudderlabs.com) |
No, it should be `https://hosted.rudderlabs.com`. Updated accordingly

2021-09-20 06:39 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +You can use the `setAnonymousId` method to override the default `anonymousId`, as shown:
Added

2021-09-20 06:39 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +If you run into any issues regarding the RudderStack Cordova SDK, you can turn on the `VERBOSE` or `DEBUG` logging to find out what the issue is.
Updated

2021-09-20 07:07 UTC, desusai7 commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +})
Updated

2021-09-20 09:11 UTC, arnab-p approved these changes

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +})
```RudderClient.identify("userId", {
    "address": {
        "city": "Hyderabad",
        "country": "India",
        "state": "Telangana",
    },
    "birthday": "1984/07/17",
    "company": {
        "name": "RudderStack",
        "id": "RS",
        "industry": "IT"
    },
    "email": "john@rudderstack.com",
    "firstName": "john",
});
```

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +## Track
```suggestion

## Track
```

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
```suggestion

```

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
```suggestion

```

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +## Configuring the RudderStack client
```suggestion

## Configuring the RudderStack client
```

2021-09-20 09:11 UTC, arnab-p commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.md
> +
```suggestion

```

2021-09-20 09:18 UTC, merged