Update user permissions to include detailed steps
rudderlabs/rudderstack-docs pull request #198
Opened 2021-09-16 10:32 UTC by ameypv-rudder

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-09-16 10:50 UTC, ashishRudder commented on warehouse-actions/snowflake.md
> +This command creates the role `RUDDER_ROLE` in Snowflake. After creating the role, you can grant object privileges to it. Also, the user `RUDDER` will be created and access control security for the s
The user `RUDDER` wont get created with this command.

2021-09-16 10:53 UTC, ameypv-rudder commented on warehouse-actions/snowflake.md
> +This command creates the role `RUDDER_ROLE` in Snowflake. After creating the role, you can grant object privileges to it. Also, the user `RUDDER` will be created and access control security for the s
got it - updated the sentence.

2021-09-16 10:55 UTC, ashishRudder commented on warehouse-actions/snowflake.md
> +This command allows the role `RUDDER_ROLE` to look up the objects within the warehouse `<YOUR_WAREHOUSE>`. Replace "<YOUR_WAREHOUSE>" with the exact name of your data warehouse in Snowflake.
They need to replace <YOUR_WAREHOUSE> not "<YOUR_WAREHOUSE>"

2021-09-16 14:49 UTC, ashishRudder requested changes

2021-09-17 05:17 UTC, merged

2021-09-17 09:50 UTC, ashishRudder commented on warehouse-actions/snowflake.md
> +This command allows `RUDDER_ROLE` to have full access to the schema `_rudderstack`.
This `_rudderstack` needs to be changed to `_RUDDERSTACK`

2021-09-17 11:06 UTC, RanjeetMishra commented on warehouse-actions/snowflake.md
> +Run the SQL queries below in the **exact order** to grant the necessary permissions for the Warehouse Actions source:
Ganesh will provide some screenshots too what does it mean by running commands as accountadmin when using snowflake worksheet. This might be helpful to add somewhere.

2021-09-17 11:17 UTC, ameypv-rudder commented on warehouse-actions/snowflake.md
> +Run the SQL queries below in the **exact order** to grant the necessary permissions for the Warehouse Actions source:
yes, will add an explicit instruction at the start that the commands need to be run as ACCOUNTADMIN

2021-09-22 05:22 UTC, ameypv-rudder commented
Hey @RanjeetMishra all the queries are grouped and can be seen here: https://docs.rudderstack.com/warehouse-actions/snowflake