User permissions for setting up Warehouse Actions sources
rudderlabs/rudderstack-docs pull request #201
Opened 2021-09-17 08:35 UTC by ameypv-rudder

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-09-17 09:46 UTC, ashishRudder requested changes

2021-09-17 09:46 UTC, ashishRudder commented on warehouse-actions/google-bigquery.md
> +RudderStack creates a dedicated dataset called `rudderstack` in your project that is used to store the state of each data sync.
`rudderstack` needs to be updated with `rudderstack_`

2021-09-17 11:04 UTC, RanjeetMishra commented on warehouse-actions/amazon-redshift.md
> +## Setting Up the Source
This comment applies for all WH sources.

2021-09-17 11:08 UTC, ameypv-rudder commented on warehouse-actions/amazon-redshift.md
> +## Setting Up the Source
sure - will look into this for all the WH Actions sources.

2021-09-17 14:09 UTC, ameypv-rudder commented on warehouse-actions/amazon-redshift.md
> +This command allows the user `rudder` to read data from all the tables in the schema `<YOUR_SCHEMA>`.
Slightly tweaked the sentence to make the idea clearer.

2021-09-20 08:41 UTC, ashishRudder commented on warehouse-actions/amazon-redshift.md
> +### Optional permissions to grant on the schema objects
it should be written as schemas' objects?
We are providing grant on objects inside schema.

2021-09-20 08:43 UTC, ashishRudder commented on warehouse-actions/postgresql.md
> +### Optional permissions to grant on the schema objects
same here.

2021-09-22 05:04 UTC, RanjeetMishra reviewed
LGTM except BigQuery.
Fort BigQuery we are not mentioning user to create rudderstack_ schema

2021-09-22 05:19 UTC, ameypv-rudder commented
> LGTM except BigQuery.
> Fort BigQuery we are not mentioning user to create rudderstack_ schema

Hey Ranjeet, as discussed this information is already present and will be visible to the user as a tip/info box.

2021-09-22 05:20 UTC, ameypv-rudder commented on warehouse-actions/amazon-redshift.md
> +## Setting Up the Source
I have the FAQ from @ashishRudder on this - will update all the WH actions docs with the screenshot and the info.

2021-09-22 07:12 UTC, RanjeetMishra approved these changes

2021-09-22 07:46 UTC, ashishRudder commented
> LGTM except BigQuery.
> Fort BigQuery we are not mentioning user to create rudderstack_ schema

It has been added in the latest commits.

2021-09-22 11:50 UTC, ashishRudder approved these changes

2021-09-23 15:17 UTC, merged