JS SDK v1 to v1.1 migration guide
rudderlabs/rudderstack-docs pull request #203
Opened 2021-09-20 11:05 UTC by ameypv-rudder

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-09-20 11:30 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +* Then, go to **Behaviors**, and check that the sub-path `/v1.1/*` is **not configured to be blocked** in any way.
Is Behaviors a specific option name that the reader will see? please confirm.

2021-09-20 11:32 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +<script src="https://<subdomain>.<yourdomain>.com/v1.1/rudder-analytics.min.js" />
please confirm if this way of presenting the script snippet is okay.

2021-09-20 11:33 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +* Download all the destination SDKs as listed [**here**]().
I will move this doc: https://www.notion.so/rudderstacks/Download-links-for-RudderStack-s-Destination-SDKs-1aac949ce9884597afcca26ab8661811

in the docs and point the link here. Please confirm if that's okay.

2021-09-20 11:34 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +<script src="https://cdn.customer.com/custom-analytics.js"></script>
here, `custom-analytics.js` is just an example right? the name could be anything else?

2021-09-20 11:35 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +{% endhint %}
Please confirm if this representation is technically accurate.

2021-09-20 12:51 UTC, MoumitaM commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +* Then, go to **Behaviors**, and check that the sub-path `/v1.1/*` is **not configured to be blocked** in any way.
When you select one specific cloudfront distribution, it basically lead you to an General section.  Similarly Behaviour is another section displayed as a tab view.

2021-09-20 13:39 UTC, MoumitaM commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +{% endhint %}
What we wanted to represent is if the base path is "baseUrl" then 
the JS SDK should be at - baseUrl/core_js_sdk
and the dest. sdks should be at - baseUrl/js-integrations/*.min.js. So, core_js_sdk and js-integrations folder should be at the same level.

2021-09-20 13:39 UTC, MoumitaM commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +<script src="https://cdn.customer.com/custom-analytics.js"></script>
Yes

2021-09-21 11:23 UTC, MoumitaM approved these changes

2021-09-22 06:10 UTC, ameypv-rudder commented
PR to be merged once the JS SDK is revamped. The PR for it is being reviewed currently.

2021-10-05 09:23 UTC, saikumarrs requested changes

2021-10-05 09:23 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +
Please add a reference to https://docs.rudderstack.com/user-guides/how-to-guides/custom-domains here which will provide more details about CDN forwarding/proxying.

2021-10-05 09:23 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +* Go to the distribution whose origin is set to RudderStack's CDN. Ensure that the entire domain (**`https://cdn.rudderlabs.com`**) is set as the origin.
We can add another statement here to stress on forwarding our whole CDN path. Something along the lines of,
"We recommend forwarding our entire CDN path "https://cdn.rudderlabs.com" so that you don't miss any files/directories that we might add later"

2021-11-02 12:50 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/js-sdk-version-migration.md
> +* Go to the distribution whose origin is set to RudderStack's CDN. Ensure that the entire domain (**`https://cdn.rudderlabs.com`**) is set as the origin.
makes sense. Added this information.

2021-11-02 13:33 UTC, ameypv-rudder commented
Closing this PR as all the changes are ported in the revamped format in this PR: https://github.com/rudderlabs/rudderstack-docs/pull/249. @saikumarrs all your suggestions/feedback is incorporated in this PR.

2021-11-02 13:33 UTC, closed without merging