Update location of recovery_data
rudderlabs/rudderstack-docs pull request #23
Opened 2021-01-29 07:07 UTC by akagr

## Description of the change

> The  location of `recovery_data.json` file seems to be different than what's in docs. I'm running latest version of rudder, so updating the docs.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklists

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-01-29 08:08 UTC, SumanthPuram requested changes

2021-01-29 08:08 UTC, SumanthPuram commented on administrators-guide/admin-troubleshooting-guide.md
> +1. Check if the server is running in _normal_ mode in the file `/data/rudderstack/recovery_data.json` .
In Kubernetes, we mount a persistent volume at `/data/rudderstack`
For docker-compose and native installations, these go-to `/tmp/rudderstack`

We should mention that the user needs to check both the locations based on the type of installation.

2021-01-29 08:08 UTC, SumanthPuram commented
Thanks for the PR @akagr. We need to add the other option too for the location of the recovery file.

2021-01-29 16:11 UTC, akagr commented
@SumanthPuram On it. Thanks for reviewing 👍

2021-02-08 15:17 UTC, ameypv-rudder approved these changes
Happy to approve the changes once the suggestions are incorporated.

2021-02-15 06:58 UTC, akagr commented
@SumanthPuram @ameypv-rudder I was away on vacation. Updated the doc so it shows both possible paths of `recovery_data.json` file.

2021-02-15 07:01 UTC, SumanthPuram approved these changes

2021-02-24 07:15 UTC, merged