Firebase docs
rudderlabs/rudderstack-docs pull request #245
Opened 2021-11-01 08:24 UTC by 1abhishekpandey

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-01 08:46 UTC, pallabmaiti requested changes

2021-11-01 08:46 UTC, pallabmaiti commented on destinations/analytics/firebase.mdx
> +| `order_id`                  | `transaction_id`         |
@1abhishekpandey  Transaction id shouldn't be order id. Did we implement like this?

2021-11-01 08:46 UTC, pallabmaiti commented on destinations/analytics/firebase.mdx
> +The `reset` method calls `setUserId(null)` which removes the user ID.
@1abhishekpandey no need to mention setUserId(null)

2021-11-01 08:51 UTC, 1abhishekpandey commented on destinations/analytics/firebase.mdx
> +| `order_id`                  | `transaction_id`         |
Yes, it was implemented like this. I haven't modified this mapping. Please let me know if any changes are required w.r.t this.

2021-11-01 09:30 UTC, pallabmaiti commented on destinations/analytics/firebase.mdx
> +| `order_id`                  | `transaction_id`         |
I think we shouldn't map transaction_id

2021-11-01 12:13 UTC, pallabmaiti submitted a review, later dismissed

2021-11-01 12:52 UTC, ameypv-rudder approved these changes
Good to go!

2021-11-03 05:42 UTC, arnab-p approved these changes

2021-11-03 05:43 UTC, merged