Sendgrid PR migration
rudderlabs/rudderstack-docs pull request #252
Opened 2021-11-03 12:08 UTC by ameypv-rudder

## Description of the change

> The PR [here](https://github.com/rudderlabs/rudderstack-docs/pull/229) has been converted and ported as per the latest documentation formatting and styling conventions.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-15 05:12 UTC, saikumarrs commented on destinations/marketing/sendgrid.mdx
> +| **Cloud mode**      | **Supported** | -          | **Supported** |
Why is it not supported for "Mobile"?

2021-11-19 07:25 UTC, abandonned commented on destinations/marketing/sendgrid.mdx
> +| **Cloud mode**      | **Supported** | -          | **Supported** |
Earlier we were sending properties inside integration object and for mobile version it only supported boolean values therefore we couldn't support. But now everything is inside properties therefore we can support mobile mode as well.

2021-11-22 09:19 UTC, saikumarrs requested changes

2021-11-22 09:19 UTC, saikumarrs commented on destinations/marketing/sendgrid.mdx
> +Each object inside attachments array must atleast contain the `content` and `filename` fields. If these fields are absent, then the object will be dropped. However the call will **not** be discarded.
Correct the typo, "at least"

2021-11-22 09:19 UTC, saikumarrs commented on destinations/marketing/sendgrid.mdx
> +---
The following issues need to be addressed throughout the document and also wherever applicable.

“Subject” -> “Email Subject”
“Get mail from traits” -> “Get email ID from traits”
“Reply To Email” -> “Reply-To Email ID”
"Reply To Name" -> "Reply-To Name"
“Email” -> “Email ID”
“Mail Settings” -> “Email Settings”

2021-11-23 12:17 UTC, arajguha commented on destinations/marketing/sendgrid.mdx
> +Each object inside attachments array must at least contain the `content` and `filename` fields. If these fields are absent, then the object will be dropped. However the call will **not** be discarded
should we call it `event` instead of `call`?

2021-11-23 12:18 UTC, ameypv-rudder commented on destinations/marketing/sendgrid.mdx
> +Each object inside attachments array must at least contain the `content` and `filename` fields. If these fields are absent, then the object will be dropped. However the call will **not** be discarded
Sure - that makes sense. I will make the change for these instances.

2021-11-23 13:53 UTC, ameypv-rudder commented on destinations/marketing/sendgrid.mdx
> +---
@abandonned has incorporated these changes in the webapp and the docs are updated as well.

2021-11-23 14:01 UTC, abandonned approved these changes

2021-11-23 14:24 UTC, merged