Hotjar - fix: add identify info
rudderlabs/rudderstack-docs pull request #261
Opened 2021-11-10 17:52 UTC by akashrpo

## Description of the change

> updated the identify docs as per the js-sdk code

## Type of change
- [ ] fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-11 02:41 UTC, saikumarrs requested changes

2021-11-11 02:41 UTC, saikumarrs commented on destinations/analytics/hotjar.mdx
> -There is **no need** to call any of `identify`, `page` or `track`methods explicitly, as Hotjar auto-tracks your user data.
I would assume Hotjar still auto-tracks data. So, let's keep this statement excluding `identify`?

2021-11-11 02:41 UTC, saikumarrs commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
Can we add a link to their docs if available?

2021-11-11 02:41 UTC, saikumarrs commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
I've redacted the redundant parts. Feel free to rephrase to something better.
```suggestion
Before you can begin making calls to `identify`, `User Attributes` must be enabled in your Hotjar dashboard for each site.
```

2021-11-11 02:41 UTC, saikumarrs commented on destinations/analytics/hotjar.mdx
>  <img src="../../assets/image (42).png" /><span class="imageTitle">Hotjar Connection Settings in RudderStack</span>
The image seems to be obsolete as it's a device-mode only destination. Let's update it.

2021-11-11 05:08 UTC, ameypv-rudder commented on destinations/analytics/hotjar.mdx
>  <img src="../../assets/image (42).png" /><span class="imageTitle">Hotjar Connection Settings in RudderStack</span>
All the event stream destination images are being updated - ETA is next week.

2021-11-11 05:45 UTC, akashrpo commented on destinations/analytics/hotjar.mdx
> -There is **no need** to call any of `identify`, `page` or `track`methods explicitly, as Hotjar auto-tracks your user data.
reverted

2021-11-11 05:46 UTC, akashrpo commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
added link to `User Attributes`

2021-11-11 05:46 UTC, akashrpo commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
seems good. rephrased it

2021-11-11 05:47 UTC, akashrpo commented on destinations/analytics/hotjar.mdx
>  <img src="../../assets/image (42).png" /><span class="imageTitle">Hotjar Connection Settings in RudderStack</span>
updated the connection settings image

2021-11-11 06:07 UTC, saikumarrs commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
Let's add this article reference that explains the process

2021-11-11 07:44 UTC, akashrpo commented on destinations/analytics/hotjar.mdx
> +Before you can begin making calls to `identify`, User Attributes must be enabled in your Hotjar dashboard for each site you want to User Attributes within your account.
added the article reference for `User Attributes`

2021-11-11 07:56 UTC, saikumarrs approved these changes

2021-11-11 08:27 UTC, utsabc approved these changes
Looks good

2021-11-12 05:35 UTC, ameypv-rudder approved these changes
Standardized the content and made some formatting fixes.

2021-11-12 06:25 UTC, merged