klaviyo docs onboarding, minor doc fix for AC
rudderlabs/rudderstack-docs pull request #27
Opened 2021-02-05 15:50 UTC by utsabc

## Onboarding Klaviyo Docs

> Docs for Klaviyo dest

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)

2021-02-12 06:17 UTC, ameypv-rudder reviewed
Made some changes to the content and left 1 comment for your review, @utsabc.

Looks good to me otherwise.

2021-02-12 06:17 UTC, ameypv-rudder commented on destinations/klaviyo.md
> +The `identify` call lets you associate a user with their actions and capture all the relevant traits about them. This information includes unique `userid` as well as any optional information such as
Please review this. Is email optional or mandatory? In some of the other sections, we mentioned that `name` and `email` are required. We say:

"The `email` or `phone` trait is a mandatory trait for mapping a user to Klaviyo."

@utsabc @arnab-p

2021-02-12 06:27 UTC, utsabc commented on destinations/klaviyo.md
> +The `identify` call lets you associate a user with their actions and capture all the relevant traits about them. This information includes unique `userid` as well as any optional information such as
Sorry I missed this part, I Klaviyo we are mapping the user unique to email or phone, i.e either of these two is required to make an identity call. So here `userid` is not mandatory or uniquely used in this destination. Other `traits` are optional.

2021-02-16 08:42 UTC, arnab-p approved these changes

2021-02-23 13:15 UTC, utsabc commented
@ameypv-rudder, updated the docs after device mode integration, could please review the changes once.

2021-02-24 07:32 UTC, ameypv-rudder approved these changes

2021-02-24 08:20 UTC, arnab-p approved these changes

2021-02-24 08:20 UTC, arnab-p commented on destinations/klaviyo.md
> +  }
Let's remove this part

2021-02-24 08:20 UTC, arnab-p commented on destinations/klaviyo.md
> +  "XUepkK",
Let's use a value like `sampleGroupId`. It's more intuitive to understand.

2021-03-03 08:51 UTC, Manashi-1881 commented on destinations/klaviyo.md
> +rudderanalytics.group(
use node js group call example

2021-03-03 09:04 UTC, utsabc commented on destinations/klaviyo.md
> +  }
done

2021-03-03 09:04 UTC, utsabc commented on destinations/klaviyo.md
> +  "XUepkK",
done

2021-03-03 09:04 UTC, utsabc commented on destinations/klaviyo.md
> +rudderanalytics.group(
done

2021-03-03 09:09 UTC, Manashi-1881 approved these changes

2021-03-03 10:25 UTC, ameypv-rudder approved these changes

2021-03-08 07:07 UTC, arnab-p requested changes

2021-03-08 07:07 UTC, arnab-p commented on destinations/klaviyo.md
> +The `userId`,`email` or `phone` trait is a mandatory trait for mapping a user to Klaviyo. If a user already exists, the new values will be updated for that user . You can further add the user to the
```suggestion
The `userId`, `email`, or `phone` trait is a mandatory trait for mapping a user to Klaviyo. If a user already exists, the new values will be updated for that user. You can further add the user to the list if default `listId` is present on the RudderStack dashboard. You can also do so by adding `listId` in the `properties` within the `traits`, this will override the `listId` you used on the dashboard for that particular event. You can also subscribe the user to a list by setting `subscribe` option to `true`.
```

2021-03-08 07:07 UTC, arnab-p commented on destinations/klaviyo.md
> +Similar to `listId` adding `consent` and `smsConsent` property will override the value stored in the control plane for the specific event.
```suggestion
Similar to `listId` adding `consent` and `smsConsent` property will override the settings on the RudderStack dashboard for the specific event.
```

2021-03-08 07:07 UTC, arnab-p commented on destinations/klaviyo.md
> +Adding or subscribing users to specific list is only available in cloud-mode integration. To know more about the difference between Cloud mode and Device mode in RudderStack, read the [RudderStack co
```suggestion
**Adding or subscribing users to a specific list is only available in cloud-mode** integration. To know more about the difference between Cloud mode and Device mode in RudderStack, read the [RudderStack connection modes](https://docs.rudderstack.com/get-started/rudderstack-connection-modes) guide.
```

2021-03-08 07:07 UTC, arnab-p commented on destinations/klaviyo.md
> +Apart from either `userId`,`email` or `phone`, the other fields are not mandatory.
```suggestion
Apart from either `userId`, `email` or `phone`, the other fields are not mandatory.
```

2021-03-08 07:07 UTC, arnab-p commented on destinations/klaviyo.md
> +Adding `consent` and `smsConsent` property in user traits will override the value stored in control plane for the specific event.
```suggestion
Adding `consent` and `smsConsent` property in user traits will override the settings on the RudderStack dashboard for the specific event.
```

2021-03-08 11:20 UTC, arnab-p approved these changes

2021-03-08 11:20 UTC, arnab-p commented on destinations/active-campaign.md
>  ```javascript
```suggestion
```xcode
```

2021-03-08 11:20 UTC, arnab-p commented on destinations/klaviyo.md
> +```javascript
```suggestion
```xcode
```

2021-03-08 13:03 UTC, arnab-p approved these changes

2021-03-08 13:05 UTC, merged