Event Stream sources revamp
rudderlabs/rudderstack-docs pull request #271
Opened 2021-11-17 11:22 UTC by ameypv-rudder

## Description of the change

> Updated screenshots
> Standardized all file names for consistency
> Standardized the section content for all the SDK sources
> Improved clarity of some instructions
> Incorporated changes from the following PRs:

- https://github.com/rudderlabs/rudderstack-docs/pull/213
- https://github.com/rudderlabs/rudderstack-docs/pull/262

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-19 18:36 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +Since the AMP source sends the data directly to the RudderStack data plane, we support only <code class="inline-code">cloud mode</code> destinations for AMP projects. For more information on the clou
I think "cloud mode" should be bold instead of an inline code element because it is not code.

2021-11-19 18:50 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +- Add an AMP source in your RudderStack [**dashboard**](https://app.rudderstack.com).
It might be more clear that these are steps to be followed in order if this is an ordered list (numbered) instead of an unordered list (bullet points). I think this would be a good to change in all of the docs.

2021-11-19 19:00 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +Prepend <code class="inline-code">properties.</code> with the <code class="inline-code">extraUrlParams</code> so that it can be parsed as the property value in RudderStack.
This sentence doesn't make sense to me. What is meant by "prepend?" Aren't the `properties` contained within the `extraUrlParams` object?

2021-11-19 19:03 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +You can use the [**AMP Linker**](https://amp.dev/documentation/examples/advertising-analytics/joining_analytics_sessions/) feature to ensure a merged session for users navigating from cached AMP page
There should be a space between "cached AMP pages" and "\(on an AMP cache\)."

2021-11-19 19:16 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
> +If you come across any issue while using the Android SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-android/issues).
Should be "an issue" or "any issues."

2021-11-19 19:31 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +- You will need to set up a [**RudderStack account**](https://app.rudderstack.com).
Should be an ordered list (numbered) in my opinion.

2021-11-19 19:35 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +    state: "California",
If we're using initialism for Los Angeles and the United States of America, we should put "CA" instead of "California" for consistency.

2021-11-19 19:39 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +Check the <strong>Configuring your options object</strong> section below for detailed information on the parameters you can send in the <code class="inline-code">options</code> object.
Should be "Configuring the `options` object." Would also be good if it linked to the section.

2021-11-19 19:47 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +You configure logging behaviour of your SDK by sending the value of the `logLevel` property of the `configuration` object and pass it over to the `initialize` call as shown below:
Should we use "behavior" (American English) instead of "behaviour" (British English)? It's a small detail, but I think using the British spelling might throw off American readers. We want readers to easily absorb the information in the docs, not think about the spelling of "behaviour."

2021-11-19 20:19 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
> +Refer to <strong>The options parameter</strong> section below for more information on the <code class="inline-code">options</code> object and its fields.
"The options parameter section" should link to the section. This should be done for all occurrences in this doc.

2021-11-19 20:41 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
> +  "userId",
Indentation should be 4 spaces, as suggested in [Microsoft's C# coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions). All code blocks with 2 space indentation should be changed.

2021-11-19 20:52 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
> +If you come across any issue while using the .NET SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-.net/issues/new).
Should be "an issue" or "any issues."

2021-11-19 20:55 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
> +You can install the RudderStack Go SDK via the `go get` command. We highly recommend that you use a tool like **Godep** to avoid the issues related to any breaking API changes introduced between majo
Godep is archived and suggests using a different tool. See: https://pkg.go.dev/github.com/tools/godep

2021-11-19 20:58 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +The **RudderStack iOS SDK** integrates RudderStack with your iOS application track the event data and send it to your preferred destinations.
This sentence does not make sense.

2021-11-19 21:02 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +We distribute our iOS SDK through [**Cocoapods**](https://cocoapods.org) and [**Carthage**](https://github.com/Carthage/Carthage). The recommended and easiest way to add the SDK to your project is th
The Cocoapods link could be changed to https://cocoapods.org/pods/Rudder.

2021-11-19 21:12 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +RudderStack uses SQLite to save the events to local database before sending it to RudderStack data-plane. Making calls like <code class="inline-code">SQLite.shutdown()</code> which is not thread-safe
This first sentence should be changed to "RudderStack uses [SQLite](https://sqlite.org/index.html) to store events before sending them to the RudderStack data plane."

2021-11-19 21:14 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +RudderStack doesn't persist the traits for the group across the sessions.
Might be better to change "doesn't" to "<strong>does not</strong>."

2021-11-19 21:21 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +You can easily develop a device mode destination in case RudderStack doesn't support it already, by following the steps listed in this section.
This sentence is too long. Might be better to break it up into something like "You can easily develop a device mode destination in case RudderStack doesn't support it already. Simply follow the steps listed in this section."

2021-11-19 21:22 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +More information on the RudderStack device mode can be found in the <a href="https://rudderstack.com/docs/connections/rudderstack-connection-modes//">RudderStack Connection Modes</a> guide.
I think the word "guide" should be included within the `a` tags.

2021-11-19 21:23 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +If you come across any issue while using the iOS SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-ios/issues/new).
Should be "an issue" or "any issues."

2021-11-19 22:10 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-java-sdk.mdx
> +The `track` call lets you record the user actions along with their associated properties. Each user action is called an **event**.
The first sentence should be changed to "The `track` call lets you record user actions along with their associated properties" (removed "the").

2021-11-19 22:14 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
> +If you come across any issue while using the Node.js SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-node/issues/new).
Should be "an issue" or "any issues."

2021-11-19 22:16 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
> +If you come across any issue while using the PHP SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-php-sdk/issues/new).
Should be "an issue" or "any issues."

2021-11-19 22:18 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
> +The **RudderStack Python SDK** lets you track your customer event data from your Ruby code and send it to your specified destination platforms.
"Ruby code" should be changed to "Python code" or "Python application."

2021-11-19 22:25 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
> +On the iOS devices, According to the Apple <a href="https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor">documentation</a>, if the device has multiple apps from the s
Should be "On iOS devices" (remove "the") and "According" should not be capitalized.

2021-11-19 22:35 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
> +If you come across any issue while using the Flutter SDK, you can also open an issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-flutter/issues).
Should be "an issue" or "any issues."

2021-11-20 00:04 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> +If you come across any issue while using the React Native SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-react-native/issues/new).
Should be "an issue" or "any issues."

2021-11-20 00:09 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> +If you come across any issue while using the Unity SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-unity/issues/new).
Should be "an issue" or "any issues."

2021-11-23 10:41 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +Since the AMP source sends the data directly to the RudderStack data plane, we support only <code class="inline-code">cloud mode</code> destinations for AMP projects. For more information on the clou
Sure - fixed this.

2021-11-23 10:41 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +- Add an AMP source in your RudderStack [**dashboard**](https://app.rudderstack.com).
Yep agreed- this might require some effort and time, though, as we standardize all docs. We can take this up as a separate activity.

2021-11-23 10:43 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +Prepend <code class="inline-code">properties.</code> with the <code class="inline-code">extraUrlParams</code> so that it can be parsed as the property value in RudderStack.
Clarified the sentence - basically every property name should be prefixed with `properties.` within the `extraUrlParams` object.

2021-11-23 10:43 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-amp-analytics.mdx
> +You can use the [**AMP Linker**](https://amp.dev/documentation/examples/advertising-analytics/joining_analytics_sessions/) feature to ensure a merged session for users navigating from cached AMP page
Agreed. Fixed this.

2021-11-23 11:07 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-android-sdk/index.mdx
> +If you come across any issue while using the Android SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-android/issues).
Fixed.

2021-11-23 11:07 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +- You will need to set up a [**RudderStack account**](https://app.rudderstack.com).
As discussed above, we can take this up as a separate activity.

2021-11-23 11:08 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +    state: "California",
Agreed. Made this change.

2021-11-24 10:02 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-unity-sdk.mdx
> +If you come across any issue while using the Unity SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-unity/issues/new).
Fixed.

2021-11-24 10:02 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-react-native-sdk.mdx
> +If you come across any issue while using the React Native SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-react-native/issues/new).
Fixed.

2021-11-24 10:02 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
> +If you come across any issue while using the Flutter SDK, you can also open an issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-flutter/issues).
Fixed.

2021-11-24 10:03 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.mdx
> +On the iOS devices, According to the Apple <a href="https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor">documentation</a>, if the device has multiple apps from the s
Rephrased the sentence for more clarity.

2021-11-24 10:03 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-python-sdk.mdx
> +The **RudderStack Python SDK** lets you track your customer event data from your Ruby code and send it to your specified destination platforms.
Oops - fixed this.

2021-11-24 10:16 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-node-sdk.mdx
> +If you come across any issue while using the Node.js SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-node/issues/new).
Fixed.

2021-11-24 10:25 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +The **RudderStack iOS SDK** integrates RudderStack with your iOS application track the event data and send it to your preferred destinations.
Fixed it.

2021-11-24 10:27 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +We distribute our iOS SDK through [**Cocoapods**](https://cocoapods.org) and [**Carthage**](https://github.com/Carthage/Carthage). The recommended and easiest way to add the SDK to your project is th
Updated the URL

2021-11-24 10:28 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +RudderStack uses SQLite to save the events to local database before sending it to RudderStack data-plane. Making calls like <code class="inline-code">SQLite.shutdown()</code> which is not thread-safe
Fixed this.

2021-11-24 10:29 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +RudderStack doesn't persist the traits for the group across the sessions.
Yep - fixed.

2021-11-24 10:31 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +You can easily develop a device mode destination in case RudderStack doesn't support it already, by following the steps listed in this section.
Thanks - made this change.

2021-11-24 10:32 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +More information on the RudderStack device mode can be found in the <a href="https://rudderstack.com/docs/connections/rudderstack-connection-modes//">RudderStack Connection Modes</a> guide.
We only anchor the exact name of the doc and exclude words like 'guide', 'support page', etc. Hence this way of presenting the sentence.

2021-11-24 10:39 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +If you come across any issue while using the iOS SDK, you can open a new issue on our [**GitHub Issues page**](https://github.com/rudderlabs/rudder-sdk-ios/issues/new).
Fixed.

2021-11-24 10:56 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-go-sdk.mdx
> +You can install the RudderStack Go SDK via the `go get` command. We highly recommend that you use a tool like **Godep** to avoid the issues related to any breaking API changes introduced between majo
Updated to dep - although this repo is archived as well. Any thoughts on what other alternative we could suggest?

2021-11-24 11:11 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +You configure logging behaviour of your SDK by sending the value of the `logLevel` property of the `configuration` object and pass it over to the `initialize` call as shown below:
Makes sense. Made the change and also noted - we will standardize our docs accordingly.

2021-11-24 11:19 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-cordova-sdk.mdx
> +Check the <strong>Configuring your options object</strong> section below for detailed information on the parameters you can send in the <code class="inline-code">options</code> object.
Updated across the doc.

2021-12-02 22:48 UTC, esadek approved these changes
LGTM

2021-12-03 19:44 UTC, esadek requested changes

2021-12-03 19:44 UTC, esadek commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
> + "ssl"     => true   // defaults to true
Indentation should be increased to 2 spaces.

2021-12-06 06:28 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-dotnet-sdk.mdx
> +  "userId",
This is fixed too.

2021-12-06 15:17 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-php-sdk.mdx
> + "ssl"     => true   // defaults to true
This is fixed!

2021-12-06 17:13 UTC, esadek approved these changes
LGTM

2021-12-07 05:41 UTC, esadek approved these changes
LGTM

2021-12-08 06:11 UTC, merged