Added Flutter SDK Documentation
rudderlabs/rudderstack-docs pull request #29
Opened 2021-02-12 18:53 UTC by desusai7

## Added Flutter SDK Documentation

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-02-16 08:36 UTC, arnab-p requested changes
Add an entry to `SUMMARY.md` as well

2021-02-16 08:36 UTC, arnab-p commented on rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> +    RudderClient.getInstance(WRITE_KEY,config: builder.build());
Format with 2-spaces and apply the same to other code snippets as well

2021-02-16 08:36 UTC, arnab-p commented on rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> +  </tbody>
Can we convert this to markdown table?

2021-02-16 16:14 UTC, desusai7 commented on rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> +  </tbody>
Yeah sure

2021-02-16 16:14 UTC, desusai7 commented on rudderstack-sdk-integration-guides/rudderstack-flutter-sdk.md
> +    RudderClient.getInstance(WRITE_KEY,config: builder.build());
Will do as said

2021-02-19 06:34 UTC, arnab-p approved these changes

2021-02-19 06:34 UTC, merged