Post Affiliate Pro documentation
rudderlabs/rudderstack-docs pull request #292
Opened 2021-12-06 12:04 UTC by ameypv-rudder

## Description of the change

> Added documentation and images for the Post Affiliate Pro integration.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-12-06 12:07 UTC, ameypv-rudder commented
@ItsSudip In the Connection Settings in the dashboard, the Do Not Delete Cookies setting is not present, so I've omitted them in the documentation. Please have a look once.

2021-12-06 13:57 UTC, ItsSudip commented on destinations/marketing/post-affiliate-pro.mdx
> +</div>
> @ItsSudip In the Connection Settings in the dashboard, the Do Not Delete Cookies setting is not present, so I've omitted them in the documentation. Please have a look once.
> 
> reference: https://www.notion.so/rudderstacks/PostAffiliatePro-78078482e3d74f5db8dbfbb97e9ad19a

Forget to remove that from the notion. Given support in the code for that.

2021-12-07 10:44 UTC, saikumarrs requested changes

2021-12-07 10:44 UTC, saikumarrs commented on destinations/marketing/post-affiliate-pro.mdx
> +- Finally, copy the `src` part as shown below:
Let's convert this into a numbered list

2021-12-07 10:44 UTC, saikumarrs commented on destinations/marketing/post-affiliate-pro.mdx
> +```
Please clean up all the Post Affiliate code from the doc. Instead, explain in words and add more images to provide clarity.

2021-12-07 10:55 UTC, ItsSudip commented on destinations/marketing/post-affiliate-pro.mdx
> +
Remove this mapping as it is showing the exact functions we are going to call and make the heading like "In case of sales tracking, RudderStack creates a Post Affiliate Pro `sale` object. For the properties in the event, RudderStack then calls the respective sale object function."

2021-12-07 11:53 UTC, ameypv-rudder commented on destinations/marketing/post-affiliate-pro.mdx
> +
This is done. Please check.

2021-12-07 11:53 UTC, ameypv-rudder commented on destinations/marketing/post-affiliate-pro.mdx
> +```
Incorporated this feedback. Please check and let me know if the changes look good.

2021-12-07 11:53 UTC, ameypv-rudder commented on destinations/marketing/post-affiliate-pro.mdx
> +- Finally, copy the `src` part as shown below:
Sounds good - done!

2021-12-07 13:25 UTC, saikumarrs approved these changes

2021-12-07 13:26 UTC, merged