Braze Currents documentation
rudderlabs/rudderstack-docs pull request #297
Opened 2021-12-13 07:36 UTC by ameypv-rudder

## Description of the change

> Documentation for the Braze Currents source. Will do a final grammar cleanup after this review, in case there is any change in the content.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-12-14 09:17 UTC, saikumarrs commented on stream-sources/braze-currents.mdx
> +</div>
This is already covered as part of the next section. Let's remove it?

2021-12-14 09:17 UTC, saikumarrs commented on stream-sources/braze-currents.mdx
> +| Webhook Sent | When a webhook message is sent. |
@arnab-p I believe we do not support the full list mentioned here. Can you please share the subset?
Accordingly, the next section needs to be cleaned.

2021-12-15 04:50 UTC, ameypv-rudder commented on stream-sources/braze-currents.mdx
> +</div>
Sure - this is done.

2022-02-04 05:56 UTC, saikumarrs commented on stream-sources/braze-currents.mdx
> +| Webhook Sent | When a webhook message is sent. |
@arnab-p I was referring to this comment in the code, https://github.com/rudderlabs/rudder-transformer/blob/5c85e75ea0293a49823f471f1c0513f763103a5d/v0/sources/braze/transform.js#L32

2022-02-04 08:12 UTC, ameypv-rudder commented on stream-sources/braze-currents.mdx
> +| Webhook Sent | When a webhook message is sent. |
Based on the outcome of the discussion, I can update the table accordingly.

2022-03-08 05:51 UTC, arnab-p commented on stream-sources/braze-currents.mdx
> +| Webhook Sent | When a webhook message is sent. |
We don't have any specific mapping for the event names. Thus, it's not a harm to list down all the events that Braze supports. The comment is somewhat misleading IMO.

2022-03-08 05:51 UTC, arnab-p approved these changes

2022-03-08 05:57 UTC, saikumarrs approved these changes

2022-03-09 10:15 UTC, ishachopra0401 requested changes

2022-03-09 10:15 UTC, ishachopra0401 commented on stream-sources/braze-currents.mdx
> +Braze Currents is available in select Braze packages and can be configured only with the Braze team's assistance. For support, you can contact the Braze Customer Success team <a href="https://www.bra
```suggestion
Braze Currents is available in select Braze packages and can be configured only with the Braze team's assistance. For support, you can contact the <a href="https://www.braze.com/docs/support_contact/">Braze Customer Success team</a>.
```

>Braze Currents is available in select Braze packages

could not quite understand this.. like some enterprise plan package? not clear what sort of packages contain Braze Currents

2022-03-09 11:01 UTC, ameypv-rudder commented on stream-sources/braze-currents.mdx
> +Braze Currents is available in select Braze packages and can be configured only with the Braze team's assistance. For support, you can contact the Braze Customer Success team <a href="https://www.bra
Refer to [this](https://www.braze.com/docs/user_guide/data_and_analytics/braze_currents/#:~:text=A%20Currents%20connector%20is%20already%20included%20in%20many%20of%20our%20pro%2D%20and%20enterprise%2Dlevel%20packages) link for more context.

2022-03-09 11:33 UTC, ishachopra0401 commented on stream-sources/braze-currents.mdx
> +Braze Currents is available in select Braze packages and can be configured only with the Braze team's assistance. For support, you can contact the Braze Customer Success team <a href="https://www.bra
got it. In that case, maybe we can mention 'Braze Currents is available in many pro and enterprise-level Braze packages and....'

2022-03-10 14:48 UTC, merged