Facebook Pixel Documentation Updates
rudderlabs/rudderstack-docs pull request #305
Opened 2021-12-21 10:44 UTC by ameypv-rudder

## Description of the change

> Updated the page section to specify that the page properties and the event ID are now automatically passed downstream.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-12-21 19:04 UTC, akashrpo commented on destinations/advertising/fb-pixel.mdx
> + Once you make the <code class="inline-code">page</code>, RudderStack automatically sends the page properties and the event ID to Facebook Pixel.
Line:152 We can actually pass properties to `page` now which is optional and by default it is empty `{}`. Also, can we re-write the statement
```
the `track` event is sent as `PageView` to `fbq('track,'PageView')
```
as follows
```
the SDK will send the data to Facebook Pixel with event type `pageView`.
```

2021-12-22 04:43 UTC, saikumarrs commented on destinations/advertising/fb-pixel.mdx
> + Once you make the <code class="inline-code">page</code>, RudderStack automatically sends the page properties and the event ID to Facebook Pixel.
@ameypv-rudder @akashrpo 
"Any parameter sent to `rudderanalytics.page()` is ignored by RudderStack." needs to be replaced with the content from the newly added "successBlock".

2021-12-22 10:42 UTC, ameypv-rudder commented on destinations/advertising/fb-pixel.mdx
> + Once you make the <code class="inline-code">page</code>, RudderStack automatically sends the page properties and the event ID to Facebook Pixel.
incorporated the changes. @akashrpo @saikumarrs

2021-12-22 10:48 UTC, saikumarrs requested changes

2021-12-22 10:48 UTC, saikumarrs commented on destinations/advertising/fb-pixel.mdx
> +</div>
This seems redundant as it is understood from our event spec and the example below. Moreover, we don't specify this in page calls for any destinations

2021-12-22 10:50 UTC, saikumarrs commented on destinations/advertising/fb-pixel.mdx
> +</div>
@akashrpo SDK adds default properties to the incoming properties object in the page call for the final rudder message object.

2021-12-22 10:55 UTC, ameypv-rudder commented on destinations/advertising/fb-pixel.mdx
> +</div>
removed the tip.

2021-12-22 10:56 UTC, saikumarrs approved these changes

2021-12-22 11:03 UTC, merged