RudderStack Airflow Provider Documentation
rudderlabs/rudderstack-docs pull request #310
Opened 2021-12-27 12:19 UTC by ameypv-rudder

## Description of the change

> Documentation for the RudderStack Airflow Provider functionality.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-12-28 07:03 UTC, vyeshwanth requested changes

2021-12-28 07:10 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +```
```suggestion
Once you have defined a DAG and configured an Airflow connection, You can run the DAG via the following commands:

make DAG visible to airflow by running following commands.
```bash
export AIRFLOW_HOME=</path/to/airflow_home>
mkdir $AIRFLOW_HOME/dags
cp rudderstack_dag.py $AIRFLOW_HOME/dags
```
```

2021-12-28 07:14 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +```
Please feel free to change the suggestion. 
The idea is airflow doesn't automatically load the dag. we should run the two commands to make sure dag is in `$AIRFLOW_HOME/dags`. And airflow will pick the DAG from there

2021-12-29 06:46 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +The following code snippet highlights an Airflow DAG with one task named `rs_trigger_symc` for the source ID `20dQV6yuUDUw31peWA8f7xxgHdN`:
spell error `rs_trigger_symc`

2021-12-29 06:46 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +    'retries': 1,
@vyeshwanth There is no concept for retries right for WH Action sync jobs.. right? If so we should highlight not to have any retries and next trigger for sync task should suffice.

2021-12-29 06:46 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +    'retry_delay': timedelta(minutes=5)
Same thing here. Please check how we can highlight in document as well as in example that WH Action syncs are better non-retryable by Airflow.

2021-12-29 06:46 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +### Creating an Airflow connection
+1

2021-12-29 06:46 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +You can trigger a DAG by clicking on the play button on the right as seen above, and selecting <strong>Trigger DAG</strong>.
@vyeshwanth Should we highlight that a running task in Airflow if paused would not pause running sync but will make sure it will not be triggered next time. Also something to consider in next version release for us.

2021-12-29 06:51 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +### Creating an Airflow connection
> we can move this section and put it before defining the dag section. Connection created will be used in operator, so makes sense to move it up, WDYT?

+1

2021-12-29 08:05 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +    'retries': 1,
makes sense. we can remove the retries from this sample code.

2021-12-29 08:05 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +    'retry_delay': timedelta(minutes=5)
```suggestion
```

2021-12-29 08:07 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +You can trigger a DAG by clicking on the play button on the right as seen above, and selecting <strong>Trigger DAG</strong>.
we can add a note that stopping the DAG won't cancel the ongoing sync.

2021-12-29 12:30 UTC, RanjeetMishra commented on warehouse-actions/airflow-provider.mdx
> +    'retries': 1,
@vyeshwanth Also which document will highlight how to call sync for full sync vs incremental?

2021-12-31 07:25 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +    'retries': 1,
@vyeshwanth any update here?

2021-12-31 07:59 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +
Sounds good - removed!

2021-12-31 07:59 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +To use the RudderStack Airflow Provider, you must have Apache Airflow installed locally. For more information, refer to the <a href="https://airflow.apache.org/docs/apache-airflow/stable/start/local.
Sure - tweaked the sentence slightly and updated the URL.

2021-12-31 07:59 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +Initialize all the dependencies by running Apache Airflow via the following command:
Mentioned this as a warning note.

2021-12-31 08:00 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +The following code snippet highlights an Airflow DAG with one task named `rs_trigger_symc` for the source ID `20dQV6yuUDUw31peWA8f7xxgHdN`:
Fixed the typo.

2021-12-31 08:00 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +### Creating an Airflow connection
Made this change.

2021-12-31 08:00 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +   - **Connection ID**: Specify a unique connection name. If you don't specify a **Connection ID**, the RudderStack operator will pick the connection with the name `rudderstack_default`.
This is fixed!

2021-12-31 08:00 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +```
Tweaked the sentence the communicate this idea.

2021-12-31 08:01 UTC, ameypv-rudder commented on warehouse-actions/airflow-provider.mdx
> +You can trigger a DAG by clicking on the play button on the right as seen above, and selecting <strong>Trigger DAG</strong>.
Added the note.

2021-12-31 08:33 UTC, vyeshwanth commented on warehouse-actions/airflow-provider.mdx
> +    'retries': 1,
For now, full sync option is not available in the operator. will add a task for this in backlog

2021-12-31 08:39 UTC, vyeshwanth approved these changes
LGTM

2022-01-03 05:08 UTC, RanjeetMishra approved these changes
LGTM!

2022-01-03 06:19 UTC, merged