Shopify Source Documentation
rudderlabs/rudderstack-docs pull request #325
Opened 2022-01-05 08:45 UTC by ameypv-rudder

## Description of the change

> Added documentation for the Shopify source.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-05 09:04 UTC, arajguha commented on stream-sources/shopify.mdx
> +The following Shopify events are mapped to RudderStack's generic `track` events:
Can we mention it explicilty that the events in this list are allowed as generic track events. Any other event flowing through would be dropped.

2022-01-05 09:41 UTC, ameypv-rudder commented on stream-sources/shopify.mdx
> +The following Shopify events are mapped to RudderStack's generic `track` events:
Sure - will add this note.

2022-01-06 07:28 UTC, yashasvibajpai commented
We have some more updates in regards to the doc. We don't need to share the Shopify partners process un the documentation. Shared the relevant one already.

2022-02-01 10:52 UTC, ameypv-rudder commented
@yashasvibajpai @arajguha @saikumarrs the device mode updates are incorporated in this PR.

2022-02-09 12:11 UTC, arajguha approved these changes

2022-02-09 12:11 UTC, arajguha commented
lgtm

2022-02-11 09:45 UTC, ishachopra0401 requested changes

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +# slug: "/docs/stream-sources/appcenter"
```suggestion
# slug: "/docs/stream-sources/shopify"
```

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +- Go to your [**RudderStack dashboard**](https://app.rudderstack.com/) and click on **Add Source**. From the list of **Event Stream** sources, select **Shopify**, as shown:
numbered list may be helpful

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +- Go to the [**admin dashboard**](https://accounts.shopify.com/store-login) of your Shopify store.
numbered list may be helpful

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +To complete the configuration, you will need to add the webhook URL copied above in the RudderStack app installed in your Shopify store. Follow these steps to do so:
Not quite sure where we copied the webhook URL

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +- Then, search for RudderStack, as shown:
```suggestion
- Search for RudderStack, as shown:
```
then is repeating in above and below steps.

2022-02-11 09:45 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +- After installation, you should see the app in the **Installed apps** section, as shown:
```suggestion
- After installation, you should be able to see the app in the **Installed apps** section, as shown:
```

2022-02-11 10:14 UTC, ameypv-rudder commented on stream-sources/shopify.mdx
> +# slug: "/docs/stream-sources/appcenter"
this won't be rendered anyway :)

2022-02-23 13:39 UTC, closed without merging