Data Regulation API documentation
rudderlabs/rudderstack-docs pull request #339
Opened 2022-01-11 13:25 UTC by ameypv-rudder

## Description of the change

> Removed the outdated API documentation and replaced it with the API docs for the Data Regulation service.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-12 17:24 UTC, lvrach commented on rudderstack-api/data-regulation-api.mdx
> +RudderStack's Data Regulation API allows you to delete the collected data, suspend data collection, or do both - for a particular user identified by a `userId`.
Actually we support:
* suspend data collection
* suspend data collection and delete data

You can not delete data while  data collection is not suspended

2022-01-12 17:41 UTC, lvrach commented on rudderstack-api/data-regulation-api.mdx
> +    "sourceIds": [
tip: they can use `https://api.rudderstack.com/v2/sources` to get source ids

2022-01-13 09:04 UTC, saurav-malani commented on rudderstack-api/data-regulation-api.mdx
> +This guide covers the data regulation feature in detail as well as details the various endpoints of the Data Regulation API.
This line isn't very clear. Can you please re-phrase it?

2022-01-13 09:24 UTC, saurav-malani requested changes

2022-01-13 10:46 UTC, ameypv-rudder commented on rudderstack-api/data-regulation-api.mdx
> +    "sourceIds": [
mentioned this as a tip.

2022-01-13 10:47 UTC, ameypv-rudder commented on rudderstack-api/data-regulation-api.mdx
> +Avoid specifying both <code class="inline-code">sourceIds</code> and <code class="inline-code">destinationIds</code>.
thanks, removed this block to avoid any confusion.

2022-01-24 05:33 UTC, saurav-malani approved these changes

2022-01-24 06:14 UTC, chandumlg approved these changes

2022-01-24 10:09 UTC, merged