Added Candu doc and image
rudderlabs/rudderstack-docs pull request #359
Opened 2022-01-25 10:57 UTC by ishachopra0401

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-27 06:07 UTC, utsabc requested changes
Some minor changes requested

2022-01-27 06:07 UTC, utsabc commented on destinations/testing-and-personalization/candu.mdx
> +While working with Candu platform, the `identify` call should always be made before the `track` call. The reason being if a `track` call is made first for an anonymous user, then a user is created wi
Can we rephrase this a bit?
"While working with Candu platform it is recommended to make an `identify` call before making a `track` call to ensure no duplicate identities are created in Candu platform"

2022-01-27 06:07 UTC, utsabc commented on destinations/testing-and-personalization/candu.mdx
> +The identify call lets you capture the actions of a visiting user. It also lets you record any traits associated with them such as their name, email address, etc.
Just a minor change
"The identify call lets you capture the details of a visiting user. It lets you record any traits associated with them such as their name, email address, etc."

2022-01-27 07:17 UTC, ishachopra0401 commented
@utsabc Suggested changes have been implemented. Please have a look.

2022-01-27 07:21 UTC, saikumarrs commented on destinations/testing-and-personalization/candu.mdx
> +| **Cloud mode**      | **Supported** | **Supported** | **Supported** |
@utsabc @ItsSudip we should check if it makes sense for these platforms to be a source of LaunchDarkly event data.

2022-01-27 08:24 UTC, utsabc approved these changes

2022-01-27 08:25 UTC, utsabc commented on destinations/testing-and-personalization/candu.mdx
> +| **Cloud mode**      | **Supported** | **Supported** | **Supported** |
Yep they have SDK for we and mobile we can support them in future releases

2022-01-27 14:29 UTC, ItsSudip commented on destinations/testing-and-personalization/candu.mdx
> +| **Cloud mode**      | **Supported** | **Supported** | **Supported** |
I don't see any mobile sdk for candu, we should update the documentation with web support only.

2022-01-27 14:30 UTC, saikumarrs commented on destinations/testing-and-personalization/candu.mdx
> +| **Cloud mode**      | **Supported** | **Supported** | **Supported** |
No. The discussion is here only about the "cloud mode" row.

2022-01-31 05:43 UTC, saikumarrs approved these changes

2022-01-31 11:28 UTC, ameypv-rudder approved these changes
Looks good to me, thanks!

2022-01-31 11:35 UTC, merged