AppsFlyer Documentation Update
rudderlabs/rudderstack-docs pull request #360
Opened 2022-01-25 12:36 UTC by ameypv-rudder

## Description of the change

> Added clarity on using the AppsFlyer ID for sending events via the cloud mode. Also, revamped and standardized the documentation.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-25 12:55 UTC, desusai7 approved these changes
LGTM

2022-02-02 07:15 UTC, ishachopra0401 requested changes

2022-02-02 08:11 UTC, ishachopra0401 commented on destinations/attribution/appsflyer.mdx
> +- If your AppsFlyer SDK is loaded through RudderStack (device mode integration), then you can obtain the AppsFlyer ID by including the code snippet depending on your platform of integration:
```suggestion
- If your AppsFlyer SDK is loaded through RudderStack (device mode integration), then you can obtain the AppsFlyer ID by including the code snippet in your app, depending on your platform of integration:
```

2022-02-03 12:21 UTC, ishachopra0401 approved these changes

2022-02-03 12:28 UTC, merged