TikTok Ads integration doc
rudderlabs/rudderstack-docs pull request #364
Opened 2022-01-27 12:32 UTC by ishachopra0401

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-01-31 10:43 UTC, saikumarrs commented on destinations/advertising/tiktok-ads.mdx
> +| **Cloud mode**      | **Supported** | -             | -             |
@akashrpo Why are "Mobile" and "Server" left out here?

2022-01-31 11:01 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +| **Cloud mode**      | **Supported** | -             | -             |
@ishachopra0401 Cloud mode: `Mobile` and `Server` will be supported fields here.

2022-01-31 11:21 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +      id: "f0e388f53921a51f0bb0fc8a2944109ec188b59172935d8f23020b1614cc44bc"
Let's update this field to
```suggestion
      id: "1234"
```
as by default, we will hash this property

2022-01-31 11:21 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +
Let's add the FAQ section below.

2022-01-31 11:25 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +
We need to add the mapping table below for events that we are mapping.

2022-01-31 11:46 UTC, utsabc commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
@akashrpo @ishachopra0401 is not able to make many contexts out of this paragraph, as the prior example is given using JS SDK, and in case batching JS SDK doesn't support batching. Probably we can use any server-side SDK example for this doc, and give example for batching as well?
cc @saikumarrs  
WDYT?

2022-01-31 11:48 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +<a href="https://www.tiktok.com/business/ru/apps/tiktok?tt4b_lang_redirect=1">TikTok Ads</a> is TikTok's online advertising platform. It allows marketers to run their product ads to target custom aud
```suggestion
<a href="https://www.tiktok.com/business/en/apps/tiktok?tt4b_lang_redirect=1">TikTok Ads</a> is TikTok's online advertising platform. It allows marketers to run their product ads to target custom audiences, optimize their campaigns, attribution, etc.
```
The provided URL is in the Russian language

2022-01-31 12:20 UTC, saikumarrs commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
I don't think this is applicable here. Looking for more context and the need.

2022-01-31 12:20 UTC, saikumarrs commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
SDK batching functionality is usually discussed in the respective SDK's documentation.

2022-01-31 12:34 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
IMHO along with the provided JS-SDK example, we can also provide another example for batching that will give more context to the user. Perhaps we can also modify this sentence to say:


Rudderstack will automatically group all the events which are received in a batch of 50 per request and send using the `batch` endpoint. However, if the payload contains `test_event_code` property, batching won't be applied. For more information on the `batch` call, please refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/http-api/#11-batch">RudderStack API Specification</a> documentation. 
cc @ishachopra0401

2022-02-01 06:20 UTC, utsabc commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
@ishachopra0401 let's add link to our batch API spect to add some more context https://www.rudderstack.com/docs/rudderstack-api/http-api/#11-batch

2022-02-01 06:29 UTC, ishachopra0401 commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
done, already!

2022-02-01 06:30 UTC, ameypv-rudder commented on destinations/advertising/tiktok-ads.mdx
> +
@akashrpo since the FAQ (re the 40002 error) is not specifically related to the RudderStack integration with TikTok, do we need to add it?

2022-02-01 07:11 UTC, saikumarrs requested changes

2022-02-01 07:11 UTC, saikumarrs commented on destinations/advertising/tiktok-ads.mdx
> +The events are automatically grouped in a batch of 50 events per request using the <code class="inline-code">batch</code> call. However, if the payload contains <code class="inline-code">test_event_c
@ameypv-rudder @ishachopra0401 this paragraph is not needed in destination documentation as it is irrelevant here.
@akashrpo to provide clarification on this.

2022-02-01 08:15 UTC, akashrpo commented on destinations/advertising/tiktok-ads.mdx
> +
As discussed I think the user's first approach will be to look for the solution to the error at our end. In which case we can add this piece of information in our docs.
cc @utsabc

2022-02-01 10:11 UTC, ishachopra0401 commented
@akashrpo @utsabc The suggested changes have been implemented. Please review.

2022-02-01 10:31 UTC, saikumarrs approved these changes

2022-02-01 10:54 UTC, utsabc approved these changes

2022-02-01 12:34 UTC, ameypv-rudder commented on destinations/advertising/tiktok-ads.mdx
> +[TikTok Ads](https://www.tiktok.com/business/en/apps/tiktok?tt4b_lang_redirect=1") is TikTok's online advertising platform. It allows marketers to run their product ads to target custom audiences, op
```suggestion
[TikTok Ads](https://www.tiktok.com/business/en/apps/tiktok?tt4b_lang_redirect=1") is TikTok's online advertising platform. It lets marketers run their product ads to target custom audiences and optimize their campaigns.
```

2022-02-01 12:44 UTC, ameypv-rudder commented on destinations/advertising/tiktok-ads.mdx
> +- **Access Token**: You need to generate the Access Token (also known as long-term access token) by following the steps mentioned in <a href="https://ads.tiktok.com/marketing_api/docs?id=170189091238
```suggestion
- **Access Token**: You need to generate the Access Token (also known as Long Term Access Token) by following the steps mentioned in <a href="https://ads.tiktok.com/marketing_api/docs?id=1701890912382977">Authorization</a> and <a href="https://ads.tiktok.com/marketing_api/docs?id=1701890914536450">Authentication</a> topics in TikTok documentation.
```

2022-02-01 12:45 UTC, ameypv-rudder commented on destinations/advertising/tiktok-ads.mdx
> +- **Access Token**: You need to generate the Access Token (also known as long-term access token) by following the steps mentioned in <a href="https://ads.tiktok.com/marketing_api/docs?id=170189091238
In the web app, we reference the access token as Long Term Access Token, and so do Segment. We can be consistent here.

2022-02-01 12:46 UTC, ameypv-rudder commented on destinations/advertising/tiktok-ads.mdx
> +- **Hash Contextual User Properties (SHA-256)**: If this setting is enabled, RudderStack will hash the contextual user properties like external_id, email, phone_number from raw format to sha256.
```suggestion
- **Hash Contextual User Properties (SHA-256)**: If this setting is enabled, RudderStack will hash the contextual user properties like `external_id`, `email`, `phone_number` from the raw format to the SHA-256 format.
```

2022-02-01 12:57 UTC, ishachopra0401 commented on destinations/advertising/tiktok-ads.mdx
> +- **Access Token**: You need to generate the Access Token (also known as long-term access token) by following the steps mentioned in <a href="https://ads.tiktok.com/marketing_api/docs?id=170189091238
Going by the official tiktok ads doc here.

2022-02-01 12:57 UTC, ameypv-rudder approved these changes

2022-02-01 12:58 UTC, merged