Customer.io Source Updates
rudderlabs/rudderstack-docs pull request #378
Opened 2022-02-02 11:08 UTC by ameypv-rudder

## Description of the change

> Added supported event information for Email (updated), Customer, Webhook, Slack, SMS, and Push events.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-02 16:52 UTC, akashrpo approved these changes
LGTM

2022-02-04 06:39 UTC, ishachopra0401 commented on stream-sources/customerio.mdx
>  Make sure you add the source write key as query parameter to the URL. This is required to prevent the webhook from failing because of an invalid write key.
For more information on the data plane URL, refer to <a href="https://rudderstack.com/docs/get-started/installing-and-setting-up-rudderstack/#what-is-a-data-plane-url-where-do-i-get-it">this</a> section.
</div>
<div class="warningBlock">

To eliminate URL on 'this':

Refer to the <a href="https://rudderstack.com/docs/get-started/installing-and-setting-up-rudderstack/#what-is-a-data-plane-url-where-do-i-get-it">data plane URL</a> section for more information.

2022-02-04 06:44 UTC, ishachopra0401 commented on stream-sources/customerio.mdx
> +- Email
Just a thought if we can skip this listing from here as this is also visible on the mini TOC which appears on the right of a docs page.

2022-02-04 06:44 UTC, ishachopra0401 commented on stream-sources/customerio.mdx
> +| `Clicked`           | A tracked link in an email was clicked by the recipient / customer.                        |
```suggestion
| `Clicked`           | A tracked link in an email was clicked by the recipient/customer.                        |
```

2022-02-04 08:07 UTC, ameypv-rudder commented on stream-sources/customerio.mdx
>  Make sure you add the source write key as query parameter to the URL. This is required to prevent the webhook from failing because of an invalid write key.
Done.

2022-02-04 08:12 UTC, ishachopra0401 approved these changes

2022-02-04 08:14 UTC, ameypv-rudder commented
@saikumarrs @utsabc please confirm if we are good to go here.

2022-02-07 11:59 UTC, saikumarrs requested changes

2022-02-07 11:59 UTC, saikumarrs commented on stream-sources/customerio.mdx
> +## Supported events
For each of these sections, let's add the supported data mapping.
The common mapping can be put at the top level if any.
CC @akashrpo @ameypv-rudder

2022-02-07 13:26 UTC, utsabc approved these changes

2022-02-10 15:04 UTC, ameypv-rudder commented on stream-sources/customerio.mdx
> +## Supported events
@saikumarrs this is done. There were a lot of mappings to include, so please have a look once.

2022-02-10 17:36 UTC, akashrpo commented on stream-sources/customerio.mdx
> +| `data.delivery.id`      | `properties.deliveryId`     |
same goes for all examples below

2022-02-11 04:41 UTC, ameypv-rudder commented on stream-sources/customerio.mdx
> +| `data.identifiers.id`  | `userId`                  |
We are doing this already at the start of the section. I thought of including all the properties so that the user finds all the supported properties associated with the event type in a single table, rather than having to scroll up every time to see the common mappings. Thoughts, @saikumarrs?

2022-02-11 04:41 UTC, ameypv-rudder commented on stream-sources/customerio.mdx
> +| `data.delivery.id`      | `properties.deliveryId`     |
Sure - thanks for highlighting - this is fixed.

2022-02-11 05:04 UTC, saikumarrs commented on stream-sources/customerio.mdx
> +| `data.identifiers.id`  | `userId`                  |
I think it would be redundant to include them again in the individual sections. We can make it clear in the common section that they are applicable for all the downstream sections. Furthermore, if needed, we can add a note above the individual tables to mention that these are specific mappings in addition to the common ones.

2022-02-11 05:16 UTC, ameypv-rudder commented on stream-sources/customerio.mdx
> +| `data.identifiers.id`  | `userId`                  |
sounds good - i have made this change.

2022-02-11 05:38 UTC, saikumarrs approved these changes

2022-02-11 08:00 UTC, merged