Google AdWords documentation update
rudderlabs/rudderstack-docs pull request #390
Opened 2022-02-09 07:33 UTC by ameypv-rudder

## Description of the change

> Updated AdWords documentation with updated information on adding custom reports as a resource.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-09 09:55 UTC, mcchran approved these changes
LGTM.

2022-02-09 11:42 UTC, ishachopra0401 requested changes

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +## FAQs
```suggestion
## FAQ
```

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +- **Start date**: This option specifies the earliest date when RudderStack will import all your historical AdWords data.
```suggestion
- **Start date**: This option specifies the earliest date by when RudderStack can import all your historical AdWords data.
```

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +- **Table prefix**: RudderStack will create a table in your data warehouse with this prefix name and load all your AdWords data into it.
```suggestion
- **Table prefix**: Creates a table in your data warehouse with the specified prefix name and loads all your AdWords data into it.
```

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +That's it! Google AdWords is now successfully configured as a source. RudderStack will start importing the Google AdWords data as per the specified frequency.
```suggestion
Google AdWords is now successfully configured as a source. RudderStack will start importing the Google AdWords data as per the specified frequency. 
```

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +You can further connect this source to your data warehouse by clicking on **Connect Destinations** or **Add Destinations**, as shown:
```suggestion
You can further connect this source to your data warehouse by clicking on **Add Destination**, as shown:
```

2022-02-09 11:42 UTC, ishachopra0401 commented on cloud-extract-sources/google-adwords.mdx
> +  Use the <strong>Connect Destinations</strong> option if you have already configured a data warehouse destination in RudderStack/ To configure a warehouse destination from scratch, click on the <str
Can't locate 'Connect Destinations' option.

2022-02-10 05:44 UTC, ameypv-rudder commented on cloud-extract-sources/google-adwords.mdx
> +  Use the <strong>Connect Destinations</strong> option if you have already configured a data warehouse destination in RudderStack/ To configure a warehouse destination from scratch, click on the <str
fixed this.

2022-02-10 06:06 UTC, ishachopra0401 approved these changes

2022-02-10 06:46 UTC, merged