Segment anonymousId backfilling section updates
rudderlabs/rudderstack-docs pull request #392
Opened 2022-02-09 12:39 UTC by ameypv-rudder

## Description of the change

> Updated the Segment to RudderStack migration docs. Context: [here](https://rudderlabs.slack.com/archives/C02B0AA8QFJ/p1639512581224900).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-10 02:33 UTC, esadek requested changes

2022-02-10 02:33 UTC, esadek commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +description: Step-by-step guide to migrate from Segment to RudderStack.
I don't think "to" is correct here. "Step-by-step guide on migrating from Segment to RudderStack." would be better.

2022-02-10 02:33 UTC, esadek commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +Start with creating an account in [RudderStack](https://app.rudderstack.com/signup?type=freetrial). You will then see the following dashboard containing your data plane URL required to [set up your d
This is not correct. Data plane URL is not required to set up your data plane. The data plane is already set up.

2022-02-10 02:33 UTC, esadek commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +## Setting up the RudderStack data plane
As I said in my previous comment, the data plane is already set up if they are using a free tier account. Setting up the data plane only makes sense for open source users.

2022-02-10 02:33 UTC, esadek commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +  You can use the rest of your code as is, as RudderStack SDK API is fully compatible
Sounds a little weird saying "as is, as."
Should be "**the** RudderStack SDK API."

2022-02-10 02:33 UTC, esadek commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +When migrating from Segment or a similar analytics tool, you might already have some anonymous traffic that has not yet been identified. When Segment or RudderStack track events for non-identified us
"When Segment **and** RudderStack track events" might be better.

2022-02-10 08:03 UTC, ameypv-rudder commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +Start with creating an account in [RudderStack](https://app.rudderstack.com/signup?type=freetrial). You will then see the following dashboard containing your data plane URL required to [set up your d
Makes sense. Removed this section.

2022-02-10 08:04 UTC, ameypv-rudder commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +description: Step-by-step guide to migrate from Segment to RudderStack.
Agree - changed this to your suggestion.

2022-02-10 08:04 UTC, ameypv-rudder commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +## Setting up the RudderStack data plane
Agreed. Removed it from the doc entirely.

2022-02-10 08:04 UTC, ameypv-rudder commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +  You can use the rest of your code as is, as RudderStack SDK API is fully compatible
You're right - rephrased it accordingly.

2022-02-11 10:37 UTC, ishachopra0401 requested changes

2022-02-11 10:37 UTC, ishachopra0401 commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
> +Start with creating an account in [RudderStack](https://app.rudderstack.com/signup?type=freetrial). You will then see the following dashboard containing your data plane URL:
```suggestion
After creating a [RudderStack](https://app.rudderstack.com/signup?type=freetrial) account, you will see the following dashboard containing your data plane URL:
```

2022-02-11 10:37 UTC, ishachopra0401 commented on user-guides/migration-guides/rudderstack-migration-guide.mdx
>  This document explains the step-by-step process of migrating from [Segment](https://segment.com/) to RudderStack. Our primary goal is to lay out the necessary actions for replacing your instrumentati
```suggestion
This document explains the step-by-step process of migrating from [Segment](https://segment.com/) to RudderStack. The primary goal is to lay out the necessary actions for replacing your instrumentation code and start generating events from RudderStack SDK with minimal changes.

```

2022-02-11 13:10 UTC, merged