Added Docs for Transformation API
rudderlabs/rudderstack-docs pull request #40
Opened 2021-03-05 05:06 UTC by Shivam4415

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-03-05 07:06 UTC, sivashanmukh commented on rudderstack-transformation-api/transormer-api.md
> +| `isPublished`  | Boolean  | Optional     | By default this flag is false. If set to true then that is latest transformer through which all events gets processed before reaching to destinations. |
Also let us have this as a query param instead of in the body itself, right?

2021-03-05 07:06 UTC, sivashanmukh commented on rudderstack-transformation-api/transormer-api.md
> +| `isPublished` | Boolean  | Optional     | By default this flag is false. If set to true then that is latest libraries all published transformer will use if it is present in that transformer.
Similar comments as that of transformations' isPublished

2021-03-05 07:06 UTC, sivashanmukh commented on rudderstack-transformation-api/transormer-api.md
> +## 7 AccessToken
Lets move these to the top of this doc where we describe how to get AccessToken. In that section, lets ask users to first try to get an accessToken and then suggest to create one if they don't already have one.

2021-03-05 07:06 UTC, sivashanmukh commented on rudderstack-transformation-api/transormer-api.md
> +| **401 – Unauthorized**          | **No valid API key provided or user doesn’t have access to the resource.** |
.

2021-03-05 07:27 UTC, Shivam4415 commented on rudderstack-transformation-api/transormer-api.md
> +Authorization: Basic Base64Enc(1Xk5DChfJAol3xtW7qNnK1apo5p).
Fixed

2021-03-05 07:30 UTC, Shivam4415 commented on rudderstack-transformation-api/transormer-api.md
> +| **401 – Unauthorized**          | **No valid API key provided or user doesn’t have access to the resource.** |
fixed

2021-03-05 07:30 UTC, Shivam4415 commented on rudderstack-transformation-api/transormer-api.md
> +Authorization: Basic {Base64Encoded(AccessToken)}
Yes, Fixed

2021-03-05 10:23 UTC, SumanthPuram requested changes

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +To consume Transformations API you need Access to it. If you don't have an access to it, you can [contact us](mailto:%20docs@rudderstack.com) or you can also start a conversation on our [Slack](https
Why do they need to contact us? Isn't it default for every customer?

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +You can either use Postman, Fiddler or any other API client to make your request.
Mention curl and httpie also examples.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +- Copy your workspace token and within Authorization section select type as Basic Auth and paste it into password field.
Let's use workspaceToken as the user and empty string as password? We do the same for workspaceConfig.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +- Copy your workspace token and within Authorization section select type as Basic Auth and paste it into password field.
Also don't mention about selecting Authorization section etc. This becomes specific to Postman. 
Either give a postman example and mention this or use generic terms like `Use HTTP Basic auth and pass workspace token as the user name and empty string as password`

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +Authorization: Basic Base64Encoded(:1Xk5DChfJAol3xtW7qNnK1apo5p).
Let's give an example with curl or httpie, it would be easy for developers to try out.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +You will authenticate your account when using the API by including your secret AccessToken in the password fields in Authorization, if using POSTMAN. The API is authenticated via HTTP Basic Auth.
Again use this as user name and not password.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +We also provide CRUD operations on your AccessToken. You can also update and delete your accesstoken.
`We also provide CRUD operations on your AccessToken`
Don't need to mention about CRUD again. Just mention that you revoke your previous access token or create new ones. I don't think we need support for updating the existing access tokens? If the access is not enough, they can create a new one in the future with the required access.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +We strongly recommend to generate your accesstoken before you make any API calls.
Why strongly recommend? Isn't this mandatory?

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +Request URL: https://api.rudderstack.com/accessToken
Where is the accessToken to delete in the request?

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +Rudderstack uses conventional HTTP response codes to indicate the success or failure of an API request. In general, codes in 2xx range indicate success, codes in 4xx range indicate an error that fail
standard instead of conventional.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +Rudderstack uses conventional HTTP response codes to indicate the success or failure of an API request. In general, codes in 2xx range indicate success, codes in 4xx range indicate an error that fail
I don't think we need to mention about what is 5xx, what is 4xx etc in the above para.

2021-03-05 10:23 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +Creates a transformer and send its object as response.
Let's use transformation instead of transformer?

2021-03-05 11:06 UTC, sivashanmukh commented on rudderstack-transformation-api/transormer-api.md
> +You will authenticate your account when using the API by including your secret AccessToken in the password fields in Authorization, if using POSTMAN. The API is authenticated via HTTP Basic Auth.
General standard for sending access token is as username:accesstoken. That's what github does too. Let's leave it this way. We can change the workspace token part to keep it in sync with our other apis

2021-03-08 06:07 UTC, SumanthPuram commented on rudderstack-transformation-api/transormer-api.md
> +You will authenticate your account when using the API by including your secret AccessToken in the password fields in Authorization, if using POSTMAN. The API is authenticated via HTTP Basic Auth.
Ok

2021-03-25 05:45 UTC, closed without merging