Google Ads Remarketing List documentation
rudderlabs/rudderstack-docs pull request #409
Opened 2022-02-17 10:53 UTC by ameypv-rudder

## Description of the change

> Added documentation for the Google Adwords Remarketing List destination.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-17 10:55 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +| `thirdPartyUserId` | `thirdPartyUserID` | - |
@ItsSudip do we need to add any specific info / things to keep in mind for `thirdPartyUserId`?

2022-02-23 16:43 UTC, ItsSudip commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +| `thirdPartyUserId` | `thirdPartyUserID` | - |
No there are not any suggestions from google about it. And I checked they are expecting everything except number. They are expecting strings only.

2022-02-24 09:05 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +
sure Sudip.

2022-02-24 09:16 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +| `thirdPartyUserId` | `thirdPartyUserID` | - |
Added this information.

2022-02-25 05:39 UTC, ameypv-rudder commented
@utsabc @ItsSudip i think all the updates are now incorporated. Can you have a look and let me know if we're good to proceed?

2022-02-25 05:42 UTC, ItsSudip approved these changes

2022-02-25 06:04 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +<img src="../../assets/event-stream-destinations/google-adwords-remarketing-lists-connection-settings-1.png" alt="Google Adwords Remarketing Lists (Customer Match) connection settings" />
We don't need the option of developer token

2022-02-25 06:04 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +```json
Can we give some sdk example like fb custom audience

2022-02-25 06:04 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +```json
Python sdk maybe

2022-02-25 06:04 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +1. Open your Google Ads account.
Some pictorial representation would be helpful? Or is overkill ..thinking out loud

2022-02-25 06:09 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +```json
Nps this not needed

2022-02-25 06:12 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +1. Open your Google Ads account.
we want to avoid unnecessary screenshots and the process is quite straightforward. I don't think we need a screenshot here.

2022-02-25 06:13 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +<img src="../../assets/event-stream-destinations/google-adwords-remarketing-lists-connection-settings-1.png" alt="Google Adwords Remarketing Lists (Customer Match) connection settings" />
yep - will update the screenshot here.

2022-02-25 06:14 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +```json
@ItsSudip can you share a sample snippet, please?

2022-02-25 06:26 UTC, utsabc commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +1. Open your Google Ads account.
Got it make sense

2022-02-25 06:27 UTC, utsabc approved these changes

2022-02-25 08:50 UTC, saikumarrs approved these changes

2022-02-25 08:54 UTC, ishachopra0401 requested changes

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +Google Adwords Remarketing Lists lets you send a list of users (audience list) to Google Adwords and run targeted advertising campaigns without having to update the user list manually.
Is there any link we can add for 'Google Adwords Remarketing Lists'?
Google Adwords Remarketing Lists is a _marketing tool/platform (whatever it is)_ which lets you send a.....
will read better IMO
WDYT?

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +1. Give RudderStack access to your Google Ads account by clicking on **Connect with Google Ads Remarketing Lists (Customer Match)** under **Create new account**.
```suggestion
1. Give access to RudderStack from your Google Ads account by clicking on **Connect with Google Ads Remarketing Lists (Customer Match)** under **Create new account**.
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **List ID**: To get your Google Ads list ID, go to your Google Ads account and navigate to **Tools & settings** > **Audience Manager**.
```suggestion
- **ListId**: To get your Google Ads list ID, go to your Google Ads account and navigate to **Tools & settings** > **Audience Manager**.
```
Shouldn't these terms be the same as in the connection settings screenshot? Thinking from the consistency POV too.. for future docs.. we can reach a consensus

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **Subaccount**: Enable or disable this setting if you are using a Google Ads subaccount.
```suggestion
- **Subaccount**: Enable or disable this setting depending on whether you are using a Google Ads subaccount or not.
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **Type of List**: Select the type of list that you want to create.
```suggestion
- **Type of List**: Select the type of list you want to create.
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +<li><strong>General</strong>: You can send email, phone number, and address information in this list. RudderStack will hash this data and send it to Google Adwords Remarketing Lists depending on the
```suggestion
<li><strong>General</strong>: You can send email, phone number, and address information in this list. RudderStack will hash this data and send it to Google Adwords Remarketing Lists depending on the <strong>Hash Required</strong> setting (enabled by default).</li>
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **Hash Required**: If enabled, RudderStack will hash the `email`, `phone`, `firstName`, and `lastName` fields in the SHA-256 format.
```suggestion
- **Hash Required**: This setting is enabled by default and hashes the `email`, `phone`, `firstName`, and `lastName` fields in the SHA-256 format.
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **Schema Fields**: If you have select **General** as the list type, you will need to choose your schema fields (at least one) from the available options. The options are `hashedEmail`, `hashedPhone
```suggestion
- **Schema Fields**: If you have selected **General** as the list type, you will need to choose your schema fields (at least one) from the available options. The options are `hashedEmail`, `hashedPhoneNumber`, and `addressInfo`.
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "email": "alex@company.com",
```suggestion
                    "email": "alex@example.com",
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "phone": "9876543210"
```suggestion
                    "phone": "8005550100"
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "phone": "9786543210"
```suggestion
                    "phone": "8005550100"
```

2022-02-25 08:54 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "email": "emily@company.com",
```suggestion
                    "email": "emily@example.com",
```

2022-02-25 09:00 UTC, saikumarrs commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "phone": "9786543210"
@ishachopra0401 can we use some other values (maybe 1234567890)? Even this seems like a valid phone number.

2022-02-25 09:24 UTC, ishachopra0401 commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +                    "phone": "9786543210"
I checked this series from 555-0100 to 555-0199 is reserved for fictional use
[Reference](https://en.wikipedia.org/wiki/555_(telephone_number)#:~:text=Only%20555%2D0100%20through%20555,restricted%20only%20in%20North%20America.)
but yeah on second thought, it's for North America. We can use what you suggested. Thanks!

2022-02-25 11:33 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +Google Adwords Remarketing Lists lets you send a list of users (audience list) to Google Adwords and run targeted advertising campaigns without having to update the user list manually.
IMO simply adding the URL should suffice, it's not a separate tool/platform.

2022-02-25 11:35 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +1. Give RudderStack access to your Google Ads account by clicking on **Connect with Google Ads Remarketing Lists (Customer Match)** under **Create new account**.
Let's retain the original sentence as the user gets the required AdWords permissions from the RudderStack dashboard itself (by clicking on the option). The changes suggest the user needs to first go to their Google Ads account and then give the permissions.

2022-02-25 11:36 UTC, ameypv-rudder commented on destinations/advertising/google-adwords-remarketing-list.mdx
> +- **Subaccount**: Enable or disable this setting if you are using a Google Ads subaccount.
A simpler alternative would be to just mention "Enable this setting if you are using a Google Ads subaccount."

2022-02-25 11:48 UTC, ishachopra0401 approved these changes

2022-02-25 11:58 UTC, merged