Supported cloud mode and device mode events for Shopify source
rudderlabs/rudderstack-docs pull request #411
Opened 2022-02-18 06:17 UTC by ameypv-rudder

## Description of the change

> Updated content.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-02-18 07:52 UTC, saikumarrs commented on stream-sources/shopify.mdx
> +| `orders_paid`                 | Order was paid.             | `orders/paid`                 | `track`                |
The Shopify event names here are plural which contradicts the description.
@yashasvibajpai @arajguha

2022-02-18 07:56 UTC, saikumarrs commented on stream-sources/shopify.mdx
> +| Shopify event name            | Description                 | Subscribed topic              | RudderStack event type |
Let's provide an example for server-side and client-side events.

2022-02-18 09:42 UTC, yashasvibajpai commented on stream-sources/shopify.mdx
> +"write_script_tags"
Yes sure. Sorry for missing this change from yesterday. 
@ameypv-rudder below is the new scope list:
`"read_checkouts",
    "read_orders",
    "read_customers",
    "read_fulfillments",
    "write_script_tags"`

2022-02-18 09:48 UTC, yashasvibajpai commented on stream-sources/shopify.mdx
> +| `orders_paid`                 | Order was paid.             | `orders/paid`                 | `track`                |
Actually Shopify event names are in plural only, even when they are fired for a single instance.
So a `orders_cancelled` call implies a single order is cancelled, just the event name is in plural.

2022-02-18 10:01 UTC, saikumarrs commented on stream-sources/shopify.mdx
> +| `orders_paid`                 | Order was paid.             | `orders/paid`                 | `track`                |
Sorry. I got confused with the RudderStack event names. However, instead of the Shopify event names, we should've included the RudderStack event names as they are user-facing.

2022-02-18 10:07 UTC, ameypv-rudder commented on stream-sources/shopify.mdx
> +| `orders_paid`                 | Order was paid.             | `orders/paid`                 | `track`                |
Agreed - can we have both if that makes the understanding easier?

2022-02-19 04:12 UTC, ameypv-rudder commented on stream-sources/shopify.mdx
> +| Shopify event name            | Description                 | Subscribed topic              | RudderStack event type |
@yashasvibajpai can you share these sample snippets?

2022-02-22 07:53 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +| `orders_paid`                 | Order was paid.             | `orders/paid`                 | `track`                |
Updated this section after discussion.

2022-02-22 07:53 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +| Shopify event name            | Description                 | Subscribed topic              | RudderStack event type |
Updated the sample snippets.

2022-02-22 08:36 UTC, saikumarrs requested changes

2022-02-22 08:36 UTC, saikumarrs commented on stream-sources/shopify.mdx
> +### Supported cloud mode events
Let's not use cloud and device mode in this document. It is applicable for destinations only. Instead, use server and client-side tracking.

2022-02-22 08:36 UTC, saikumarrs commented on stream-sources/shopify.mdx
> +```yaml
```suggestion
```json
```

2022-02-22 09:37 UTC, ishachopra0401 commented on stream-sources/shopify.mdx
> +### Supported cloud mode events
updated

2022-02-22 10:05 UTC, saikumarrs approved these changes

2022-02-22 10:56 UTC, utsabc commented
We should add the following in the FAQ
- What happens when my app is behaving unexpectedly and no event is flowing? (reinstall app)
- How to track events from multiple stores? (use multiple sources) - this is an obvious one but still
@arajguha @yashasvibajpai you guys could add some to FAQ list

2022-02-22 11:15 UTC, yashasvibajpai commented
@utsabc For multiple stores, we can use the same source also, we just need the app installed and properly configured in each of the stores.
Should we put this question in FAQ?

2022-02-22 12:39 UTC, utsabc commented
> @utsabc For multiple stores, we can use the same source also, we just need the app installed and properly configured in each of the stores. Should we put this question in FAQ?

Yes we can

2022-02-22 12:39 UTC, utsabc approved these changes

2022-02-22 12:40 UTC, arajguha approved these changes

2022-02-22 12:41 UTC, arajguha commented
LGTM

2022-02-22 12:49 UTC, yashasvibajpai approved these changes

2022-02-22 12:49 UTC, merged