RS cloud vs open-source docs
rudderlabs/rudderstack-docs pull request #442
Opened 2022-03-05 05:46 UTC by ameypv-rudder

## Description of the change

> Comparison guide between RS Cloud and open-source

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-03-07 19:01 UTC, esadek commented
Some other features that are only available to cloud customers:
- [Models](https://www.rudderstack.com/docs/connections/models/)
- [Client-side Event Filtering](https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/event-filtering/)
- Events tab

2022-03-08 06:29 UTC, ishachopra0401 requested changes

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +This guide compares the feature differences between the two primary [RudderStack](https://rudderstack.com/) offerings - [RudderStack Cloud](https://app.rudderstack.com/signup?type=freetrial) and [Rud
```suggestion
This guide compares the features present in the two primary [RudderStack](https://rudderstack.com/) offerings - [RudderStack Cloud](https://app.rudderstack.com/signup?type=freetrial) and [RudderStack Open Source](https://app.rudderstack.com/signup?type=opensource). It will help you in picking up the one suited to your requirements.
```

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Data plane setup in your own environment |  ✖ |  ✓ | [Setup instructions](https://www.rudderstack.com/docs/get-started/installing-and-setting-up-rudderstack/) for RudderStack Open Source  | Cloud u
We can may be un-bold the cross symbol in the whole doc. The reason is, both are RS offerings only. If we were comparing with a competitor, makes sense to highlight other one's shortcomings but as both are ours, we can keep it neutral. Thoughts?

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Reverse ETL | ✓ |  ✖ |  [Documentation](https://www.rudderstack.com/docs/warehouse-actions/) | [RudderStack Cloud Free](https://app.rudderstack.com/signup?type=freetrial) users can set up only 1 Wa
```suggestion
| Reverse ETL | ✓ |  ✖ |  [Documentation](https://www.rudderstack.com/docs/warehouse-actions/) | [RudderStack Cloud Free](https://app.rudderstack.com/signup?type=freetrial) users can set up only 1 Reverse ETL source.  | 
```

Should it be a Reverse ETL source? not sure, you can clarify.

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Events replay | ✓ |  ✖ | [Documentation](https://www.rudderstack.com/docs/user-guides/administrators-guide/event-replay/) | This is an [Enterprise](https://www.rudderstack.com/enterprise-quote/)-on
```suggestion
| Events replay | ✓ |  ✖ | [Documentation](https://www.rudderstack.com/docs/user-guides/administrators-guide/event-replay/) | Only available with the [Enterprise](https://www.rudderstack.com/enterprise-quote/) plan. | 
```

Or if we keep the original, maybe add the link on 'Enterprise-only', the whole term.

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Data governance | ✓ |  ✖ | [Documentation](https://www.rudderstack.com/docs/data-governance/)| This is an [Enterprise](https://www.rudderstack.com/enterprise-quote/)-only feature. |
same as above

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Feature |  Cloud |  Open Source | Reference | Comments |
```suggestion
| Feature |  RudderStack Cloud | RudderStack Open Source | Reference | Comments |
```
just a thought, as we do not mention RudderStack in any table header, might add more clarity

2022-03-08 06:29 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Transformations |  ✓ |  ✖ | [Documentation](https://www.rudderstack.com/docs/transformations/) | Only applicable for [cloud mode](https://www.rudderstack.com/docs/connections/rudderstack-connection
```suggestion
| Transformations |  ✓ |  ✖ | [Learn More](https://www.rudderstack.com/docs/transformations/) | Only applicable for [cloud mode](https://www.rudderstack.com/docs/connections/rudderstack-connection-modes/#cloud-mode) destinations. |
```

What are your thoughts on 'Learn more' instead of 'Documentation'?

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| [Control plane setup](https://www.rudderstack.com/docs/get-started/control-plane-lite/) in your own environment  |  ✕ |  ✓ | Cloud uses the RudderStack-hosted [web app](https://app.rudderstack.com/
```suggestion
| [Control plane setup](https://www.rudderstack.com/docs/get-started/control-plane-lite/) in your own environment  |  ✕ |  ✓ | Cloud uses the RudderStack-hosted [web app](https://app.rudderstack.com/) to manage your connections. |
```

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| [Data plane setup](https://www.rudderstack.com/docs/get-started/installing-and-setting-up-rudderstack/) in your own environment |  ✕ |  ✓ | Cloud uses a RudderStack-hosted [data plane](https://www.
```suggestion
| [Data plane setup](https://www.rudderstack.com/docs/get-started/installing-and-setting-up-rudderstack/) in your own environment |  ✕ |  ✓ | Cloud uses the RudderStack-hosted [data plane](https://www.rudderstack.com/docs/glossary/#data-plane). | 
```

just to be consistent with the below line

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| [Event backups in your own bucket](https://www.rudderstack.com/docs/user-guides/administrators-guide/bucket-configuration-settings/) |  ✓ |  ✓ | RudderStack can manage it for you as a part of the [
```suggestion
| [Event backup in your own bucket](https://www.rudderstack.com/docs/user-guides/administrators-guide/bucket-configuration-settings/) |  ✓ |  ✓ | RudderStack can manage it for you as a part of the [Enterprise plan](https://www.rudderstack.com/enterprise-quote/). | 
```

Observed that the topic name is 'backups' as well.. but we can maybe keep backup here and later on revamp the topic as well..

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| [Transformations](https://www.rudderstack.com/docs/transformations/) |  ✓ |  ✓ | <ul><li>In case of Open Source, this feature is only applicable for the [RudderStack-hosted control plane](https://a
```suggestion
| [Transformations](https://www.rudderstack.com/docs/transformations/) |  ✓ |  ✓ | <ul><li>In case of Open Source, this feature is only applicable for the [RudderStack-hosted control plane](https://app.rudderstack.com/signup?type=opensource) and users can set upto <strong>3 transformations</strong>.</li><li>In case of <a href="https://app.rudderstack.com/signup?type=freetrial" target="_blank">RudderStack Cloud Free</a>, users can set upto <strong>3 transformations</strong>.</li><li>Pro and Enterprise users can set up unlimited transformations.</li><li>It can be used only for [cloud mode](https://www.rudderstack.com/docs/connections/rudderstack-connection-modes/#cloud-mode) destinations.</li></ul> |
```

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| [Model](https://www.rudderstack.com/docs/reverse-etl/features/models/) as a source | ✓ |  ✕  | Models let you define and run custom SQL queries on your warehouse and send the resulting data to spec
```suggestion
| [Models](https://www.rudderstack.com/docs/reverse-etl/features/models/) | ✓ |  ✕  | Models let you define and run custom SQL queries on your warehouse and send the resulting data to specific destinations. |
```

2022-03-24 10:36 UTC, ishachopra0401 commented on get-started/cloud-vs-open-source.mdx
> +| Ability to add other team members in the workspace | ✓ |  ✕  |  You can invite 3 members in your workspace in case of  [RudderStack Cloud Free](https://app.rudderstack.com/signup?type=freetrial), w
```suggestion
| Ability to add other team members in the workspace | ✓ |  ✕  |  You can invite upto 3 members in your workspace in [RudderStack Cloud Free](https://app.rudderstack.com/signup?type=freetrial), upto 10 members in Pro, and unlimited members in the Enterprise plan. | 
```

2022-03-24 11:09 UTC, ishachopra0401 approved these changes

2022-03-24 16:09 UTC, merged

2022-03-28 23:29 UTC, psrikanth88 commented on get-started/cloud-vs-open-source.mdx
> +| Maintaining events ordering | ✓ |  ✕ | This is an [Enterprise-only](https://www.rudderstack.com/enterprise-quote/) feature. |
OSS does have event ordering too. Only in the case of multi-node Rudderstack setup, it is not guaranteed

2022-03-28 23:31 UTC, psrikanth88 commented
Great doc. Should we have one more comparing free tier to pro. Or would that be more for the rudderstack.com than the docs?

2022-03-29 02:56 UTC, ameypv-rudder commented on get-started/cloud-vs-open-source.mdx
> +| Maintaining events ordering | ✓ |  ✕ | This is an [Enterprise-only](https://www.rudderstack.com/enterprise-quote/) feature. |
Got it - will add this point. Thanks Srikanth!

2022-03-29 02:58 UTC, ameypv-rudder commented
> Great doc. Should we have one more comparing free tier to pro. Or would that be more for the rudderstack.com than the docs?

Yeah IMO. There were will be way too many variables if we introduce pro in this doc, and that can cause confusion. Hence just kept it generic (Cloud) for comparison purposes. 

Our pricing page does a great job of comparing the different plans and we do mention this at the start of the doc.