ActiveCampaign documentation update
rudderlabs/rudderstack-docs pull request #443
Opened 2022-03-07 06:11 UTC by ameypv-rudder

## Description of the change

> Updated ActiveCampaign docs to explicitly specify that the `screen` and `track` calls must have only alphanumeric characters in the event name.
> Reordered the doc to include the following order of sections: Identify > Page > Screen > Track.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-03-08 03:46 UTC, yashasvibajpai approved these changes

2022-03-08 08:47 UTC, ishachopra0401 requested changes

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
>  The `identify` call lets you associate a user with their actions and capture all the relevant traits about them. This information includes unique `userid` as well as any optional information such as
```suggestion
The `identify` call lets you associate a user with their actions and captures all the relevant traits about them. This information includes unique `userid` as well as any optional information such as name, email address, etc.
```

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +The <code class="inline-code">email</code> trait is a mandatory trait for mapping a user to ActiveCampaign. If a user already exists, the new values will be updated for that user.
>If a user already exists, the new values will be updated for that user.
bit confusing, does it mean that if a user already exists, the new 'email' value will be updated for that user?

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +The <code class="inline-code">tags</code> property should contain an array of tags which you want to associate with the user. If any tag is already created in the destination previously, RudderStack
```suggestion
The <code class="inline-code">tags</code> property should contain an array of tags which you want to associate with the user. If any tag is already created in the destination previously, RudderStack will override the tag information with the new one.
```

Does it mean this?

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +The <code class="inline-code">fieldInfo</code> property contains the value of the field information that you want to store for that contact. For using this feature, you have to create the fields from
```suggestion
The <code class="inline-code">fieldInfo</code> trait contains the value of the custom field that you want to store for that contact. For using this feature, you have to create the custom fields from your ActiveCampaign dashboard \(For example - Interest, Country\) before passing the values for the given user.
```

We have used `fieldInfo` **trait** above. Can 'trait' and 'property' be used interchangeably?

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +The `page` call allows you to record information whenever a user sees a web page, along with the associated optional properties of that page. This method must be called at least once per page load.
```suggestion
The `page` call lets you record information whenever a user sees a web page, along with the associated optional properties of that page. This method must be called at least once per page load.
```

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +The `screen` method allows you to record whenever a user sees the mobile screen, along with any associated optional properties. This call is similar to the `page` call, but is exclusive to your mobil
```suggestion
The `screen` method lets you record whenever a user sees the mobile screen, along with any associated optional properties. This call is similar to the `page` call, but is exclusive to your mobile device.
```

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +If you want to set a value for the <code class="inline-code">screen</code> and <code class="inline-code">track</code> type event, you need to pass <code class="inline-code">name</code> in the event p
We have mentioned 'name' only in track-type event, not in screen event but say 'as shown in the above example'. Can be misleading..

2022-03-08 08:47 UTC, ishachopra0401 commented on destinations/marketing/activecampaign.mdx
> +No, your `screen` and `track` event names must contain only alphanumeric characters. ActiveCampaign prescribes that the `screen` and `track` event names must contain only alphabets and numbers, and d
```suggestion
No, your `screen` and `track` event names must contain only alphanumeric characters. ActiveCampaign prescribes that the `screen` and `track` event names must contain only alphabets and numbers, and does not allow the usage of any special characters.
```

2022-03-08 09:11 UTC, utsabc approved these changes

2022-03-10 04:36 UTC, ishachopra0401 approved these changes

2022-03-10 04:36 UTC, merged