personalize: docs new addition
rudderlabs/rudderstack-docs pull request #47
Opened 2021-03-17 04:04 UTC by shrouti1507

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-03-17 05:05 UTC, arnab-p requested changes

2021-03-17 05:05 UTC, arnab-p commented on destinations/aws-personalize.md
> +     As event name is a mandatory field here, that means you can only send `track` events. Also remember that, inside the payload you have to specify the **same** event name, which you have used whil
```suggestion
     As event name is a mandatory field here, you can only send `track` events. Also, you need to specify the **same** event name, which you have used while configuring the destination on [RudderStack dashboard](https://app.rudderstack.com/)
```

2021-03-17 08:14 UTC, ruchiramoitra approved these changes

2021-03-18 06:39 UTC, arnab-p approved these changes

2021-03-18 06:39 UTC, merged