Data storage JavaScript SDK
rudderlabs/rudderstack-docs pull request #472
Opened 2022-03-22 08:15 UTC by ishachopra0401

## Description of the change

Added new topic for JavaScript data storage by cookies or local storage

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-03-23 06:23 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `rl_trait`       | Stores the user traits object set via the `identify` API method. All the subsequent event payloads will contain this data unless overridden. |  <pre>{<br>  email: "alex@example.
```suggestion
|  `rl_trait`       | Stores the user traits object set via the `identify` API method. All the subsequent event payloads will contain this data unless overridden. |  <pre>{<br>  email: "alex@example.com",<br>  accountType: "pro",<br>  country: "US",<br>  someObj: {<br>    key1: val1,<br>    key2: val2,<br>  }<br>}</pre>         |`rudderanalytics.reset()` |
```

2022-03-23 06:27 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `rl_anonymous_id`          | Stores the anonymous ID. By default, it would be the auto-generated unique ID by SDK for each visitor unless overridden via `setAnonymousId` API method. All the subseq
For these 3 entries, update the last statement as below:

"All the subsequent event payloads will contain this data unless cleared from the storage."

2022-03-23 06:29 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `rl_group_trait`    | Stores the user group traits object set via the `group` API method.   |    <pre>{<br>  location: "New Orleans",<br>  nationality: "US",<br>  someObj: {<br>    key1: val1,<br>
For these 2 items, add the following statement to the description:

"All the subsequent group event payloads will contain this data unless cleared from the storage."

2022-03-23 06:32 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `reclaimStart`/`reclaimEnd`      |Determines if a tab takes over the queue from another tab  | `2dc2aee6-2836-4273-be69-79c90c04ddec`  |
These variables together contribute to the purpose.
```suggestion
|  `reclaimStart` and `reclaimEnd`      |Determines if a tab takes over the queue from another tab  | `2dc2aee6-2836-4273-be69-79c90c04ddec`  |
```

2022-03-23 06:33 UTC, saikumarrs commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `queue`    | Keeps track of the events that are in queue to be processed   | <pre>[<br>  {<br>   "item": {<br>    "url": "https://rudderstack-dataplane.rudderstack.com/v1/track",<br>     "headers"
The examples are ill-formatted.

2022-03-23 06:36 UTC, saikumarrs requested changes
Added comments for improvements.

2022-03-23 11:33 UTC, saikumarrs approved these changes

2022-03-25 07:53 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +RudderStack's JavaScript SDK stores persistent user data in cookies by default. In case the cookies are not supported, local storage is considered for the same.
```suggestion
By default, the RudderStack JavaScript SDK stores persistent user data in the cookies. If the cookies are not supported, local storage is used instead. 
```

2022-03-25 07:54 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +All the cookies are stored in the top-level domain by default. It helps to identify the users visiting from websites that are hosted under a sub-domain. For example, if you include the RudderStack Ja
```suggestion
All the cookies are stored in the top-level domain by default. It helps you to identify the users visiting from websites hosted under a particular sub-domain. For example, if you include the JavaScript SDK in both `admin.samplewebsite.com` and `app.samplewebsite.com`, the SDK will store the cookie in `samplewebsite.com`. However, you can configure where you want to store the cookie by using the `setCookieDomain` parameter in the `load` API options as shown:
```

2022-03-25 07:55 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +The list of cookies used by JavaScript SDK to store persistent user data is mentioned below:
```suggestion
The list of cookies used by the JavaScript SDK to store persistent user data is mentioned below:
```

2022-03-25 07:55 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +| Name             | Description       | Example    | Clearing Mechanism using SDK |
```suggestion
| Name             | Description       | Example    | Clearing mechanism using the SDK |
```

2022-03-25 07:55 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `rl_user_id`         |Stores the user ID set via the `identify` API method. All the subsequent event payloads will contain this data unless cleared from the storage. | `4578`, `USER_001` | `rudder
```suggestion
|  `rl_user_id`         |Stores the user ID set via the `identify` API. All the subsequent event payloads will contain this data unless cleared from the storage. | `4578`, `USER_001` | `rudderanalytics.reset()`  |
```

2022-03-25 07:56 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `rl_trait`       | Stores the user traits object set via the `identify` API method. All the subsequent event payloads will contain this data unless cleared from the storage. |  <pre>{<br>  email:
```suggestion
|  `rl_trait`       | Stores the user traits object set via the `identify` API. All the subsequent event payloads will contain this data unless cleared from the storage. |  <pre>{<br>  email: "alex@example.com",<br>  accountType: "pro",<br>  country: "US",<br>  someObj: {<br>    key1: val1,<br>    key2: val2,<br>  }<br>}</pre>         |`rudderanalytics.reset()` |
```

2022-03-25 08:00 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +| `rl_page_init_referrer`        | Stores the initial referrer of the page when a user visits a site for the first time. All the subsequent event payloads will contain this data.    | https://www.goo
```suggestion
| `rl_page_init_referrer`        | Stores the initial referrer of the page when a user visits a site for the first time. All the subsequent event payloads will contain this data.    | `https://www.google.com/` | Cannot be cleared using SDK |
```

2022-03-25 08:01 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +| `rl_page_init_referring_domain`      | Stores the initial referring domain of the page when a user visits a site for the first time. All the subsequent event payloads will contain this data.  |  go
```suggestion
| `rl_page_init_referring_domain`      | Stores the initial referring domain of the page when a user visits a site for the first time. All the subsequent event payloads will contain this data.  |  `google.com` | Cannot be cleared using SDK. |
```

2022-03-25 08:02 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +The local storage cookies are used by the JavaScript SDK to keep track of the events being sent to the RudderStack backend. These can be listed as below:
```suggestion
The local storage cookies are used by the JavaScript SDK to keep track of the events sent to the RudderStack backend. They are listed in the table below:
```

2022-03-25 08:03 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `ack`     | Timer for other browser tabs to claim control of the retry queue     | `1639734070124` |
```suggestion
|  `ack`     | Timer for other browser tabs to claim control of the retry queue.     | `1639734070124` |
```

2022-03-25 08:03 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `inProgress`    | Keeps track of the events in progress | <pre>{<br>  "d89d7fb5-945e-4378-bda5-492e4b596fb4": {<br>   "item": {<br>    "url": "https://rudderstack-dataplane.rudderstack.com/v1/trac
```suggestion
|  `inProgress`    | Keeps track of the events in progress. | <pre>{<br>  "d89d7fb5-945e-4378-bda5-492e4b596fb4": {<br>   "item": {<br>    "url": "https://rudderstack-dataplane.rudderstack.com/v1/track",<br>    "headers": {<br>     "Content-Type": "application/json",<br>      ...<br>    },<br>    "message": { <br>     ...<br>    }<br>    "attemptNumber": 1,<br>    "time": 1639734792773,<br>    "id": "a4d89d7f-b594-4eb3-b8bd-a5492e4b596f"<br>   }<br>  }<br>}<br></pre> |
```

2022-03-25 08:03 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/data-storage-cookies.mdx
> +|  `queue`    | Keeps track of the events that are in queue to be processed   | <pre>[<br>  {<br>   "item": {<br>    "url": "https://rudderstack-dataplane.rudderstack.com/v1/track",<br>    "headers":
```suggestion
|  `queue`    | Keeps track of the events that are in queue to be processed.   | <pre>[<br>  {<br>   "item": {<br>    "url": "https://rudderstack-dataplane.rudderstack.com/v1/track",<br>    "headers": {<br>     "Content-Type": "application/json",<br>      ...<br>    },<br>    "message": { <br>     ...<br>    }<br>    "attemptNumber": 0,<br>    "time": 1639734792773,<br>    "id": "a4d89d7f-b594-4eb3-b8bd-a5492e4b596f"<br>   }<br>  }<br>]<br></pre> |
```

2022-03-25 08:04 UTC, ameypv-rudder approved these changes

2022-03-25 08:12 UTC, merged