Airship documentation
rudderlabs/rudderstack-docs pull request #481
Opened 2022-03-28 09:29 UTC by ameypv-rudder

## Description of the change

> Added documentation for the Airship integration.

## Type of documentation
- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Airship documentation](https://www.notion.so/rudderstacks/Airship-Destination-Cloud-mode-ed0c7aed542f4db2b17bbf11fa99bd10)

2022-03-28 11:21 UTC, utsabc commented on destinations/marketing/airship.mdx
> +| `transaction` | `transaction` | Optional |
These will be taken from `properties` right? @ujjwal-ab ?

2022-03-30 06:37 UTC, ameypv-rudder commented
@akashrpo @ujjwal-ab @utsabc this doc is ready for your review.

2022-03-30 12:50 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +The event name must not contain any upper case characters. Otherwise, the event will be rejected with a <code class="inline-code">400</code> status code.
It is handled on the RudderStack side like, "the event name having multiple words with spaces between them and uppercase characters are being converted to lowercase characters and "_" between the words with spaces as Airship doesn't support them. eg. ("Product       Clicked" -> "product_clicked")

2022-03-30 12:50 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +To successfully assign tags to Airship using the RudderStack <code class="inline-code">identify</code> events, you must create a tag group with the group key set to <code class="inline-code">rudderst
The similar is also true for attributes.

2022-03-30 13:31 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +| `transaction` | `transaction` | Optional |
Yes

2022-03-30 13:47 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +The event name must not contain any upper case characters. Otherwise, the event will be rejected with a <code class="inline-code">400</code> status code.
Added this information.

2022-03-30 13:48 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +To successfully assign tags to Airship using the RudderStack <code class="inline-code">identify</code> events, you must create a tag group with the group key set to <code class="inline-code">rudderst
Yep, added this information as well.

2022-03-30 15:08 UTC, utsabc commented on destinations/marketing/airship.mdx
> +  },
Do we need this as no one uses track to send user info this way

2022-03-30 15:54 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +The event requests are rate limited to 500 events/sec per app.
Yes, We can remove this line. @ameypv-rudder

2022-03-30 16:00 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
Yes, It is added here `rudderstack_integration_group`[https://github.com/rudderlabs/rudderstack-docs/pull/481/files#:~:text=To%20successfully%20assign%20tags%20to%20Airship%20using%20the%20RudderStack%20%3Ccode,in%20Airship%20to%20set%20the%20attributes%20on%20the%20named%20users.](url)

2022-03-30 16:04 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +  },
Similar to this is shown in Airship.

2022-03-30 16:09 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +The event requests are rate limited to 500 events/sec per app.
Got it - will remove this.

2022-03-30 16:54 UTC, utsabc commented on destinations/marketing/airship.mdx
> +  },
https://docs.airship.com/partners/segment/#custom-events
I am seeing this one. We should stick to out spec to avoid confusion w.r.t Rudderstack nomenclature

2022-03-30 16:55 UTC, utsabc commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
My bad :P

2022-03-31 04:29 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +  },
We can remove the user info. Apart from that is fine. Right?

2022-03-31 05:50 UTC, akashrpo commented on destinations/marketing/airship.mdx
> +rudderanalytics.identify("1hKOmRA4el9Zt1WSfVJIVo4GRlm", {
```suggestion
rudderanalytics.identify("userId", {
```

2022-03-31 05:56 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +rudderanalytics.identify("1hKOmRA4el9Zt1WSfVJIVo4GRlm", {
Do the same for the group too.

2022-03-31 06:09 UTC, akashrpo commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
For group call named_user_id is associated with `userId` and not `groupId` cc @ujjwal-ab

2022-03-31 07:01 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +  },
Lets remove the user info from proprties. [here](https://github.com/rudderlabs/rudderstack-docs/pull/481/files#:~:text=name%3A%20%22Alex%20Keener,%7D%2C)

2022-03-31 07:09 UTC, ujjwal-ab requested changes
```
rudderanalytics.group({
            userId: "abc123",
            firstName: true,
            lastName: true,
            age: 13,
          });
```

2022-03-31 07:09 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
Let's update the group example.

2022-03-31 08:12 UTC, utsabc commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
```
client.group(groupId,{
  userId: "userId",
  firstName: true,
  lastName: true,
  })
```
Lets do this @ujjwal-ab

2022-03-31 08:19 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +rudderanalytics.identify("1hKOmRA4el9Zt1WSfVJIVo4GRlm", {
We made this change by following a [unified user persona](https://docs.google.com/spreadsheets/d/1Yh6ws_MNK6-Fp7L4Q0LhhmRMpdnT5f1pZx9wxM9dWRs/edit#gid=0) - this will help us maintain consistency in code samples across all the destination docs going forward. `1hKOmRA4el9Zt1WSfVJIVo4GRlm` (can be shortened, if required) is more realistic than just `userId`. Thoughts? @akashrpo

2022-03-31 08:24 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
@utsabc there's no mention of the attributes (non-Bool values) in the above snippet. Will that be okay?

2022-03-31 08:29 UTC, utsabc commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
I just put an example w.r.t structure, @ujjwal-ab can you share a proper group example

2022-03-31 08:29 UTC, akashrpo commented on destinations/marketing/airship.mdx
> +rudderanalytics.identify("1hKOmRA4el9Zt1WSfVJIVo4GRlm", {
Let's follow this approach. Seems good.

2022-03-31 08:29 UTC, ujjwal-ab commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
Ya, sure.

2022-03-31 08:34 UTC, akashrpo commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
```
client.group({
  userId: "userId",
  traits: {
    firstName: true,
    lastName: true,
    tags3: true,
    favorite_color: "purple",
    attribute: "value",
  },
})
```
cc @ujjwal-ab @utsabc

2022-03-31 09:12 UTC, ameypv-rudder commented on destinations/marketing/airship.mdx
> +rudderanalytics.group("group01", {
Snippet updated

2022-03-31 09:29 UTC, ishachopra0401 commented on destinations/marketing/airship.mdx
> +- **API Key**: Enter your Airship token required by RudderStack to communicate with your Airship project.
```suggestion
- **API Key**: Enter your Airship token which is required by RudderStack to communicate with your Airship project.
```

2022-03-31 09:29 UTC, ishachopra0401 commented on destinations/marketing/airship.mdx
> +- **App Key**: Enter your Airship project's app key by going to **Settings** > **Project Details**.
```suggestion
- **App Key**: Enter your Airship project's app key by going to **Settings** > **Project Details** in the Airship dashboard.
```

2022-03-31 09:29 UTC, ishachopra0401 commented on destinations/marketing/airship.mdx
> +- **App Secret**: Enter your Airship project's app secret by going to **Settings** > **Project Details**.
```suggestion
- **App Secret**: Enter your Airship project's app secret by going to **Settings** > **Project Details** in the Airship dashboard.
```

2022-03-31 09:29 UTC, ishachopra0401 commented on destinations/marketing/airship.mdx
> +You will find your project's app key listed here. To obtain the app secret, click on on **Click to reveal**, as shown:
```suggestion
You will find your project's app key listed here. To obtain the app secret, click on **Click to reveal**, as shown:
```

2022-03-31 10:29 UTC, utsabc approved these changes

2022-03-31 10:39 UTC, akashrpo commented on destinations/marketing/airship.mdx
> +  userId: "1hKOmRA4el9Zt1WSfVJIVo4GRlm"
```suggestion
  userId: "1hKOmRA4el9Zt1WSfVJIVo4GRlm",
```

2022-03-31 10:59 UTC, ishachopra0401 approved these changes

2022-03-31 11:06 UTC, akashrpo approved these changes

2022-03-31 11:09 UTC, ujjwal-ab approved these changes

2022-03-31 11:16 UTC, merged