DCM Floodlight doc
rudderlabs/rudderstack-docs pull request #505
Opened 2022-04-11 09:54 UTC by ishachopra0401

## Description of the change

Created new doc for DCM Floodlight integration

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-04-13 08:54 UTC, akashrpo commented
Let's show `+ ADD MORE` option too in [dcm-floodlight-connection-settings2.png](https://github.com/rudderlabs/rudderstack-docs/pull/505/files#diff-87541343aaca59243178050c308c7c9a8d3a3d46cb1262bb455131209bab0258)

2022-04-13 11:37 UTC, akashrpo requested changes

2022-04-13 11:37 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
Let's add an info block below stating `userAgent` is a required field and must be passed

2022-04-13 11:37 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +    <li><strong>Sales tag</strong>: Used to count the number of conversions. It is supposed to be placed on the confirmation page after a sale with information about the sales, like `cost`,`qty`, or
we can add this info - counts no. of conversions, plus the total number of sales that take place and the total associated revenue.

2022-04-13 11:37 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +- **Custom Floodlight variables:** Enter the custom Floodlight variables which will be mapped to the RudderStack event properties.
we are not mapping to the RudderStack event properties. we can mention something like - Enter the custom Floodlight variables to capture additional reporting data.

2022-04-13 11:37 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +| `context.device.adTrackingEnabled` | `dc_lat` | Optional |Counter/Sales|
Let's showcase these tags together as counter/sales -> counter -> sales for readability purpose

2022-04-13 14:15 UTC, utsabc commented on destinations/advertising/dcm-floodlight.mdx
> +| `properties.quantity` | `qty` | Optional | Sales |
If products are there its sum of quantity of all the products

2022-04-13 14:16 UTC, utsabc commented on destinations/advertising/dcm-floodlight.mdx
> +<img src="../../assets/event-stream-destinations/advertiser-id-dcm-floodlight.png" alt="DCM Floodlight connection settings"/>
There is details of Sharesis account please crop the image

2022-04-13 14:17 UTC, utsabc commented on destinations/advertising/dcm-floodlight.mdx
> +- **Group Tag:** Enter the `type` of your tag string to define the same parameter value across all the group conversion events. Alternatively, you can define this value for each conversion event in t
FAQ section thing how does a user find the `cat` and `type`?

2022-04-13 14:21 UTC, utsabc commented on destinations/advertising/dcm-floodlight.mdx
> +
FAQ How can one get the reports of events in DCM

2022-04-14 04:05 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +Find the open-source transformer code for this destination in our <a href="https://github.com/rudderlabs/rudder-transformer/tree/master/v0/destinations/dcm_floodlight">GitHub repo</a>.
Is this available/accessible for the general users, yet? cc @utsabc

2022-04-14 04:09 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +Find the open-source transformer code for this destination in our <a href="https://github.com/rudderlabs/rudder-transformer/tree/master/v0/destinations/dcm_floodlight">GitHub repo</a>.
Yes, this link is accessible for the general users and it is up and running rn since the changes are merged.

2022-04-14 04:10 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +Find the open-source transformer code for this destination in our <a href="https://github.com/rudderlabs/rudder-transformer/tree/master/v0/destinations/dcm_floodlight">GitHub repo</a>.
Got it - thanks!

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +- **Group Tag:** Enter the `type` of your tag string to define the same parameter value across all the group conversion events. Alternatively, you can define this value for each conversion event in t
Added this information as a FAQ.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +    <li><strong>Sales tag</strong>: Used to count the number of conversions. It is supposed to be placed on the confirmation page after a sale with information about the sales, like `cost`,`qty`, or
Added this info.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +- **Custom Floodlight variables:** Enter the custom Floodlight variables which will be mapped to the RudderStack event properties.
Fixed this setting.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +- **Custom Floodlight variables:** Enter the custom Floodlight variables which will be mapped to the RudderStack event properties.
Added this information as a FAQ

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
Sure. Added this info.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +| `npa` | `npa` |
Added this information.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +| `context.device.advertisingId` | `dc_rdid` | Required | Counter/Sales|
Added this info. Separated the table because 5 columns in a single table don't look good in our docs and the readers might miss out on the info entirely.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +| `properties.quantity` | `qty` | Optional | Sales |
Added this info.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +| `context.device.adTrackingEnabled` | `dc_lat` | Optional |Counter/Sales|
Done! Thanks for the suggestion.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +<img src="../../assets/event-stream-destinations/advertiser-id-dcm-floodlight.png" alt="DCM Floodlight connection settings"/>
Yep - will blur out the sensitive details in the images wherever applicable.

2022-04-14 06:06 UTC, ameypv-rudder commented on destinations/advertising/dcm-floodlight.mdx
> +
Added this information as a FAQ.

2022-04-14 06:11 UTC, ameypv-rudder commented
All the suggestions are now incorporated. LMK if we're good to go, @akashrpo @utsabc

2022-04-14 06:17 UTC, ameypv-rudder approved these changes

2022-04-14 07:16 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +### Where can I find the activity tag string (cat) and group tag string (type)?
We need to hide advertiserId, activityId from the images

2022-04-14 07:38 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +    <li><strong>Sales tag</strong>: Used to count the number of conversions, the total number of sales that take place, and the total associated revenue. It is supposed to be placed on the confirmati
```suggestion
    <li><strong>Sales tag</strong>: Used to count the number of conversions, the total number of sales that take place, and the total associated revenue. It is supposed to be placed on the confirmation page after a sale with information about the sales, like `cost`, `qty`, or `ord` properties passed to the tag.</li> 
```

2022-04-14 08:43 UTC, utsabc commented
Things are looking good but we are exposing the `advertiserId` as this is a customer's account lets censor it

2022-04-14 08:49 UTC, akashrpo commented on destinations/advertising/dcm-floodlight.mdx
> +In your Campaign Manager dashboard, go to **Floodlight** > **Activities**. Here you can see the all the activity names along with their **Activity tag string** (`cat`) and Group tag string (`type`),
```suggestion
In your Campaign Manager dashboard, go to **Floodlight** > **Activities**. Here you can see all the activity names along with their **Activity tag string** (`cat`) and Group tag string (`type`), as shown:
```

2022-04-14 08:51 UTC, akashrpo approved these changes
LGTM

2022-04-14 09:37 UTC, utsabc approved these changes

2022-04-14 09:38 UTC, merged