iOS SDK Swift migration
rudderlabs/rudderstack-docs pull request #506
Opened 2022-04-11 12:46 UTC by ameypv-rudder

## Description of the change

> iOS SDK v2 (Swift migration) documentation.

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [iOS SDK Swift migration](https://www.notion.so/rudderstacks/Documentation-Update-Swift-SDK-c7e6e635bbdb4c91970926b20a3c8274)

2022-04-25 04:57 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +    <Tab>Carthage</Tab>
Will the Carthage installation steps remain the same?

2022-04-25 04:59 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +| `options`    | `RudderOption` | Optional       | Extra options to be passed along with the `screen` call.     |
should this be `option` or `options`? As per the spec shared by you [here](https://www.notion.so/rudderstacks/Swift-migration-changes-Core-SDK-5ab9a96f526344d4bde3a149723cd18b) (refer to the Screen section)

2022-04-25 04:59 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +The iOS SDK does not persist the group traits across the sessions.
What is the reason for this? I think this information will be beneficial.

2022-04-25 05:00 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +RudderStack gives the users (for example, an EU user) the ability to opt out of tracking any user activity until they give their consent. You can do this by leveraging RudderStack's `setOptOutStatus`
Is the `setOptOutStatus` API available only from v2?

2022-04-25 05:01 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +### How do I ensure the events tracked just before closing/backgrounding the app are sent immediately and not on the next app launch?
If `enableBackgroundMode` is deprecated in this version, should we remove this FAQ as well?

2022-04-25 05:01 UTC, ameypv-rudder commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +### How do I migrate from v1.0.2?
Please review this FAQ and confirm if the **updated** parameter names remain the same

2022-04-25 05:03 UTC, ameypv-rudder commented
@pallabmaiti we would also need to review all the code snippets for accuracy and consistency with the v2 release.

2022-05-16 07:47 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +title: "iOS"
Should be `Swift`.

2022-05-16 07:51 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +  Detailed technical documentation on the RudderStack iOS SDK to send
```suggestion
  Detailed technical documentation on the RudderStack SDK to send
```

2022-05-16 07:52 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +  events from your iOS apps to various destinations.
```suggestion
  events from your iOS/tvOS/watchOS/macOS apps to various destinations.
```

2022-05-17 07:36 UTC, pallabmaiti commented
All the `RudderOption` will be `RSOption`, `options` to `option`, `RudderConfig` to `RSConfig`

2022-05-17 07:40 UTC, pallabmaiti requested changes

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +To set up the RudderStack iOS SDK, the following prerequisites must be met:
```suggestion
To set up the RudderStack Swift SDK, the following prerequisites must be met:
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +## Installing the RudderStack iOS SDK
```suggestion
## Installing the RudderStack Swift SDK
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +The RudderStack iOS SDK is distributed through [Cocoapods](https://cocoapods.org/pods/Rudder) and [Carthage](https://github.com/Carthage/Carthage).
```suggestion
The RudderStack SDK is distributed through [Cocoapods](https://cocoapods.org/pods/Rudder) and [Carthage](https://github.com/Carthage/Carthage).
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +To install the iOS SDK depending on your preference, follow the steps below:
```suggestion
To install the SDK depending on your preference, follow the steps below:
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +      <li>Add the iOS SDK to your <code class="inline-code">Podfile</code>, as shown:
```suggestion
      <li>Add the SDK to your <code class="inline-code">Podfile</code>, as shown:
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +pod 'RudderStack', '~> 1.0.0-beta.3'
```suggestion
pod 'Rudder', '~> 2.0.0'
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +#import <Rudder/Rudder.h>
```suggestion
@import Rudder;
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +[[RSClient sharedInstance] configureWith:config]
```suggestion
[[RSClient sharedInstance] configureWith:config];
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +| `logLevel`     | `RSLogLevel`     | Controls how much of the log you want to see from the iOS SDK.                | `RSLogLevel.None`                                                           |
```suggestion
| `logLevel`     | `RSLogLevel`     | Controls how much of the log you want to see from the SDK.                | `RSLogLevel.none`                                                           |
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +If you are using a device mode destination like Adjust, Firebase, etc., the iOS SDK needs to fetch the required configuration from the control plane. If you are using the [Control Plane Lite](https:/
```suggestion
If you are using a device mode destination like Adjust, Firebase, etc., the SDK needs to fetch the required configuration from the control plane. If you are using the [Control Plane Lite](https://www.rudderstack.com/docs/rudderstack-open-source/control-plane-lite/) utility to host your own control plane, then follow [this section](https://www.rudderstack.com/docs/rudderstack-open-source/control-plane-lite/#control-plane-url) to specify `controlPlaneUrl` in `RSConfig` that points to your hosted source configuration file.
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +You can configure your client based on the following parameters using `RudderConfig`:
```suggestion
You can configure your client based on the following parameters using `RSConfig`:
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +| `options` | `RudderOption` | Optional       | Extra options for the `identify` event.      |
```suggestion
| `option` | `RSOption` | Optional       | Extra options for the `identify` event.      |
```

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +### Does the iOS SDK support the tvOS and watchOS platforms?
Add macOS here.

2022-05-17 07:40 UTC, pallabmaiti commented on stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +| `RudderConfigBuilder` | `RSConfigBuilder` |
`RSConfigBuilder` - this class is not available.

2022-05-19 07:31 UTC, ameypv-rudder commented
Because of some issues with rebasing this branch with `main`, I've created a fresh PR with all the changes incorporated from @pallabmaiti 's feedback. Hence, closing this PR.

2022-05-19 07:31 UTC, closed without merging