Added documentation of clevertap android and iOS device modes
rudderlabs/rudderstack-docs pull request #56
Opened 2021-04-05 15:14 UTC by desusai7

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-04-07 08:21 UTC, ameypv-rudder approved these changes
Made some minor tweaks to the content, looks good to me otherwise. @desusai7 @arnab-p

2021-04-20 08:12 UTC, arnab-p requested changes

2021-04-20 08:12 UTC, arnab-p commented on destinations/clevertap.md
> +    maven { url 'https://dl.bintray.com/rudderstack/rudderstack' }
We need to update based on `mavenCentral` release

2021-04-22 07:27 UTC, desusai7 commented on destinations/clevertap.md
> +    maven { url 'https://dl.bintray.com/rudderstack/rudderstack' }
Will do that

2021-04-22 12:24 UTC, arnab-p approved these changes

2021-04-22 12:25 UTC, merged