BigQuery Update -  Deduplication Information
rudderlabs/rudderstack-docs pull request #565
Opened 2022-05-06 14:28 UTC by ameypv-rudder

## Description of the change

> BigQuery dedup information added to the documentation.

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [BigQuery documentation update - add information on deduplication method](https://www.notion.so/rudderstacks/BigQuery-documentation-update-add-information-on-deduplication-method-185c0f87725a47a5809c7dd0f1a5d255)

2022-05-06 15:47 UTC, psrikanth88 requested changes

2022-05-06 15:47 UTC, psrikanth88 commented on data-warehouse-integrations/google-bigquery.mdx
> +- Creates `users_view` while loading the `users` table.
Creates `users_view` while loading the `users` table 

Should we add a `if not present` to these statements ? @Jayachand

2022-05-09 15:07 UTC, Jayachand commented on data-warehouse-integrations/google-bigquery.mdx
> +- Creates `users_view` while loading the `users` table.
yeah, this would be fine
- Creates `users_view` if not present
- Creates the views for the new `track` events.
- All the other skipped views will not be regenerated. You can either create those views or [contact us](mailto:%20support@rudderstack.com).

2022-05-09 15:15 UTC, Jayachand commented on data-warehouse-integrations/google-bigquery.mdx
> +
one more warning here: 
`Query cost increases as duplicated are removed from tables through sequential scan`

wdyt @psrikanth88 ?

2022-05-09 18:53 UTC, psrikanth88 commented on data-warehouse-integrations/google-bigquery.mdx
> +
Yes, that would be good to add.

`Query cost increases as duplicates are removed from tables through sequential scan on every warehouse upload. Eg. If your warehouse upload frequency is 'Every  30 mins' - a full scan on tracks table would be performed every 30mins to upload new events to tracks table`

2022-05-10 07:51 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +You can easily switch from using the deduplication method to ingest your data in BigQuery to the partitioned tables by setting the config parameter `warehouse.bigquery.isDedupEnabled` to `false`.
incorporated this.

2022-05-10 07:51 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +### Deduplication method
yep - done!

2022-05-10 07:51 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +- Creates `users_view` while loading the `users` table.
Added this info

2022-05-10 07:51 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +
Done!

2022-05-10 11:24 UTC, ishachopra0401 approved these changes

2022-05-10 11:24 UTC, ishachopra0401 commented on data-warehouse-integrations/google-bigquery.mdx
> +More details on the BigQuery partitioned tables can be found in this <a href="https://cloud.google.com/bigquery/docs/partitioned-tables">BigQuery documentation</a>. More information on how RudderStac
```suggestion
You can find more details on the BigQuery partitioned tables in <a href="https://cloud.google.com/bigquery/docs/partitioned-tables">BigQuery documentation</a>. For information on how RudderStack creates these tables on load, refer to the <a href="https://cloud.google.com/bigquery/docs/creating-partitioned-tables#creating_an_ingestion-time_partitioned_table_when_loading_data">Creating partitioned tables</a> guide.
```

2022-05-10 11:24 UTC, ishachopra0401 commented on data-warehouse-integrations/google-bigquery.mdx
> +Note that the <strong>querying cost will increase</strong> if you choose this method, as RudderStack removes the duplicates from the tables through sequential scans that happen on every warehouse upl
```suggestion
Note that the <strong>querying cost will increase</strong> if you choose this method, as RudderStack removes the duplicates from the tables through sequential scans that happen on every warehouse upload. For example, if your warehouse upload frequency is set to  every 30 minutes, RudderStack performs a full scan on the <code class="inline-code">tracks</code> table every 30 minutes to upload any new events.
```

2022-05-10 11:24 UTC, ishachopra0401 commented on data-warehouse-integrations/google-bigquery.mdx
> +- All the other skipped views are not regenerated. You can either manually create those views or [contact us](mailto:%20support@rudderstack.com).
```suggestion
- All the other skipped views are not regenerated. You can either manually create those views or [contact us](mailto:%20support@rudderstack.com) to get them created.
```

2022-05-10 12:58 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +If you are using [open source RudderStack](https://rudderstack.com/docs/rudderstack-open-source), you can manage these modes via the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED`
```suggestion
If you are using [open source RudderStack](https://rudderstack.com/docs/rudderstack-open-source) or are hosting the RudderStack data plane, you can manage these modes via the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED`, as shown in the following table:
```

2022-05-10 12:59 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +If you are using [open source RudderStack](https://rudderstack.com/docs/rudderstack-open-source) or are hosting the RudderStack data plane, you can manage these modes via the environment variable `RS
```suggestion
If you are using [open source RudderStack](https://rudderstack.com/docs/rudderstack-open-source) or hosting the RudderStack data plane, you can manage these modes via the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED`, as shown in the following table:
```

2022-05-10 20:12 UTC, Jayachand commented on data-warehouse-integrations/google-bigquery.mdx
> +You can easily switch from using the deduplication method to ingest your data in BigQuery to the partitioned tables by setting the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED` i
remove open source term, as these options are available to both open source and RS deployments.
Mentioning above variable in this structure as open source guys are convenient to this.

2022-05-11 11:00 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +You can easily switch from using the deduplication method to ingest your data in BigQuery to the partitioned tables by setting the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED` i
```suggestion
You can easily switch from using the deduplication method to ingest your data in BigQuery to the partitioned tables by setting the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED` in your RudderStack setup to `false`.
```

2022-05-11 11:02 UTC, Jayachand approved these changes

2022-05-11 12:10 UTC, sivashanmukh approved these changes
LGTM

2022-05-11 12:17 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +In this method, RudderStack automatically discards any duplicate events while loading them into the BigQuery tables. To enable this method, set the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS
```suggestion
In this method, RudderStack automatically discards any duplicate events while loading them into the BigQuery tables. To enable this method, set the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED` in your RudderStack setup to `true`.
```

2022-05-11 12:18 UTC, ameypv-rudder commented on data-warehouse-integrations/google-bigquery.mdx
> +In this method, RudderStack automatically discards any duplicate events while loading them into the BigQuery tables. To enable this method, set the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS
```suggestion
In this method, RudderStack automatically discards any duplicate events while loading them into the BigQuery tables. To enable this method, set the environment variable `RSERVER_WAREHOUSE_BIGQUERY_IS_DEDUP_ENABLED` in your RudderStack data plane setup to `true`.
```

2022-05-11 13:39 UTC, merged