Personal Access Token documentation updates
rudderlabs/rudderstack-docs pull request #572
Opened 2022-05-10 12:49 UTC by ameypv-rudder

## Description of the change

> Updated location of the Personal access tokens doc to within the RS API section.

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Moving the Personal Access Tokens doc in the API docs section](https://www.notion.so/rudderstacks/Moving-the-Personal-Access-Tokens-doc-in-the-API-docs-section-for-more-visibility-suitability-3c311d95d8674717b42f2097f406d401)

2022-05-10 12:53 UTC, ameypv-rudder commented on rudderstack-cloud/dashboard-overview.mdx
> +Refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Token</a> guide for more details on this option.
```suggestion
Refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide for more details on this option.
```

2022-05-10 12:55 UTC, ameypv-rudder commented on data-governance/tracking-plans/index.mdx
> +1. Get your [Personal Access Token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```suggestion
1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```

2022-05-10 12:55 UTC, ameypv-rudder commented on data-governance/tracking-plans/index.mdx
> +1. Get your [Personal Access Token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```suggestion
1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```

2022-05-10 12:56 UTC, ameypv-rudder commented on rudderstack-api/data-regulation-api.mdx
> +You need to generate a [**Personal Access Token**](https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/) to authenticate the Data Regulation API and use it successfully.
```suggestion
You need to generate a [personal access token](https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/) to authenticate the Data Regulation API and use it successfully.
```

2022-05-10 22:34 UTC, esadek requested changes

2022-05-10 22:34 UTC, esadek commented on data-governance/tracking-plans/index.mdx
> +1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
Should change to

> **Generate a** [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) **in** the RudderStack dashboard.

2022-05-10 22:34 UTC, esadek commented on data-governance/tracking-plans/index.mdx
> +1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
Should change to

> **Generate a** [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) **in** the RudderStack dashboard.

2022-05-10 22:34 UTC, esadek commented on faqs.mdx
> +For more information on finding your access token, refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
Should change "finding your access token" to "generating an access token"

2022-05-10 22:34 UTC, esadek commented on reverse-etl/features/airflow-provider.mdx
> +For more information on obtain the access token, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
Should change "obtain the access token" to "generating an access token"

2022-05-10 22:34 UTC, esadek commented on rudderstack-api/personal-access-tokens.mdx
> +To consume all the public RudderStack APIs, you will need an access token associated with your RudderStack account. This guide describes the steps to generate your **personal access token** and the o
Should change "generate **your**" to "generate **a**"

2022-05-10 22:34 UTC, esadek commented on transformations/rudderstack-transformation-api.mdx
> +It is mandatory to generate your RudderStack personal access token to be able to make any API calls. For more information, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-
Should change "generate your RudderStack personal access token to be able to make any API calls" to "generate a personal access token to make any API calls"

2022-05-11 10:20 UTC, ameypv-rudder commented on data-governance/tracking-plans/index.mdx
> +1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```suggestion
1. Generate a [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) in the RudderStack dashboard.
```

2022-05-11 10:20 UTC, ameypv-rudder commented on data-governance/tracking-plans/index.mdx
> +1. Get your [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) from the RudderStack dashboard.
```suggestion
1. Generate a [personal access token](https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/) in the RudderStack dashboard.
```

2022-05-11 10:21 UTC, ameypv-rudder commented on faqs.mdx
> +For more information on finding your access token, refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
```suggestion
For more information on generating a personal access token, refer to the <a href="https://www.rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
```

2022-05-11 10:21 UTC, ameypv-rudder commented on reverse-etl/features/airflow-provider.mdx
> +For more information on obtain the access token, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
```suggestion
For more information on generating an access token, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
```

2022-05-11 10:21 UTC, ameypv-rudder commented on rudderstack-api/personal-access-tokens.mdx
> +To consume all the public RudderStack APIs, you will need an access token associated with your RudderStack account. This guide describes the steps to generate your **personal access token** and the o
```suggestion
To consume all the public RudderStack APIs, you will need an access token associated with your RudderStack account. This guide describes the steps to generate a **personal access token** and the operations associated with it.
```

2022-05-11 10:23 UTC, ameypv-rudder commented on transformations/rudderstack-transformation-api.mdx
> +It is mandatory to generate your RudderStack personal access token to be able to make any API calls. For more information, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-
```suggestion
You need to generate a personal access token to make any API calls. For more information, refer to the <a href="https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/">Personal Access Tokens</a> guide.
```

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/test-api.mdx
> +* You need to generate a [**Personal Access Token**](https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/) to authenticate the API successfully.
```suggestion
* You need to generate a [personal access token](https://rudderstack.com/docs/rudderstack-api/personal-access-tokens/) to authenticate the API successfully.
```

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/personal-access-tokens.mdx
> +To consume all the public RudderStack APIs, you will need an access token associated with your RudderStack account. This guide describes the steps to generate a **personal access token** and the oper
```suggestion
To consume all the public RudderStack APIs, you need an access token associated with your RudderStack account. This guide describes the steps to generate a **personal access token** and the operations associated with it.
```

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/personal-access-tokens.mdx
> +2. Go to **Settings** > **Personal access tokens**, as shown
```suggestion
2. Go to **Settings** > **Personal access tokens**, as shown:
```

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/personal-access-tokens.mdx
> +3. Click on **Generate new token**.
It would be great if we can include the 'Generate new token' option in the above screenshot

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/personal-access-tokens.mdx
> +Make sure you copy the generated token. You will not be able to see the token details again once you close this window.
```suggestion
Make sure you copy the generated token as it will not be visible again once you close this window.
```

2022-05-11 13:16 UTC, ishachopra0401 commented on rudderstack-api/personal-access-tokens.mdx
> +RudderStack Cloud users with the[**Read-Write**](https://www.rudderstack.com/docs/rudderstack-cloud/teammates/#read-write) or [**Admin**](https://www.rudderstack.com/docs/rudderstack-cloud/teammates/
```suggestion
The RudderStack Cloud users only with [Read-Write](https://www.rudderstack.com/docs/rudderstack-cloud/teammates/#read-write) or [Admin](https://www.rudderstack.com/docs/rudderstack-cloud/teammates/#admin) access permissions can create their own access tokens and use them.
```

2022-05-11 13:29 UTC, ameypv-rudder commented on rudderstack-api/personal-access-tokens.mdx
> +3. Click on **Generate new token**.
added a new screenshot

2022-05-11 13:30 UTC, ishachopra0401 approved these changes

2022-05-11 13:33 UTC, merged