Custom Domains documentation updates
rudderlabs/rudderstack-docs pull request #594
Opened 2022-05-17 09:37 UTC by ameypv-rudder

## Description of the change

> Updated custom domains doc with GCP load balancer-specific settings.

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Custom domains update](https://www.notion.so/rudderstacks/Custom-Domains-doc-update-07b88a86c96541239583ed9edb970044)

2022-05-18 18:33 UTC, MoumitaM commented on docs/user-guides/how-to-guides/custom-domains.mdx
> +
Add [this](https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/version-migration-guide/#case-3-self-hosting-rudderstacks-cdn) link here. 
`https://subdomain.yourdomain.com/v1.1/js-integrations` will basically be used as the `destSDKBaseURL` in load option.

2022-05-19 01:05 UTC, psrikanth88 requested changes

2022-05-19 01:05 UTC, psrikanth88 commented on docs/user-guides/how-to-guides/custom-domains.mdx
> +
@MoumitaM  @ameypv-rudder Should we update the first section `Setup for serving the SDK` to include code snippet to set the right `destSDKBaseURL` when using custom domains. Can include the snippet here again in FAQ just to reinforce

2022-05-19 06:36 UTC, MoumitaM commented on docs/user-guides/how-to-guides/custom-domains.mdx
> +
@psrikanth88, Yes we should.

2022-05-19 06:49 UTC, ishachopra0401 commented on docs/user-guides/how-to-guides/custom-domains.mdx
> +
@MoumitaM @psrikanth88 The requested changes have been addressed.

2022-05-19 06:51 UTC, psrikanth88 commented on docs/user-guides/how-to-guides/custom-domains.mdx
> +    destSDKBaseURL: "https://subdomain.yourdomain.com/v1.1/js-integrations/GA.min.js"
the destSDKBaseURL should not contain the `js-integrations/GA.min.js` part ?

2022-05-19 09:54 UTC, MoumitaM approved these changes

2022-05-20 11:36 UTC, ishachopra0401 approved these changes

2022-05-26 00:37 UTC, psrikanth88 approved these changes

2022-05-26 03:11 UTC, merged