Swift SDK migration
rudderlabs/rudderstack-docs pull request #597
Opened 2022-05-19 06:19 UTC by ameypv-rudder

## Description of the change

> Rebasing the older branch was causing some issues so moved the doc in a new PR. > Incorporated all suggestions made by @pallabmaiti as listed in [this] PR.

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Swift migration doc](https://www.notion.so/rudderstacks/Documentation-Update-Swift-SDK-c7e6e635bbdb4c91970926b20a3c8274)

2022-05-19 07:20 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +| `RudderConfigBuilder` | `RSConfigBuilder` |
@pallabmaiti as per your comment [here](https://github.com/rudderlabs/rudderstack-docs/pull/506/files#r874472740), `RSConfigBuilder` class is not available now. Should I go ahead and remove the reference from this table?

2022-05-19 07:21 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +### How do I ensure the events tracked just before closing/backgrounding the app are sent immediately and not on the next app launch?
@pallabmaiti as per your comment [here](https://github.com/rudderlabs/rudderstack-docs/pull/506/files#r873504858), we don't support this as of now but we might re-support it later.

Can we remove it from this doc **for now**, and then re-add it once we add support for this feature?

2022-05-19 07:22 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +RSConfigBuilder *builder = [[RSConfigBuilder alloc] init];
@pallabmaiti  Since `RSConfigBuilder` is not supported/available, does this code block need to be changed (if we are retaining this FAQ and not removing it completely)?

2022-05-19 07:24 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +### How do I migrate from an older SDK version to the current version?
@pallabmaiti can you please help me with [this comment](https://github.com/rudderlabs/rudderstack-docs/pull/506/files#r873506200)? How do I fetch the current version?

2022-05-19 07:37 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +| `RudderConfigBuilder` | `RSConfigBuilder` |
Yes please.

2022-05-19 07:38 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +### How do I ensure the events tracked just before closing/backgrounding the app are sent immediately and not on the next app launch?
Yes, we can do that.

2022-05-19 07:39 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +RSConfigBuilder *builder = [[RSConfigBuilder alloc] init];
I think this entire portion will be deleted. So, yes.

2022-05-20 08:19 UTC, ameypv-rudder commented
@pallabmaiti 

- Changed “Swift” to “iOS v2" and restructured the folder accordingly.
- Added information on the new features in the main iOS doc.
- Added relevant versions in the new and the current doc.

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +You can disable these events using the <code class="inline-code">trackLifecycleEvents</code> method of <code class="inline-code">RSConfig</code> by passing <code class="inline-code">false</code>. How
```suggestion
You can disable these events using the <code class="inline-code">trackLifecycleEvents</code> method of <code class="inline-code">RSConfig</code> and passing it as <code class="inline-code">false</code>. However, it is highly recommended to keep them enabled.
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +An sample `identify` call is shown below:
```suggestion
A sample `identify` call is shown below:
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +The <Link to="/rudderstack-api/api-specification/rudderstack-spec/alias"><code class="inline-code">alias</code></Link> call associates the user with a new identification. A sample `alias` call for th
```suggestion
The <Link to="/rudderstack-api/api-specification/rudderstack-spec/alias"><code class="inline-code">alias</code></Link> call associates the user with a new identification. A sample `alias` call is shown below:
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +Alternatively, you can use the following method signature
```suggestion
Alternatively, you can use the following method signature:
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +You can use the `reset` method to clear the persisted user traits for the `identify` call. This is required for the user logout operation.
```suggestion
You can use the `reset` method to clear the persisted user traits from the `identify` call. This is required for the user logout operation.
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +You only need to call the <code class="inline-code">setoptOutStatus</code> API with the relevant parameter only once, as the information persists within the device even if you reboot it.
```suggestion
You need to call the <code class="inline-code">setoptOutStatus</code> API with the relevant parameter only once, as the information persists within the device even if you reboot it.
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +The following snippet highlights the use of the `optOut` API to disable user tracking:
```suggestion
The following snippet highlights the use of the `setoptOutStatus` API to disable user tracking:
```

2022-05-20 08:26 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-swift-sdk.mdx
> +Once the user grants their consent, you can enable user tracking once again by using the `setOptOutStatus` API with `NO` or `false` as a parameter sent to it, as shown:
```suggestion
Once the user grants their consent, you can enable user tracking once again by using the `setOptOutStatus` API with `NO` or `false` as its parameter, as shown:
```

2022-05-20 09:09 UTC, pallabmaiti requested changes

2022-05-20 09:09 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +[option putIntegrationWithFactory:[RudderMoengageFactory instance] isEnabled:NO];
Line no. 756 & 757 is not available anymore.

2022-05-20 09:09 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +option.putIntegration(with: RudderMoengageFactory.instance(), isEnabled: true);
Line no. 772 & 773 not available anymore.

2022-05-20 09:09 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +class CustomDestination: RudderDestination {
```suggestion
@objc
class CustomDestination: RudderDestination {
```

2022-05-20 09:11 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +<strong>This documentation is written for the iOS SDK v1.6.0 and below</strong>. <br /><br />
```suggestion
<strong>This document is written for the iOS SDK v1.6.0 and below</strong>. <br /> 
You can also integrate the iOS SDK with your tvOS and watchOS apps and seamlessly track user events without any additional configuration. 

The tvOS apps are supported in the SDK version <strong>1.1.0 and above</strong> whereas the watchOS apps are supported in the SDK version <strong>1.3.1 and above</strong>.

</div>
```

2022-05-20 09:12 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +
<div class="infoBlock">

2022-05-20 09:13 UTC, ishachopra0401 commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +<div class="infoBlock">
This info block can be removed as content is merged above.

The idea is to keep the content for a specific iOS SDK version together.

2022-05-20 09:19 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/index.mdx
> +<strong>This documentation is written for the iOS SDK v1.6.0 and below</strong>. <br /><br />
```suggestion
<strong>This documentation is written for the iOS SDK v1.x</strong>. <br /><br />
```

2022-05-20 12:18 UTC, pallabmaiti approved these changes

2022-05-20 12:50 UTC, ishachopra0401 approved these changes

2022-05-20 13:04 UTC, merged