Bugsnag device mode updates for iOS SDK v2
rudderlabs/rudderstack-docs pull request #610
Opened 2022-05-25 07:11 UTC by ishachopra0401

## Description of the change

Bugsnag device mode updates for iOS SDK v2

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-05-30 09:07 UTC, pallabmaiti approved these changes

2022-05-30 09:09 UTC, pallabmaiti requested changes

2022-05-30 09:09 UTC, pallabmaiti commented on docs/destinations/error-reporting/bugsnag.mdx
> +          This device mode integration is supported for Bugsnag v8.15.0 and above.
```suggestion
          This device mode integration is supported for Bugsnag v6.16.4 and above.
```

2022-05-30 16:42 UTC, pallabmaiti commented
Words used in steps for Bugsnag are very much different from [Firebase](https://www.rudderstack.com/docs/destinations/analytics/firebase/#adding-device-mode-integration). Did we intentionally do that?

2022-05-31 06:18 UTC, pallabmaiti approved these changes

2022-05-31 06:18 UTC, ameypv-rudder commented
> Words used in steps for Bugsnag are very much different from [Firebase](https://www.rudderstack.com/docs/destinations/analytics/firebase/#adding-device-mode-integration). Did we intentionally do that?

@pallabmaiti please confirm if you are referring to the iOS v2 tab? Because the steps appear to be quite similar to Firebase.

2022-05-31 06:20 UTC, pallabmaiti commented
> @pallabmaiti please confirm if you are referring to the iOS v2 tab? Because the steps appear to be quite similar to Firebase.
I had a call with @ishachopra0401 to explain. It is sorted now.

2022-05-31 06:20 UTC, ameypv-rudder approved these changes

2022-05-31 07:35 UTC, merged