Amplitude - iOS v2 device mode update
rudderlabs/rudderstack-docs pull request #628
Opened 2022-06-01 09:01 UTC by ishachopra0401

## Description of the change

Amplitude - iOS v2 device mode update

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-06-02 15:59 UTC, pallabmaiti requested changes

2022-06-02 15:59 UTC, pallabmaiti commented on docs/destinations/analytics/amplitude.mdx
> +pod 'Amplitude', '~> 8.8.0'
Don't need this line.

2022-06-02 15:59 UTC, pallabmaiti commented on docs/destinations/analytics/amplitude.mdx
> +<li> Install <code class="inline-code">RudderAmplitude</code> by adding the following line to your <code class="inline-code">Podfile</code>.
```suggestion
<li> Install <code class="inline-code">RudderAmplitude</code> (available through [CocoaPods](https://cocoapods.org/)) by adding the following line to your <code class="inline-code">Podfile</code>.
```

2022-06-03 09:55 UTC, ameypv-rudder commented on docs/destinations/analytics/amplitude.mdx
> +Once you add Amplitude as a destination in the [RudderStack dashboard](https://app.rudderstack.com/), follow these steps to add it to your mobile project depending on your integration platform:
```suggestion
Once you add Amplitude as a destination in the [RudderStack dashboard](https://app.rudderstack.com/), follow these steps to add it to your project depending on your integration platform:
```

2022-06-03 09:56 UTC, ameypv-rudder commented on docs/destinations/analytics/amplitude.mdx
> +    <Tab>iOS V2</Tab>
```suggestion
    <Tab>iOS v2</Tab>
```

2022-06-03 09:56 UTC, ameypv-rudder commented on docs/destinations/analytics/amplitude.mdx
>  <li>In your <code class="inline-code">Podfile</code> and add the <code class="inline-code">Rudder-Amplitude</code> extension
```suggestion
<li>In your <code class="inline-code">Podfile</code>, add the <code class="inline-code">Rudder-Amplitude</code> extension, as shown:
```

2022-06-03 09:57 UTC, ameypv-rudder commented on docs/destinations/analytics/amplitude.mdx
> +<li> Install <code class="inline-code">RudderAmplitude</code> (available through <a href="https://cocoapods.org/">CocoaPods</a>) by adding the following line to your <code class="inline-code">Podfile
```suggestion
<li> Install <code class="inline-code">RudderAmplitude</code> (available through <a href="https://cocoapods.org/">CocoaPods</a>) by adding the following line to your <code class="inline-code">Podfile</code>:
```

2022-06-03 09:58 UTC, ameypv-rudder approved these changes
Extremely minor suggestions, good to go once they are incorporated!

2022-06-03 11:34 UTC, pallabmaiti approved these changes

2022-06-03 11:35 UTC, merged