App Center device mode integration steps for iOS v2
rudderlabs/rudderstack-docs pull request #646
Opened 2022-06-07 03:16 UTC by ameypv-rudder

## Description of the change

> Device mode integration for iOS v2

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> [App Center device mode updates](https://www.notion.so/rudderstacks/App-Center-device-mode-updates-69773888d2d5408ea6e52eb18105e33d)

2022-06-07 09:19 UTC, pallabmaiti requested changes

2022-06-07 09:19 UTC, pallabmaiti commented on docs/destinations/continuous-integration/appcenter.mdx
> +<li>Add App Center as a destination in the [RudderStack dashboard](https://app.rudderstack.com/).</li>
Hyperlink not working.

2022-06-07 09:57 UTC, ishachopra0401 commented on docs/destinations/continuous-integration/appcenter.mdx
>    <TabList>
Lets add this line before starting the tabs as it is common for all the platforms:

Once you add App Center as a destination in the [RudderStack dashboard](https://app.rudderstack.com/), follow these steps to add it to your mobile project depending on your integration platform:

2022-06-07 09:57 UTC, ishachopra0401 commented on docs/destinations/continuous-integration/appcenter.mdx
> +<li>Add App Center as a destination in the [RudderStack dashboard](https://app.rudderstack.com/).</li>
We can remove this step from here as added above (because common for all platforms)

2022-06-07 10:27 UTC, ameypv-rudder commented on docs/destinations/continuous-integration/appcenter.mdx
>    <TabList>
Makes sense - one thing to note, though - we will have to do this for all the previously merged device mode destinations for consistency purposes.

2022-06-07 11:47 UTC, ishachopra0401 approved these changes

2022-06-08 05:05 UTC, pallabmaiti approved these changes

2022-06-08 07:00 UTC, merged