Adjust device mode integration for iOS v2
rudderlabs/rudderstack-docs pull request #647
Opened 2022-06-07 03:53 UTC by ameypv-rudder

## Description of the change

> Adjust iOS v2 device mode integration steps

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Adjust iOS v2](https://www.notion.so/rudderstacks/Documentation-Update-Adjust-Device-Mode-37ec1bd61b86482c920e0a5f96aa1322)

2022-06-07 11:48 UTC, ishachopra0401 approved these changes

2022-06-07 11:48 UTC, ishachopra0401 commented on docs/destinations/attribution/adjust.mdx
> +<li>Install <code class="inline-code">RudderAdjust</code> (available through <a href="https://cocoapods.org/">CocoaPods</a> by adding the following line to your <code class="inline-code">Podfile</cod
```suggestion
<li>Install <code class="inline-code">RudderAdjust</code> (available through <a href="https://cocoapods.org/">CocoaPods</a>) by adding the following line to your <code class="inline-code">Podfile</code>:
```

2022-06-07 14:19 UTC, pallabmaiti requested changes

2022-06-07 14:19 UTC, pallabmaiti commented on docs/destinations/attribution/adjust.mdx
> +<li>Add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
Shouldn't it be 'add the following code to your.......'?

2022-06-08 02:09 UTC, ameypv-rudder commented on docs/destinations/attribution/adjust.mdx
> +<li>Add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
```suggestion
<li>Add the imports to your <code class="inline-code">AppDelegate</code> file under the <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
```

2022-06-08 02:09 UTC, ameypv-rudder commented on docs/destinations/attribution/adjust.mdx
> +<li>Add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
We're keeping it consistent with the steps present in the Firebase doc.

2022-06-08 05:02 UTC, pallabmaiti approved these changes

2022-06-08 07:00 UTC, merged