Singular iOS v2 device mode updates
rudderlabs/rudderstack-docs pull request #648
Opened 2022-06-07 04:03 UTC by ameypv-rudder

## Description of the change

> Singular iOS v2 device mode updates

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Singular iOS v2 device mode updates](https://www.notion.so/rudderstacks/Singular-device-mode-updates-4340707a42884edba22ee93dc58337da)

2022-06-07 11:49 UTC, ishachopra0401 approved these changes

2022-06-07 11:49 UTC, ishachopra0401 commented on docs/destinations/analytics/singular.mdx
> +<li>Install <code class="inline-code">RudderSingular</code> (available through <a href="https://cocoapods.org/">CocoaPods</a> by adding the following line to your <code class="inline-code">Podfile</c
```suggestion
<li>Install <code class="inline-code">RudderSingular</code> (available through <a href="https://cocoapods.org/">CocoaPods</a>) by adding the following line to your <code class="inline-code">Podfile</code>:
```

2022-06-07 14:17 UTC, pallabmaiti requested changes

2022-06-07 14:17 UTC, pallabmaiti commented on docs/destinations/analytics/singular.mdx
> +<li>Next, add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
Shouldn't it be 'add the following code to your.......'?

2022-06-08 02:10 UTC, ameypv-rudder commented on docs/destinations/analytics/singular.mdx
> +<li>Next, add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
We're keeping it consistent with the steps present in the Firebase doc.

2022-06-08 02:10 UTC, ameypv-rudder commented on docs/destinations/analytics/singular.mdx
> +<li>Next, add the imports to your <code class="inline-code">AppDelegate</code> file under <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
```suggestion
<li>Next, add the imports to your <code class="inline-code">AppDelegate</code> file under the <code class="inline-code">didFinishLaunchingWithOptions</code> method, as shown:
```

2022-06-08 04:58 UTC, pallabmaiti approved these changes

2022-06-08 07:00 UTC, merged