OneLogin SSO documentation updates
rudderlabs/rudderstack-docs pull request #650
Opened 2022-06-07 13:00 UTC by ameypv-rudder

## Description of the change

> Added updated documentation for OneLogin SSO

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> [OneLogin documentation updates](https://www.notion.so/rudderstacks/OneLogin-Documentation-Update-4daac0ce2495427189e62c5d04629227)

2022-06-07 14:16 UTC, aris1009 requested changes
Looks awesome! Just a value needs to be updated

2022-06-07 14:16 UTC, aris1009 commented on docs/user-guides/administrators-guide/onelogin-sso.mdx
> +| ACS (Consumer) URL Validator | `^https:VVauth2\.rudderstack\.comVsamI2VidpresponseV\S` |
```suggestion
| ACS (Consumer) URL Validator | `^https:\/\/auth2\.rudderstack\.com\/saml2\/idpresponse\/\$` |
```

2022-06-07 14:16 UTC, aris1009 commented on docs/user-guides/administrators-guide/onelogin-sso.mdx
> +| ACS (Consumer) URL Validator | `^https:VVauth2\.rudderstack\.comVsamI2VidpresponseV\S` |
This is a regex pattern and some characters need to be escaped

2022-06-08 02:12 UTC, ameypv-rudder commented
> Looks awesome! Just a value needs to be updated

thanks Aris - I've pushed the suggestion - LMK if we're good to go here.

2022-06-08 05:30 UTC, aris1009 approved these changes
lgtm

2022-06-08 07:16 UTC, ishachopra0401 approved these changes

2022-06-08 07:16 UTC, ishachopra0401 commented on docs/user-guides/administrators-guide/onelogin-sso.mdx
> +9. To add a custom parameter, simply click the **+** button, enter the **Field name**, and select the value from the dropdown, as shown:
```suggestion
9. To add any other custom parameter, click the **+** button, enter the **Field name**, and select the value from the dropdown, as shown:
```

2022-06-08 07:58 UTC, merged