iOS v2 push notifications support
rudderlabs/rudderstack-docs pull request #654
Opened 2022-06-08 11:05 UTC by ameypv-rudder

## Description of the change

> iOS v2 push notifications support

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> [Push notifications iOS v2](https://www.notion.so/rudderstacks/Push-Notifications-iOS-v2-2c042ae2e2f24011b51185e8dea38b14)

2022-06-08 15:46 UTC, pallabmaiti requested changes

2022-06-08 15:46 UTC, pallabmaiti commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +```swift
Let's add the ObjC functions:
`- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken;`

`- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error;`

`- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;`

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler;`

2022-06-09 05:45 UTC, ameypv-rudder commented on docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-ios-sdk/ios-v2.mdx
> +```swift
@pallabmaiti just to confirm, the user can use **any one** of the above four functions to enable the push notifications, right?

2022-06-09 07:16 UTC, pallabmaiti approved these changes

2022-06-09 12:29 UTC, ishachopra0401 approved these changes

2022-06-09 16:01 UTC, merged