Added Pinterest Destination
rudderlabs/rudderstack-docs pull request #67
Opened 2021-04-28 14:26 UTC by Shivam4415

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-04-29 09:54 UTC, ameypv-rudder approved these changes

2021-04-30 05:47 UTC, arnab-p requested changes

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +The [Pinterest Tag](https://ads.pinterest.com/advertiser/549762398656/conversions/tag/) is a piece of code that, when added to your website, allows Pinterest to track your visitors as well as their a
The URL here is redirecting to `https://ads.pinterest.com/`, so let's that URL?

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +RudderStack supports Pinterest as a destination to which you can send your customer events in real-time, through Pinterest's `pintrk` conversion tag.
Should we add a git link pointing to our implementation? Similar to others

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +To support Pinterest Enhanced Match, go to the Pinterest Tag destination settings in the Rudderstack dashboard and turn on the **Enable Enhanced Match on Page Load** option.
```suggestion
To support Pinterest Enhanced Match, go to the Pinterest Tag destination settings in the RudderStack dashboard and turn on the **Enable Enhanced Match on Page Load** option. 
```

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +When turned `on` this configuration will attach the hashed email address on the initial page load. Now any call made to Pinterest will be an Enhanced Match.
```suggestion
When turned `ON` this configuration will attach the hashed email address on the initial page load. Now any call made to Pinterest will be an Enhanced Match.
```

Does it look better? @ameypv-rudder

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +When you make an `identify()` call with the user’s email address and traits, RudderStack triggers a Pinterest `set()` method. This saves the identification parameters so they can be sent with the nex
```suggestion
When you make an `identify()` call with the user’s email address and traits, RudderStack triggers a Pinterest `set()` method. This saves the identification parameters to be sent with the next events, so it’s important to set the values as early as possible. 
```

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +## eCommerce
```suggestion
## E-Commerce
```

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +| Order Completed | `Checkout` |
Repeated line. Please remove one

2021-04-30 05:47 UTC, arnab-p commented on destinations/pinterest-tag.md
> +rudderanalytics.track('Event', {customProperty: { customValue: 2 }, someRandomMailId: 'user@gmail.com'})
Please format this snippet

2021-04-30 06:00 UTC, ameypv-rudder commented on destinations/pinterest-tag.md
> +The [Pinterest Tag](https://ads.pinterest.com/advertiser/549762398656/conversions/tag/) is a piece of code that, when added to your website, allows Pinterest to track your visitors as well as their a
makes sense.

2021-04-30 06:06 UTC, ameypv-rudder commented on destinations/pinterest-tag.md
> +When turned `on` this configuration will attach the hashed email address on the initial page load. Now any call made to Pinterest will be an Enhanced Match.
Tweaked this entirely.

2021-04-30 06:08 UTC, ameypv-rudder commented on destinations/pinterest-tag.md
> +RudderStack supports Pinterest as a destination to which you can send your customer events in real-time, through Pinterest's `pintrk` conversion tag.
Absolutely. Please share the link to our implementation.

2021-04-30 06:16 UTC, Shivam4415 commented on destinations/pinterest-tag.md
> +RudderStack supports Pinterest as a destination to which you can send your customer events in real-time, through Pinterest's `pintrk` conversion tag.
https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations/PinterestTag

2021-05-03 06:22 UTC, merged