GA4 enhancement
rudderlabs/rudderstack-docs pull request #676
Opened 2022-06-21 08:41 UTC by ishachopra0401

## Description of the change

Multiple event, mappings and UI changes
https://www.notion.so/rudderstacks/GA4-Enhancement-of-spec-e2212447ffaa4d1c9eb29bf8b6686ea0

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-06-21 13:55 UTC, arnab-p requested changes

2022-06-21 13:55 UTC, arnab-p commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> +| `client_id`         |  from `externalID` `ga4ClientId`  or `messageId` or `anonymousId` |
```suggestion
| `client_id`         |  from `externalID` `ga4ClientId`  or `anonymousId` or `messageId` |
```

`messageId` comes at the last in precedence

2022-06-21 14:27 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> +| `client_id`         |  from `externalID` `ga4ClientId`  or `messageId` or `anonymousId` |
should we add "in that specific order" after `messageId` to explicitly clarify the order of precedence?

2022-06-21 14:29 UTC, ishachopra0401 commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> +| `client_id`         |  from `externalID` `ga4ClientId`  or `messageId` or `anonymousId` |
Understood!

2022-06-22 11:07 UTC, akashrpo commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the e
```suggestion
- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the existing ones. When enabled and if it's a new user, you also need to enter the following details:
```

2022-06-22 11:32 UTC, akashrpo commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> +    <td><code class="inline-code">add_payment_info</code></td>
Group -> join_group won't be present in the list of e-commerce mapping as it has been moved to a separate group call.

2022-06-22 11:46 UTC, akashrpo commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
> +    <td rowspan="4">Promotion Viewed<br />Promotion Clicked</td>
In Products Searched let's provide `properties.query`

2022-06-23 10:22 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode.mdx
>  ## E-commerce
```suggestion
## E-commerce event tracking
```

2022-06-23 10:23 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Enable Server Side Identify**: Enable this setting to fire an <Link to="/rudderstack-api/api-specification/rudderstack-spec/identify/">`identify`</Link> call.
```suggestion
- **Enable Server Side Identify**: Enable this setting to make an <Link to="/rudderstack-api/api-specification/rudderstack-spec/identify/">`identify`</Link> call.
```

2022-06-23 10:24 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +  If enabled, you can set the following:
```suggestion
If **Enable Server Side Identify** setting is enabled, you can also configure the following settings:
```

2022-06-23 10:24 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +  If enabled, you can set the following:
Clarified a bit - lmk if it makes sense.

2022-06-23 10:25 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Trait to differentiate between new or existing user**: Enter a trait key to determine whether its a new or an existing user.
```suggestion
- **Trait to differentiate between new or existing user**: Enter a trait key to determine whether a user is new or an existing user.
```

2022-06-23 10:26 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Trait key for the 'method' parameter in Login or Signup event**: Enter the trait key to pass the `method` parameter in `login` or `sign_up` event.
```suggestion
- **Trait key for the 'method' parameter in Login or Signup event**: Enter the trait key to pass the `method` parameter in the `login` or `sign_up` event.
```

2022-06-23 10:27 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the e
Can we present this bit as an info block?

```
Note that `generate_lead` will only be fired for new users and not for the existing ones.
```

2022-06-23 10:27 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the e
```suggestion
- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the existing ones. When enabled in case of a new user, you also need to enter the following details:
```

2022-06-23 10:27 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +  - **Value - traits for lead generation**: Enter the value key to pass the `value` parameter for `generate_lead` event.
```suggestion
  - **Value - traits for lead generation**: Enter the value key to pass the `value` parameter for the `generate_lead` event. 
```

2022-06-23 10:28 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +  - **Currency - traits for lead generation**: Enter the currency key to pass the `currency` parameter for `generate_lead` event.
```suggestion
  - **Currency - traits for lead generation**: Enter the currency key to pass the `currency` parameter for the `generate_lead` event. 
```

2022-06-23 10:28 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +Refer to <Link to="/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode/#identify"><code class="inline-code">identify</code> call payload</Link> for more information.
```suggestion
Refer to the <Link to="/destinations/analytics/google-analytics-4/google-analytics-4-cloud-mode/#identify"><code class="inline-code">identify</code> call payload</Link> for more information.
```

2022-06-23 10:36 UTC, ishachopra0401 commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the e
Actually, this means when both conditions are true:
- enabled
- new user

lmk if that makes sense

2022-06-23 10:44 UTC, ameypv-rudder commented on docs/destinations/analytics/google-analytics-4/setting-up-google-analytics-4-in-rudderstack.mdx
> +- **Send 'generate_lead' event for 'identify' event**: Enable this setting to send a `generate_lead` event for a new user. Note that `generate_lead` will only be fired for new users and not for the e
yeah - i had made the suggestion assuming the same. If you think the current sentence is more understandable, we can retain it.

2022-06-23 10:52 UTC, ameypv-rudder approved these changes

2022-06-23 11:21 UTC, arnab-p approved these changes

2022-06-23 11:23 UTC, merged