Contextual fields combine for SDKs
rudderlabs/rudderstack-docs pull request #743
Opened 2022-07-11 11:14 UTC by ishachopra0401

## Description of the change

https://www.notion.so/rudderstacks/Common-fields-update-6145016ebe2340928d82641b879815ff

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-07-11 11:26 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
> +| `location.speed` | - | - | - |
@saikumarrs these 3 `location` fields are not collected for any of the SDKs, should we remove them?

2022-07-11 12:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `location.speed` | - | - | - |
Makes sense.

2022-07-11 12:42 UTC, pallabmaiti requested changes

2022-07-11 12:42 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
> +| `device.type`      | -   | Yes | -   |
```suggestion
| `device.type`      | -   | Yes | Yes   |
```

2022-07-11 12:42 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
> +| `ip` | - | Yes | Yes |
```suggestion
| `ip` | - | Yes | - |
```

2022-07-11 12:42 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.bluetooth` | - | Yes | - |
```suggestion
| `network.bluetooth` | - | Yes | Yes | 
```

2022-07-11 17:36 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `app.build`        | -   | Yes | Yes |
@MoumitaM This is not true. We only set default values for those fields, and they are not the actual application information.

2022-07-11 17:37 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `screen.density` | - | Yes | - |
Adding to that, we have `innerHeight` and `innerWidth` too. @MoumitaM, check if there are any such fields in the SDK.

2022-07-11 17:42 UTC, MoumitaM commented on docs/event-spec/standard-events/common-fields.mdx
> +| `app.build`        | -   | Yes | Yes |
Yes, since we fill up these values I thought of adding it. @ishachopra0401 ignore this.

2022-07-12 09:23 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
> +| `screen.density` | - | Yes | - |
@MoumitaM Can you please provide details related to these additional fields?

2022-07-13 06:00 UTC, MoumitaM requested changes

2022-07-13 06:00 UTC, MoumitaM commented on docs/event-spec/standard-events/common-fields.mdx
> +| `screen.width` | Yes | Yes | Yes |
```suggestion
| `screen.width` | Yes | Yes | Yes |
| `screen.innerWidth` | Yes |   -   |   -   |
| `screen.innerHeight` | Yes |   -   |   -   |
```

2022-07-13 06:00 UTC, MoumitaM commented on docs/event-spec/standard-events/common-fields.mdx
> +| `page.referrer` | Yes | - |  - |
```suggestion
| `page.initial_referrer` | Yes | - |  - |
| `page.initial_referring_domain` | Yes | - |  - |
| `page.referrer` | Yes | - |  - |
| `page.referring_domain` | Yes | - |  - |
```

2022-07-13 06:00 UTC, MoumitaM commented on docs/event-spec/standard-events/common-fields.mdx
> +| `screen.density` | - | Yes | - |
Check out the below suggestions.

2022-07-14 07:04 UTC, MoumitaM approved these changes

2022-07-14 11:43 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +For iOS SDK V1.6.3 and above, the bluetooth status is not collected in the <code class="inline-code">network.bluetooth</code> field as it’s a run time permission.
```suggestion
For Android SDK V1.6.0 and above, the Bluetooth status is collected in the <code class="inline-code">network.bluetooth</code> field only if the Bluetooth permission is present in the app.
For iOS SDK V1.6.3 and above, the Bluetooth status is not collected in the <code class="inline-code">network.bluetooth</code> field as it’s a run time permission.
```

2022-07-14 11:46 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
>  ```json
I'd add two different example payloads for Android and iOS SDKs.

2022-07-14 12:54 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
>  ```json
done

2022-07-18 13:29 UTC, saikumarrs requested changes

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +  "anonymousId": "7e22166a4dab652f",
The example anonymous ID does not look real. Please fix other examples too in this page.

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +      "name": "com.rudderstack.javascript.sdk.core",
This is incorrect.

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +      "version": "1.0.0"
Use `2.9.1` as it's the latest version.

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +    "screen": { "density": 420, "height": 1794, "width": 1080, "innerHeight": 200, "innerWidth": 100 },
Formatting issue.

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.bluetooth` | - | Yes (if permission is granted) | No | Bluetooth information about the network connection. |
`Bluetooth information about the network connection.` - @pallabmaiti, does this make sense? "about the network connection"

2022-07-18 13:29 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.wifi` | - | Yes | Yes | Wifi information about the network connection. |
```suggestion
| `network.wifi` | - | Yes | Yes | WiFi information about the network connection. |
```

2022-07-19 05:36 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
> +  "anonymousId": "7e22166a4dab652f",
@saikumarrs Can you please suggest a sample one?

2022-07-19 05:36 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
> +      "name": "com.rudderstack.javascript.sdk.core",
@saikumarrs Please suggest what should go here instead

2022-07-21 17:08 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +      "name": "com.rudderstack.javascript.sdk.core",
`RudderLabs JavaScript SDK`

2022-07-22 02:22 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.bluetooth` | - | Yes (if permission is granted) | No | Bluetooth information about the network connection. |
Right @saikumarrs it doesn't make sense. @ishachopra0401 for iOS, it will be `-`

2022-07-22 02:22 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
> +      "name": "com.rudderstack.iOS.sdk.core",
For iOS, `rudder-ios-library`

2022-07-22 02:22 UTC, pallabmaiti commented on docs/event-spec/standard-events/common-fields.mdx
>  {
Here is a sample JSON:
`
{
        "messageId": "1643629072-8ce81faf-7489-4508-b21b-659e81510991",
        "anonymousId": "anonymous_id",
        "userId": "new_user_id",
        "channel": "mobile",
        "event": "Application Installed",
        "context": {
            "screen": {
                "density": 3,
                "width": 844,
                "height": 390
            },
            "os": {
                "name": "iOS",
                "version": "15.2"
            },
            "locale": "en-US",
            "app": {
                "version": "1.0",
                "namespace": "com.rudderstack.ios.test.objc",
                "name": "RudderSampleAppObjC",
                "build": "1"
            },
            "device": {
                "attTrackingStatus": 0,
                "manufacturer": "Apple",
                "id": "42f0686d-564d-4e2d-815c-a9380dd8b70f",
                "model": "iPhone",
                "adTrackingEnabled": true,
                "type": "iOS",
                "token": "your_device_token",
                "advertisingId": "advertisement_Id",
                "name": "iPhone 12"
            },
            "traits": {
                "id": "new_user_id",
                "anonymousId": "anonymous_id",
                "userId": "new_user_id",
                "firstname": "First Name"
            },
            "library": {
                "name": "rudder-ios-library",
                "version": "1.5.0"
            },
            "timezone": "Asia\/Kolkata",
            "network": {
                "bluetooth": false,
                "wifi": true,
                "carrier": "unavailable",
                "cellular": false
            },
            "externalId": [{
                "type": "brazeExternalId",
                "id": "some_external_id_1"
            }]
        },
        "originalTimestamp": "2022-01-31T11:37:52.481Z",
        "properties": {
            "version": "1.0"
        },
        "type": "track",
        "integrations": {
            "All": true
        },
        "sentAt": "2022-01-31T11:38:08.731Z"
    }
`

2022-07-22 12:02 UTC, pallabmaiti approved these changes

2022-07-24 16:34 UTC, saikumarrs commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.bluetooth` | - | Yes (if permission is granted) | No | Bluetooth information about the network connection. |
I meant "about the network connection". How's Bluetooth connected to the network?

2022-07-25 02:50 UTC, ishachopra0401 commented on docs/event-spec/standard-events/common-fields.mdx
> +| `network.bluetooth` | - | Yes (if permission is granted) | No | Bluetooth information about the network connection. |
@saikumarrs: I had a discussion with @pallabmaiti and have modified the description to "Bluetooth information" only.

2022-07-25 08:01 UTC, ameypv-rudder commented on docs/event-spec/standard-events/common-fields.mdx
> +The contextual fields give additional useful context about a particular event. The following table lists all the contextual fields with their detailed description:
```suggestion
The contextual fields give additional context about a particular event. The following table lists all the contextual fields with their detailed description:
```

2022-07-25 08:02 UTC, ameypv-rudder commented on docs/event-spec/standard-events/common-fields.mdx
> +<strong>All of the above contextual fields are not automatically collected by the RudderStack SDKs.</strong> Refer to the following section for more information on which SDK automatically populates w
```suggestion
<strong>All of the above contextual fields are not automatically collected by the RudderStack SDKs.</strong> Refer to the following section for more information on the contextual fields automatically populated by the RudderStack SDKs.
```

2022-07-25 08:03 UTC, ameypv-rudder commented on docs/event-spec/standard-events/common-fields.mdx
> +For iOS SDK V1.6.3 and above, the Bluetooth status is not collected in the <code class="inline-code">network.bluetooth</code> field as it’s a run time permission.
```suggestion
For iOS SDK V1.6.3 and above, the Bluetooth status is not collected in the <code class="inline-code">network.bluetooth</code> field as it’s a run-time permission.
```

2022-07-25 08:04 UTC, ameypv-rudder approved these changes
Made some minor suggestions, but LGTM overall!

2022-07-25 08:24 UTC, merged