HubSpot V2 doc
rudderlabs/rudderstack-docs pull request #786
Opened 2022-07-27 10:35 UTC by ishachopra0401

## What do these changes do?

New doc for HubSpot V2 and updates in the older hubSpot doc

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

## Notion ticket link

https://www.notion.so/rudderstacks/HubSpot-v2-documentation-b1dd4690495b49f38078c916ddec501c

2022-08-02 07:01 UTC, shrouti1507 requested changes
Please add permission information for custom behavorial event that has been mentioned

2022-08-02 07:01 UTC, shrouti1507 commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +
To use custom behavorial events, one needs to opt for the private app access token only. And, private app must have permission  : `analytics.behavioral_events.send ` @akashrpo please confirm

2022-08-02 11:06 UTC, shrouti1507 commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +
Hi, sorry to go to and fro here, `To use custom behavorial events, one needs to opt for the private app access token only.` <-- this information needed to be deleted. We can send custom behavioral events with an API key as well

2022-08-02 11:15 UTC, shrouti1507 approved these changes

2022-08-02 12:08 UTC, akashrpo commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +
We can use custom behavioral events for both the Authorisation Type.
![image](https://user-images.githubusercontent.com/64877812/182371060-f7904847-d298-4401-ac84-074abeb2a9f6.png)

2022-08-02 12:11 UTC, utsabc commented on docs/destinations/streaming-destinations/hubspot.mdx
>  A sample `identify` call for HubSpot CRM custom object is shown below:
Can we remove this custom objects section its planned as part of next release

2022-08-02 12:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +description: Step-by-step guide on sending your event data from RudderStack to HubSpot using the new API
```suggestion
description: Step-by-step guide on sending your event data from RudderStack to HubSpot using the new HubSpot API.
```

2022-08-02 12:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +description: Step-by-step guide on sending your event data from RudderStack to HubSpot using the new API
As per our discussion, highlighting in the meta itself for clarity and differentiation.

2022-08-02 12:28 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +Refer to the <Link to="#faq">FAQ</Link> section to know where to get the HubSpot access token.
```suggestion
Refer to the <Link to="#faq">FAQ</Link> section for more information on getting the HubSpot access token.
```

2022-08-02 12:29 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +- **API Version**: Select **New API** from the dropdown.
```suggestion
- **API Version**: Select **New API (v3)** from the dropdown.
```

2022-08-02 12:29 UTC, utsabc requested changes

2022-08-02 12:29 UTC, utsabc commented on docs/destinations/streaming-destinations/hubspot.mdx
>  A sample `identify` call for HubSpot CRM custom object is shown below:
> Can we remove this custom objects section its planned as part of next release

2022-08-02 12:30 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/hubspot.mdx
>  A sample `identify` call for HubSpot CRM custom object is shown below:
@utsabc this is the existing Hubspot doc (legacy API), just confirming if this will be released later in the next release?

2022-08-02 12:31 UTC, utsabc commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +- **Map your Event Property**: Enter the RudderStack and HubSpot event properties you want to map for the above-mentioned custom behavioral events. You can specify multiple properties for a single ev
Can we elaborate this point this is not giving full context of what should be done.
You can refer this loom demo video on how we are using this

2022-08-02 12:31 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +The **API Key (deprecating soon)** authorization type allows you to create custom applications using HubSpot's APIs.
```suggestion
The **API Key (deprecating soon)** authorization type lets you create custom applications using HubSpot's APIs.
```

2022-08-02 12:31 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +HubSpot API keys will be deprecated soon. Refer to <Link to="https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key">HubSpot documentation</Link> for more information.
```suggestion
This authorization type will be deprecated soon. Refer to <Link to="https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key">HubSpot documentation</Link> for more information.
```

2022-08-02 12:33 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +- **API Version**: Select **New API** from the dropdown.
```suggestion
- **API Version**: Select **New API (v3)** from the dropdown.
```

2022-08-02 12:34 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +The below settings are only applicable for the **Private Apps** authorization type:
```suggestion
The below settings are only applicable for the <Link to="#private-apps-authorization-type">**Private Apps**</Link> authorization type:
```

2022-08-02 12:36 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +Refer to the <Link to="https://developers.hubspot.com/docs/api/analytics/events">custom behavioral events</Link> section to know more about them.
```suggestion
Refer to the <Link to="https://developers.hubspot.com/docs/api/analytics/events">Custom Behavioral Events</Link> guide for more information.
```

2022-08-02 12:37 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +RudderStack sends the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to check if a contact exists, if yes, it performs the update through the new update endpoints.
```suggestion
RudderStack sends the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to check if a contact exists in HubSpot. If it does, RudderStack performs the update through the new update endpoints.
```

2022-08-02 12:39 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +RudderStack sends the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to check if a contact exists, if yes, it performs the update through the new update endpoints.
"If it does, RudderStack performs the update through the new update endpoints."

can we simplify this to "If it does, RudderStack updates the user with the new information. Otherwise, it creates a new user." cc @shrouti1507 @akashrpo

2022-08-02 12:41 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +To associate a `track` call with a user, you need to specify the user's `email` under `context.traits`. Also, RudderStack associates the `track` events with the same user after an `identify` request
@shrouti1507 @akashrpo For HubSpot, should `identify` be mandatorily called before `track` or is it optional? cc @ishachopra0401

2022-08-02 12:43 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +Refer to the <Link to="https://developers.hubspot.com/docs/api/analytics/events">custom behavioral events</Link> section to know more about them.
would it be helpful to link to our own section on Custom behavioral events here, instead of redirecting to HubSpot docs?

2022-08-02 12:44 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +Refer to the <Link to="https://developers.hubspot.com/docs/api/analytics/events">custom behavioral events</Link> section to know more about them.
```suggestion
Refer to the <Link to="#custom-behavioral-events">Custom behavioral events</Link> section below for more information.
```

2022-08-02 12:45 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot.mdx
> +description: Step-by-step guide on sending your event data from RudderStack to HubSpot using the legacy API
```suggestion
description: Step-by-step guide on sending your event data from RudderStack to HubSpot using the legacy API.
```

2022-08-02 12:46 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot.mdx
> +HubSpot API keys will be deprecated soon. Refer to <Link to="https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key">HubSpot documentation</Link> for more information.
```suggestion
This authorization type will be deprecated soon. Refer to <Link to="https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key">HubSpot documentation</Link> for more information.
```

2022-08-02 12:46 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot.mdx
> +- **API Key**: Enter your HubSpot API key. This field is mandatory to send data to HubSpot via the RudderStack cloud mode.
```suggestion
- **API Key**: Enter your HubSpot API key. This field is mandatory to send data to HubSpot via the RudderStack <Link to="/destinations/rudderstack-connection-modes/#cloud-mode">cloud mode</Link>.
```

2022-08-02 12:47 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot.mdx
> +Refer to the <Link to="#faq">FAQ</Link> section to know where to get the Hub ID and API Key.
```suggestion
Refer to the <Link to="#faq">FAQ</Link> section for more information on obtaining the Hub ID and API Key.
```

2022-08-02 13:01 UTC, utsabc commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +- **Map your Event Property**: Enter the RudderStack and HubSpot event properties you want to map for the above-mentioned custom behavioral events. You can specify multiple properties for a single ev
Apologies @ishachopra0401 missed it
https://www.loom.com/share/1eff601602c143dfb53f17a0487a6da6

2022-08-02 13:03 UTC, utsabc commented on docs/destinations/streaming-destinations/hubspot.mdx
>  A sample `identify` call for HubSpot CRM custom object is shown below:
Yeah it was added long back but this functionality was never added. We are working on addressing it

2022-08-02 13:11 UTC, akashrpo commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +- **Map your Event Property**: Enter the RudderStack and HubSpot event properties you want to map for the above-mentioned custom behavioral events. You can specify multiple properties for a single ev
Custom Behavioural Events - 10:40

2022-08-02 13:13 UTC, akashrpo commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +RudderStack sends the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to check if a contact exists, if yes, it performs the update through the new update endpoints.
Looks good

2022-08-02 13:18 UTC, akashrpo commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +To associate a `track` call with a user, you need to specify the user's `email` under `context.traits`. Also, RudderStack associates the `track` events with the same user after an `identify` request
It is not mandatory however if there is no contact in HS then there won't be any association of events as we won't have any identifier but still the track will go through. https://developers.hubspot.com/docs/api/analytics/events

2022-08-03 13:16 UTC, akashrpo approved these changes
LGTM

2022-08-03 15:16 UTC, utsabc approved these changes

2022-08-04 05:26 UTC, ameypv-rudder approved these changes

2022-08-04 05:31 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/hubspot-v2.mdx
> +RudderStack sends the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to check if a contact exists, if yes, it performs the update through the new update endpoints.
@ishachopra0401 think we missed this update.

"If yes, RudderStack updates the user with the new information. Otherwise, it creates a new user." -- we need to specify the new user creation bit as well.

2022-08-04 05:41 UTC, merged