Improved Code Snippets across Mobile SDK's docs
rudderlabs/rudderstack-docs pull request #787
Opened 2022-07-27 17:10 UTC by desusai7

## What do these changes do?

> Improved Code Snippets across Mobile SDK's docs.

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

## Notion ticket link

> Add a link to the Notion ticket.

2022-07-28 04:20 UTC, ameypv-rudder commented on docs/sources/sdks/rudderstack-unity-sdk.mdx
>  // Build your config
```suggestion
// Building your config
```

2022-07-28 07:11 UTC, arnab-p requested changes

2022-07-28 07:11 UTC, arnab-p commented on docs/sources/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
>  RudderLogger.init(RudderLogger.VERBOSE);
@desusai7 We should not ask to initialize the SDK with VERBOSE logging

2022-08-01 09:56 UTC, ameypv-rudder commented on docs/sources/sdks/rudderstack-flutter-sdk/flutter-v1.mdx
>  RudderLogger.init(RudderLogger.VERBOSE);
```suggestion
```

2022-08-01 09:57 UTC, ameypv-rudder commented
As discussed, @desusai7 and team will verify all the code snippets across the SDK docs.

2022-12-29 14:28 UTC, closed without merging

2022-12-29 14:28 UTC, pfd commented
Will revisit in the new docs framework if necessary