OneSignal doc
rudderlabs/rudderstack-docs pull request #790
Opened 2022-07-28 08:26 UTC by ishachopra0401

## What do these changes do?

New doc for OneSignal integration

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-03 10:18 UTC, ItsSudip requested changes

2022-08-03 10:18 UTC, ItsSudip commented on docs/destinations/streaming-destinations/onesignal.mdx
> +| `anonymousId` | `external_user_id` | Optional |
We are adding a groupId tag and setting the value as the value of groupId. Apart from that, we are adding all the group call traits to tags similar to track call properties.

2022-08-03 10:18 UTC, ItsSudip commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- One for the browser (by default)
We are not creating the device for browsers only. We are also adding device from the data of integrations object and depending on the context.device data. So it is also possible to add device of ios and android types. When we are setting deviceType as ios or android, we are setting device identifier as device.token, one can set this token for both [android](https://www.rudderstack.com/docs/sources/sdks/rudderstack-android-sdk/#setting-the-android-device-token) and [ios](https://www.rudderstack.com/docs/sources/sdks/rudderstack-ios-sdk/ios-v2/#setting-the-device-token-for-push-notifications). And if token is not available we are setting device.id as identifier. But it is recommended to send token only for push notifications.

2022-08-03 11:08 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/onesignal.mdx
> +| `anonymousId` | `external_user_id` | Optional |
@ItsSudip I see these are being updated in the research spec, let me know when it's finalized. I'll pick these mappings up.

2022-08-03 13:05 UTC, ItsSudip commented on docs/destinations/streaming-destinations/onesignal.mdx
> +                    identifier: ""
7abcd558f29d0b1f048083e2834ad8ea4b3d87d8ad9c088b33c132706ff445f0

2022-08-03 13:12 UTC, ItsSudip commented on docs/destinations/streaming-destinations/onesignal.mdx
> +    email: "alex@example.com"
Updated.

2022-08-04 09:33 UTC, ItsSudip approved these changes

2022-08-04 10:32 UTC, ujjwal-ab approved these changes

2022-08-04 12:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +[OneSignal](https://onesignal.com/) is a popular service which helps in driving customer engagement with multi-channel messaging across web and mobile push notifications, in-app messages, SMS, and em
```suggestion
[OneSignal](https://onesignal.com/) is a popular service that helps you drive customer engagement with multi-channel messaging across web and mobile push notifications, in-app messages, SMS, and email subscribers.
```

2022-08-04 12:23 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +For more information on finding the OneSignal App Id, refer to the <a href="#faq">FAQ</a> section below.
```suggestion
For more information on finding the OneSignal App Id, refer to the <Link to="#faq">FAQ</Link> section below.
```

2022-08-04 12:41 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- **Toggle on to create a device using email**: Enable this setting to create a device using email.
@ujjwal-ab @ItsSudip can we rename this setting to `Add a device` in the web app to be consistent with the OneSignal feature? Reference: https://documentation.onesignal.com/reference/add-a-device 

cc @ishachopra0401

2022-08-04 12:46 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- **Allowed Property List**: Enter the properties you want to add as device <Link to="https://documentation.onesignal.com/docs/add-user-data-tags">tags</Link>, if present in the payload.
```suggestion
- **Allowed Property List**: Enter the properties you want to add as the device <Link to="https://documentation.onesignal.com/docs/add-user-data-tags">tags</Link>, if present in the payload. 
```

2022-08-04 12:47 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The properties mentioned under <strong>Allowed Property List</strong> are considered only for the <code class="inline-code">track</code>  and <code class="inline-code">group</code> calls.
```suggestion
RudderStack considers the properties mentioned under <strong>Allowed Property List</strong> only for the <code class="inline-code">track</code> and <code class="inline-code">group</code> calls.
```

2022-08-04 12:48 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +You can make an <Link to="/event-spec/standard-events/identify">`identify`</Link> call to add a new device to OneSignal App. However, if a device is already registered with the specified identifier,
```suggestion
You can make an <Link to="/event-spec/standard-events/identify">`identify`</Link> call to add a new device to your OneSignal App. However, if a device is already registered with the specified identifier, then it will update the existing device's record.
```

2022-08-04 12:48 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +You can make an <Link to="/event-spec/standard-events/identify">`identify`</Link> call to add a new device to OneSignal App. However, if a device is already registered with the specified identifier,
Removing the last bit as we already say that in the first sentence.

2022-08-04 12:56 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The `anonymoysId` is added as a tag with key as `anonymousId` and value as `anonymousId`'s value.
```suggestion
<div class="infoBlock">
RudderStack adds the <code class="inline-code">anonymousId</code> as a tag with the key as <code class="inline-code">anonymousId</code> along with the corresponding value.
</div>
```

2022-08-04 12:59 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +You can create multiple devices in a single `identify` call:
@ishachopra0401 Should we have a separate sub-section for this?

2022-08-04 13:00 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- For browser, RudderStack maps the `device_type` from the browser name and device type mapping as explained in the below code snippet. The `anonymousId` is set as an `identifier` depending upon the
```suggestion
- For the browser, RudderStack maps the `device_type` from the browser name and device type mapping as explained in the below code snippet. It sets the `anonymousId` as an `identifier` depending upon the browser name. 
```

2022-08-04 13:00 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +    You can override the device type mapping mentioned above or set any other device type by providing the `deviceType` and `identifier` in the `integrations` object, as shown:
```suggestion
You can override the above-mentioned device type mapping or set any other device type by providing the `deviceType` and `identifier` in the `integrations` object, as shown:
```

2022-08-04 13:02 UTC, ujjwal-ab commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- **Toggle on to create a device using email**: Enable this setting to create a device using email.
Ya, it's updated now in webapp. We can update in the doc too and can replace it with.
`Toggle on to add a device using email`
`Toggle on to add a device using phone number`

2022-08-04 13:05 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- For iOS and Android, the `device_type` is taken from the `context.device.type` and is mapped with the `device_type` value from the mappings mentioned above. The `context.device.token`/`context.devi
```suggestion
- For iOS and Android, RudderStack takes the `device_type` from the `context.device.type` field and maps it with the `device_type` value from the above-mentioned mappings. The `context.device.token`/`context.device.id` is set as an `identifier`. 
```

2022-08-04 13:05 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- For iOS and Android, the `device_type` is taken from the `context.device.type` and is mapped with the `device_type` value from the mappings mentioned above. The `context.device.token`/`context.devi
@ujjwal-ab @ItsSudip please confirm if it should be `deviceType` or `device_type`. cc @ishachopra0401

2022-08-04 13:07 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> + It is recommended to send <code class="inline-code">device.token</code> for push notifications.
```suggestion
It is recommended to send <code class="inline-code">device.token</code> for push notifications.
```

2022-08-04 13:08 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +    RudderStack maps the following device types by default:
```suggestion
RudderStack maps the following device types by default:
```

2022-08-04 13:09 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- For email and SMS, enable the **Toggle on to create a device using email** and **Toggle on to create a device using phone number** settings in the RudderStack dashboard as well as send their data (
```suggestion
- For email and SMS, enable the **Toggle on to create a device using email** and **Toggle on to create a device using phone number** settings in the RudderStack dashboard and send their data (`email` or `phone`) in the event payload.
```

2022-08-04 13:09 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +### Property mapping
```suggestion
### Supported mappings
```

2022-08-04 13:10 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The following table details the mappings between RudderStack and OneSignal **optional** properties:
```suggestion
The following table details the mappings between the **optional** RudderStack and OneSignal properties:
```

2022-08-04 13:12 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The <Link to="/event-spec/standard-events/track">`track`</Link> call can be used to update an existing device's tags in one of your OneSignal apps using the `external_user_id`. All devices containing
```suggestion
You can use the <Link to="/event-spec/standard-events/track">`track`</Link> to update an existing device's tags in your OneSignal apps using the `external_user_id` parameter. All devices containing the particular `external_user_id` are updated simultaneously.
```

2022-08-04 13:12 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +While updating a device tag, any key inside a tag can be deleted by providing the key value as an empty string.
```suggestion
While updating a device tag, you can delete any key inside a tag by providing the key value as an empty string.
```

2022-08-04 13:12 UTC, ujjwal-ab commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- For iOS and Android, the `device_type` is taken from the `context.device.type` and is mapped with the `device_type` value from the mappings mentioned above. The `context.device.token`/`context.devi
We are accepting `deviceType` in the integrations object and is mapped and send to OneSignal as `device_type`.

2022-08-04 13:13 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +```
```

rudderanalytics.track('Add to cart', {
  purchased_item: "Shirt",
  brand: "Zara"
});
```

Can we use the above beautified code?

2022-08-04 13:17 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The <Link to="/event-spec/standard-events/group">`group`</Link> call can be used to group the devices having device tags using  the `groupId`.
```suggestion
You can use the <Link to="/event-spec/standard-events/group">`group`</Link> call to group the devices with the device tags using the same `groupId`.
```

2022-08-04 13:17 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The <Link to="/event-spec/standard-events/group">`group`</Link> call can be used to group the devices having device tags using  the `groupId`.
@ujjwal-ab @ItsSudip @ishachopra0401 please confirm if the above change is technically sound.

2022-08-04 13:19 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/onesignal.mdx
> +All the properties added in the <strong>Allowed Property List</strong> setting in the RudderStack dashboard will be mapped inside the <code class="inline-code">tags</code> object if available in the
```suggestion
RudderStack maps all the properties added in the <strong>Allowed Property List</strong> setting in the RudderStack dashboard to the <code class="inline-code">tags</code> object if they are present in the payload. However, note that the key-value pair should be of the String data type only.
```

2022-08-04 14:11 UTC, ujjwal-ab commented on docs/destinations/streaming-destinations/onesignal.mdx
> +The <Link to="/event-spec/standard-events/group">`group`</Link> call can be used to group the devices having device tags using  the `groupId`.
LGTM

2022-08-05 06:27 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- **Toggle on to create a device using email**: Enable this setting to create a device using email.
@ujjwal-ab I dont see the changed settings in webapp. Can you please confirm?

2022-08-05 06:38 UTC, ujjwal-ab commented on docs/destinations/streaming-destinations/onesignal.mdx
> +- **Toggle on to create a device using email**: Enable this setting to create a device using email.
Ya, actually, It is just changed in the master branch. That's why not visible in the develop. Doing it for develop also.

2022-08-05 11:26 UTC, ameypv-rudder approved these changes

2022-08-05 11:30 UTC, merged