Canny source doc
rudderlabs/rudderstack-docs pull request #797
Opened 2022-08-01 08:59 UTC by ishachopra0401

## What do these changes do?

Added doc for Canny source

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-03 09:01 UTC, rohithkaza commented on docs/sources/cloud-apps/canny.mdx
> +| `object`        | `properties.objectType`        | -|
```suggestion
| `objectType`        | `properties.objectType`        | -|
```

2022-08-03 09:02 UTC, rohithkaza commented on docs/sources/cloud-apps/canny.mdx
> +| `object`        | `properties.objectType`        | -|
object-> properties mapping is missing

2022-08-03 09:38 UTC, ItsSudip requested changes

2022-08-03 09:38 UTC, ItsSudip commented on docs/sources/cloud-apps/canny.mdx
> +| `cannyId`    | `context.externalId[0].type`  |- |
'cannyId' does not belong to Canny, we are assigning the type of externalId as `cannyUserId`.

2022-08-03 10:47 UTC, ItsSudip approved these changes

2022-08-03 12:15 UTC, rohithkaza approved these changes

2022-08-03 15:45 UTC, ItsSudip approved these changes

2022-08-04 06:08 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +title: "Canny"
```suggestion
title: "Canny Source"
```

2022-08-04 06:08 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +title: "Canny"
To help with the search results.

2022-08-04 06:10 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +4. Go to your Canny account and navigate to **Settings** > **API & Webhooks** under your profile.
```suggestion
4. Go to your <a href="https://canny.io/login">Canny account</a> and navigate to **Settings** > **API & Webhooks** under your profile.
```

2022-08-04 06:11 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +RudderStack ingests the events from Canny after converting them into the RudderStack event format. It also maps the following properties from the Canny event payload to the RudderStack properties:
```suggestion
RudderStack ingests the Canny events after converting them into the RudderStack event format. It also maps the following properties from the Canny event payload to the RudderStack properties:
```

2022-08-04 06:18 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| `object`        | `properties`        | excluding `author`/`voter` from properties|
```suggestion
| `object`        | `properties`        | RudderStack excludes `author`/`voter` from the properties. |
```

2022-08-04 06:18 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| `object`        | `properties`        | excluding `author`/`voter` from properties|
Please verify if this is accurate.

2022-08-04 06:18 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| `object.author`    | `context.traits`  | excluding `userId` and `id` |
```suggestion
| `object.author`    | `context.traits`  | RudderStack excludes `userId` and `id`. |
```

2022-08-04 06:19 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| sha256 hash of(`object.voter.email`)        | `anonymousId` |Only if `userId` is not present AND `type`is `vote.created`/`vote.deleted`|
```suggestion
| sha256 hash of(`object.voter.email`)        | `anonymousId` |Only if `userId` is not present **and** `type`is `vote.created`/`vote.deleted`|
```

2022-08-04 06:19 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| sha256 hash of(`object.author.email`)        | `anonymousId` | Only if `userId` is not present |
```suggestion
| SHA-256 hash of(`object.author.email`)        | `anonymousId` | Only if `userId` is not present |
```

2022-08-04 06:19 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| sha256 hash of(`object.voter.email`)        | `anonymousId` |Only if `userId` is not present AND `type`is `vote.created`/`vote.deleted`|
```suggestion
| SHA-256 hash of(`object.voter.email`)        | `anonymousId` |Only if `userId` is not present AND `type`is `vote.created`/`vote.deleted`|
```

2022-08-04 06:20 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| sha256 hash of(`object.author.email`)        | `anonymousId` | Only if `userId` is not present |
Are the brackets required here? Just confirming.

2022-08-04 06:21 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| `object.voter.userId`    | `userId`  | Only if `type`is `vote.created`/`vote.deleted` |
```suggestion
| `object.voter.userId`    | `userId`  | Only if `type` is `vote.created`/`vote.deleted` |
```

2022-08-04 06:21 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +| `object.voter.id`        | `context.externalId[0].value` | Only if `type`is `vote.created`/`vote.deleted`|
```suggestion
| `object.voter.id`        | `context.externalId[0].value` | Only if `type` is `vote.created`/`vote.deleted`|
```

2022-08-04 06:21 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +Canny supports the following events:
```suggestion
Canny supports ingesting the following events:
```

2022-08-04 06:47 UTC, ameypv-rudder approved these changes

2022-08-04 06:56 UTC, ishachopra0401 commented on docs/sources/cloud-apps/canny.mdx
> +title: "Canny"
Should we add it in alias tag rather? search results will be catered, and consistency across all source docs will be maintained too. WDYT

2022-08-04 07:25 UTC, ameypv-rudder commented on docs/sources/cloud-apps/canny.mdx
> +title: "Canny"
Makes sense!

2022-08-05 11:31 UTC, merged