AWS Lambda documentation
rudderlabs/rudderstack-docs pull request #806
Opened 2022-08-03 07:42 UTC by ameypv-rudder

## What do these changes do?

> Documentation for the AWS Lambda destination

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-04 08:36 UTC, ameypv-rudder commented
This PR is on hold as per discussion with @sandeepdsvs. cc @ishachopra0401 @utsabc

2022-08-09 05:27 UTC, utsabc requested changes

2022-08-09 05:27 UTC, utsabc commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +  - **Event**: RudderStack invokes the lambda function asynchronously and sends the failed events to the function's dead-letter queue (if configured). For more information, refer to the <a href="http
Lets change this to `Async Invocation`
and `Sync Invocation`
@sandeepdsvs

2022-08-23 07:23 UTC, sandeepdsvs commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +  - **Event**: RudderStack invokes the lambda function asynchronously and sends the failed events to the function's dead-letter queue (if configured). For more information, refer to the <a href="http
No longer using this setting.

2022-08-23 07:39 UTC, sandeepdsvs commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +- **Secret Access Key**: Enter your secret access key.
@ameypv-rudder  Don't we need to mention `Access Key ID` and `Secret Access Key` will be disabled if `Role Based Authentication` ?

2022-08-24 06:23 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +- **Secret Access Key**: Enter your secret access key.
thanks - I've incorporated this feedback.

2022-08-24 06:37 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html">AWS documentation</a>.
```suggestion
For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html">AWS documentation</a>.
```

2022-08-24 06:39 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html">AWS documentation</a>.
@sandeepdsvs please verify if this update is accurate.

2022-08-24 06:56 UTC, sandeepdsvs commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html">AWS documentation</a>.
```suggestion
For more information on creating an IAM role in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html">AWS documentation</a>.
```

2022-08-24 10:24 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html">AWS documentation</a>.
```suggestion
For more information on creating an IAM role in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html">AWS documentation</a>.
```

2022-08-24 10:25 UTC, sandeepdsvs commented on docs/destinations/streaming-destinations/aws-lambda.mdx
> +For more information on creating an IAM user in AWS, refer to the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html">AWS documentation</a>.
👍🏼

2022-08-24 10:41 UTC, sandeepdsvs approved these changes

2022-08-24 12:10 UTC, utsabc approved these changes

2022-08-24 15:41 UTC, ishachopra0401 approved these changes

2022-08-24 15:58 UTC, merged