Canny destination doc
rudderlabs/rudderstack-docs pull request #807
Opened 2022-08-03 09:23 UTC by ishachopra0401

## What do these changes do?

Created new doc for Canny destination

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-03 11:40 UTC, ItsSudip requested changes

2022-08-03 11:40 UTC, ItsSudip commented on docs/destinations/streaming-destinations/canny.mdx
> +- If a user exists, it is updated with new data.
We can create and update a user only through identify call.

2022-08-03 11:40 UTC, ItsSudip commented on docs/destinations/streaming-destinations/canny.mdx
> +| Collect from `externalId` or <Link to="https://developers.canny.io/api-reference#retrieve_user">retrieve user</Link> API call | `voterID` | Required | String |
The key name of externalId is `cannyUserId` we have to mention that somewhere.

2022-08-04 07:56 UTC, ItsSudip requested changes

2022-08-04 07:56 UTC, ItsSudip commented on docs/destinations/streaming-destinations/canny.mdx
> +| `properties` (after removing `boardID`, `byID`, `categoryID`,`details`, `eta`, `etaPublic`, `title`, `imageURLs`)| `customFields` | Optional | Object | Ensure that you <Link to="#how-to-create-cust
for `customFields` we are looking for `customFields` in properties so need to update the mapping.
```suggestion
| `properties.customFields` | `customFields` | Optional | Object | Ensure that you <Link to="#how-to-create-custom-fields-in-canny-dashboard">create the custom fields in Canny dashboard</Link> to send the event seuccessfully.|
```

2022-08-04 11:02 UTC, ItsSudip approved these changes

2022-08-04 13:45 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +- **Mapping to trigger Canny Events for the respective Event**: Enter the event name and pick the Canny event from the dropdown to be triggered when that event is called.
```suggestion
- **Mapping to trigger Canny Events for the respective Event**: Enter the event name and choose the Canny event from the dropdown to be triggered when that event is called.
```

2022-08-04 13:46 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to <Link to="https://developers.canny.io/api-reference#create_or_update_user">create or update a user</Link>.
```suggestion
You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to <Link to="https://developers.canny.io/api-reference#create_or_update_user">create or update a user</Link> in Canny.
```

2022-08-04 13:47 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +| `originalTimestamp`/`timestamp` | `created` | Optional | Date |
Should this be in the ISO 8601 timestamp format? @ItsSudip @rohithkaza cc @ishachopra0401 we should specify this accordingly.

2022-08-04 13:50 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +The following table lists the mappings between RudderStack and Canny properties for **Create post** event:
```suggestion
The following table lists the mappings between RudderStack and Canny properties for the **Create post** event:
```

2022-08-04 13:51 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +|:---------------------|:-------------|:--------------|:--------------|:--------------|
we can drop the **Notes** column here.

2022-08-04 13:51 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +| `properties.customFields` | `customFields` | Optional | Object | Ensure that you <Link to="#how-to-create-custom-fields-in-canny-dashboard">create the custom fields in Canny dashboard</Link> to sen
```suggestion
| `properties.customFields` | `customFields` | Optional | Object | Ensure that you <Link to="#how-to-create-custom-fields-in-canny-dashboard">create the custom fields in Canny dashboard</Link> to send the event successfully.|
```

2022-08-04 13:53 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +| `properties.eta` | `eta` | Optional | String | In MM/YYYY format. Required if `etaPublic` is present. |
```suggestion
| `properties.eta` | `eta` | Required if `etaPublic` is present. | String | Should be in MM/YYYY format.  |
```

2022-08-04 13:53 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +| `properties.etaPublic` | `etaPublic` | Optional | Boolean | Required if `eta` is present. |
```suggestion
| `properties.etaPublic` | `etaPublic` | Required if `eta` is present.  | Boolean | - |
```

2022-08-04 13:54 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +The following table lists the mappings between RudderStack and Canny properties for **Create vote** event:
```suggestion
The following table lists the mappings between RudderStack and Canny properties for the **Create vote** event:
```

2022-08-04 13:55 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +### How to create custom fields in Canny Dashboard?
```suggestion
### How to create custom fields in the Canny dashboard?
```

2022-08-04 13:56 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +4. Click on **Create new Post Fields to add them to a board** in the **Fields** section.
```suggestion
4. In the **Fields** section, click on **Create new Post Fields to add them to a board**.
```

2022-08-04 13:59 UTC, ItsSudip commented on docs/destinations/streaming-destinations/canny.mdx
> +| `originalTimestamp`/`timestamp` | `created` | Optional | Date |
Yes, it should be in the ISO 8601 timestamp format.

2022-08-04 14:02 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/canny.mdx
> +| `originalTimestamp`/`timestamp` | `created` | Optional | Date |
```suggestion
| `originalTimestamp`/`timestamp` | `created` | Optional | ISO 8601 Timestamp |
```

2022-08-04 14:25 UTC, ameypv-rudder approved these changes

2022-08-04 17:53 UTC, rohithkaza commented on docs/destinations/streaming-destinations/canny.mdx
> +Also, you can retrieve the user data using `userId` or `email` and use that information to post or vote.
```suggestion
We <Link to="/event-spec/standard-events/track/">`rerieve the user`</Link> data using `userId` or `email` and use that information to create post or vote.
```

2022-08-05 03:21 UTC, ItsSudip commented on docs/destinations/streaming-destinations/canny.mdx
> +
We need to do another step:
Your Company/Dashboard -> Settings-> Boards -> [Select a Board From Dropdown] -> Create Post Form -> Add Field -> [Select a Post Field From Dropdown] -> Enter details -> Save

2022-08-05 11:31 UTC, merged