Wootric destination
rudderlabs/rudderstack-docs pull request #826
Opened 2022-08-12 09:33 UTC by ishachopra0401

## What do these changes do?

Wootric integration doc

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-16 07:42 UTC, Gauravudia commented
In Wootric destination -> Connection Settings => Password placeholder updated.
Have raised the PR [here](https://github.com/rudderlabs/rudder-webapp/pull/3288).
Please refer the attached screenshot.
<img width="671" alt="Screenshot 2022-08-16 at 1 08 32 PM" src="https://user-images.githubusercontent.com/60897972/184824445-cf2b1c91-4004-4659-8f18-fa9f2ac2e047.png">

2022-08-16 09:53 UTC, Gauravudia requested changes

2022-08-16 09:53 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +
We are only using the Create Response/ Decline API's . 
Refer [DOC](https://www.notion.so/rudderstacks/Wootric-706470e406fb493eb909b7624818e1c4#1853436e30c84e06838dfe5a2cf175d9)

2022-08-16 09:53 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +RudderStack checks the `message.integrations.Wootric.survey` field to determine whether to create a response or a decline.
we are using **message.integrations.Wootric.eventType**.
Refer [DOC](https://www.notion.so/rudderstacks/Wootric-706470e406fb493eb909b7624818e1c4#1adbeee3fd39408e9727d2917959e779)

2022-08-16 09:53 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.email`/`traits.email`/`properties.email`/`context.externalId.0.id` | `email` | Optional | String |
Phone number should be in this format => +12025550146.
We will use this value as input of User lookup by Phone number API.
Refer [DOC](https://www.notion.so/rudderstacks/Wootric-706470e406fb493eb909b7624818e1c4#9a60cddde90948b3bd44fbe8d28f32cf).

2022-08-16 10:19 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.phone`/`traits.phone`/`properties.phone` | `phone_number` | Optional, if `email` is present. | String (Phone number with country code, for example, `+1-202-555-0146`) |
This is updated, @Gauravudia

2022-08-16 10:19 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +RudderStack checks the `message.integrations.Wootric.survey` field to determine whether to create a response or a decline.
Updated.

2022-08-18 05:27 UTC, Gauravudia requested changes

2022-08-18 05:40 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +                survey: "create response",
This is done.

2022-08-18 17:52 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.email`/`traits.email`/`properties.email`/`context.externalId.0.id` | `email` | Optional | String |
yes, Updated the mapping on doc.

2022-08-19 02:44 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id`/`anonymousId` | `external_id` | Required | String |
```suggestion
    | `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id` | Required | String |
```

2022-08-19 02:44 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `traits.email`/`context.traits.email`/ `properties.email` / `context.externalId.0.id` | `email` | Required | String |
```suggestion
    | `traits.email`/`context.traits.email`/ `properties.email` | `email` | Required | String |
```

2022-08-19 02:46 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.email`/`traits.email`/`properties.email`/`context.externalId.0.id` | `email` | Optional, if `phone` is present. | String |
```suggestion
    | `context.traits.email`/`traits.email`/`properties.email` | `email` | Optional, if `phone` is present. | String |
```

2022-08-19 02:47 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.email`/`traits.email`/`properties.email`/`context.externalId.0.id` | `email` | Optional | String |
```suggestion
    | `context.traits.email`/`traits.email`/`properties.email` | `email` | Optional | String |
```

2022-08-19 12:07 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id` | Required | String |
Here InMoment property is `external_id`

2022-08-19 13:30 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id` | Required | String |
```suggestion
    | `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id` | `external_id` | Required | String |
```

2022-08-19 15:19 UTC, Gauravudia approved these changes

2022-08-22 02:59 UTC, ameypv-rudder approved these changes

2022-08-22 05:38 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/inmoment.mdx
> +RudderStack updates the user if the `external_id` field exists, otherwise creates a new one.
AFAIU, its true for `context.externalId.0.id` as well, meaning, RudderStack updates the user if the `external_id` or `context.externalId.0.id` field exists, otherwise creates a new one.

Is this correct?

2022-08-22 05:47 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/inmoment.mdx
> +RudderStack updates the user if the `external_id` field exists, otherwise creates a new one.
yes - that's what point 1 says. If `context.externalId.0.id` is absent, we look for RS `external_id` (`userId`). 

we can actually remove the line break after point 3 to avoid confusion.

2022-08-24 07:47 UTC, Gauravudia requested changes

2022-08-24 07:47 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +If the difference between the event's <code class="inline-code">timestamp</code> and <code class="inline-code">createdAt</code> is greater than 24 hours, RudderStack creates a new survey response for
If the difference between `current timestamp` and `createAt` is greater than 24 hours , Wootric creates a new survey response for the user . Otherwise , it updates the last response.
i.e. if the request is received within a 24-hour window for a same user. The last response will be updated else new response will be created

2022-08-24 07:47 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +If the difference between the event's <code class="inline-code">timestamp</code> and <code class="inline-code">createdAt</code> is greater than 24 hours, RudderStack creates a new survey decline for
If the difference between `current timestamp` and `createAt` is greater than 24 hours , Wootric creates a new survey decline for the user . Otherwise , it updates the last decline.
i.e. if the request is received within a 24-hour window for a same user. The last decline will be updated else new decline will be created

2022-08-24 07:47 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.createdAt`/`traits.createdAt` | `created_at` | Optional | Integer (UNIX timestamp) |
Data Type is `String` (UNIX timestamp)

2022-08-24 07:47 UTC, Gauravudia commented on docs/destinations/streaming-destinations/inmoment.mdx
> +    | `context.traits.createdAt`/`traits.createdAt` | `created_at` | Optional | Integer (UNIX timestamp) |
Data type is `String` (UNIX timestamp)

2022-08-24 08:20 UTC, ameypv-rudder commented
@Gauravudia any reason why we have these new implementation-related changes after the integration is already live? there have been too many back and forth in terms of documentation updates as well, as a result. Please confirm once there are no more additions/updates to the implementation and provide us with the final spec with all the necessary changes. We will pick this up after this confirmation. cc @utsabc @shrouti1507 @ishachopra0401

2022-08-25 05:35 UTC, Gauravudia commented
@ameypv-rudder As `Wootric` doesn't support `patching` at their end for user details updation.We have introduce the `patching` at our end. We are planning to release these changes in this release (this Thursday) along with some code refectoring and test cases updation. Demo video is also recorded and uploaded on research spec.

@utsabc Has approved the PR and waiting for @shrouti1507 approval.

2022-08-25 06:12 UTC, Gauravudia commented
@ameypv-rudder Transformer PR is approved and merged. We can proceed with the doc changes.l

2022-08-25 11:57 UTC, ameypv-rudder commented
@Gauravudia I've incorporated all the suggestions and changes as highlighted in the PR as well as in the spec. Kindly confirm if we're good to go here.

2022-08-25 12:11 UTC, Gauravudia approved these changes

2022-08-25 14:20 UTC, merged