SnapEngage documentation
rudderlabs/rudderstack-docs pull request #834
Opened 2022-08-17 06:54 UTC by ameypv-rudder

## What do these changes do?

> Added documentation for SnapEngage destination

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-08-17 11:58 UTC, ItsSudip requested changes

2022-08-17 11:58 UTC, ItsSudip commented on docs/destinations/streaming-destinations/snapengage.mdx
> +- **Record Live Chat Events**: Enable this setting to allow RudderStack to automatically track and send your live chat-related events to SnapEngage.
Here we are not sending any events to SnapEngage actually. Depending on some events we are making track calls to rudderstack to analyze the user based on their interaction with the chatBot. Let's say the customer sends a message through chatbot then one track call will be sent to rudderstack. Now our customers can send those events to any other destinations to analyze the user.

2022-08-17 11:58 UTC, ItsSudip commented on docs/destinations/streaming-destinations/snapengage.mdx
> +You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to set the user's email, name, and other custom fields in SnapEngage through their <a href="https://developer.s
We are only updating the email and userName.

2022-08-17 11:58 UTC, ItsSudip commented on docs/destinations/streaming-destinations/snapengage.mdx
> +If the **Record Live Chat Events** dashboard setting is enabled during the destination setup, RudderStack lets you track the Live Chat events and send them as <Link to="/event-spec/standard-events/tr
Same here we are not sending any track call to snapengage.

2022-08-17 12:28 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/snapengage.mdx
> +If the **Record Live Chat Events** dashboard setting is enabled during the destination setup, RudderStack lets you track the Live Chat events and send them as <Link to="/event-spec/standard-events/tr
Got it - I misunderstood. Will make the changes to the sections accordingly.

2022-08-18 06:33 UTC, ameypv-rudder commented
@ItsSudip @rohithkaza I've made the necessary changes to the doc. Please review.

2022-08-18 07:07 UTC, rohithkaza commented on docs/destinations/streaming-destinations/snapengage.mdx
> +If the **Record Live Chat Events** dashboard setting is enabled during the destination setup, RudderStack records the SnapEngage Live Chat events based on the user's interactions. You can then send t
Will it be more clear if we say 
"We then send them as <Link to="/event-spec/standard-events/track/">track</Link> events, so that you can view these events in other tools (connected to the same source in RudderStack), where you can analyze your Live Chat Events"
WDYT?

2022-08-18 09:59 UTC, rohithkaza approved these changes

2022-08-18 11:11 UTC, ameypv-rudder commented
@ItsSudip all the changes are incorporated. Could you please have a look and let me know if we're good to go?

2022-08-18 11:18 UTC, ItsSudip approved these changes

2022-08-24 10:19 UTC, merged