Shynet doc
rudderlabs/rudderstack-docs pull request #870
Opened 2022-09-02 08:38 UTC by ishachopra0401

## What do these changes do?

Added Shynet doc

2022-09-02 08:39 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/shynet.mdx
> +```javascript
@aashishmalik sample code required here

2022-09-02 09:16 UTC, ItsSudip requested changes

2022-09-02 09:16 UTC, ItsSudip commented on docs/destinations/streaming-destinations/shynet.mdx
> +- **Heart Beat**: Enter the time (in ms) to send a ping request. The default value is 5000 ms.
This is a device mode setting only. Can we mention it under the web SDK setting?

2022-09-02 09:16 UTC, ItsSudip commented on docs/destinations/streaming-destinations/shynet.mdx
> +| `context.page.loadTime`        | `loadTime`       | Integer |
```suggestion
| `properties.loadTime`        | `loadTime`       | Integer |
```

2022-09-02 09:16 UTC, ItsSudip commented on docs/destinations/streaming-destinations/shynet.mdx
> +The following table lists the mapping for the **required** property between RudderStack and Shynet:
I don't think there are any required fields @aashishmalik can you please confirm?

2022-09-02 09:16 UTC, ItsSudip commented on docs/destinations/streaming-destinations/shynet.mdx
> +[Shynet](https://github.com/milesmcc/shynet) is an open source web analytics tool which works without cookies and is privacy-friendly.
Shynet is a self-hosted platform, there is not any website as well. We should mention this information somewhere.

2022-09-05 06:08 UTC, ishachopra0401 commented
@aashishmalik Can you please respond to the tagged comments? As this is already released in prod, we are looking to close this asap. cc @ItsSudip

2022-09-05 07:01 UTC, aashishmalik commented on docs/destinations/streaming-destinations/shynet.mdx
> +The following table lists the mapping for the **required** property between RudderStack and Shynet:
updated doc

2022-09-05 08:25 UTC, ItsSudip approved these changes

2022-09-05 09:19 UTC, aashishmalik approved these changes

2022-09-05 10:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/shynet.mdx
> +- **Heart Beat**: This is a **device mode** only setting where you need to enter the time (in ms) to send a ping request. The default value is 5000 ms.
```suggestion
- **Heart Beat**: This is a **device mode** only setting. Enter the time (in ms) to send a ping request. The default value is 5000 ms.
```

2022-09-05 10:24 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/shynet.mdx
> +| `context.page.url`        | `location`      | Required | String |
@aashishmalik @ItsSudip in the sample snippet above, we have `loadTime` which is an optional property but not `url` which is required. Please confirm if it should be added. cc @ishachopra0401

2022-09-06 06:25 UTC, ItsSudip commented on docs/destinations/streaming-destinations/shynet.mdx
> +| `context.page.url`        | `location`      | Required | String |
Our javascript SDK automatically tracks the URL. But we should update the sample snippet with the required property.

2022-09-06 06:58 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/shynet.mdx
> +| `context.page.url`        | `location`      | Required | String |
cc @ishachopra0401

2022-09-06 08:25 UTC, ameypv-rudder approved these changes

2022-09-06 08:26 UTC, merged