Session tracking documentation
rudderlabs/rudderstack-docs pull request #885
Opened 2022-09-09 12:23 UTC by ameypv-rudder

## What do these changes do?

> Documentation for the session tracking feature in the JS, Android, and iOS SDKs

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-09-12 02:35 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +**By default, the RudderStack SDKs automatically track the user sessions**. This means that RudderStack automatically determines the start and end of a session depending on the inactivity time config
```suggestion
**By default, the above-mentioned RudderStack SDKs automatically track the user sessions**. This means that RudderStack automatically determines the start and end of a session depending on the inactivity time configured in the SDK.
```

2022-09-12 02:38 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +To disable automatic session tracking, you can set the load option `autoTrack`to `false`.
```suggestion
To disable automatic session tracking, you can set the load option `autoTrack` to `false`.
```

2022-09-12 02:40 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +This section is applicable for the <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/">JavaScript</Link>, <Link to="/sources/event-streams/sdks/rudderstack-android-sdk/">Android</Link>
```suggestion
This section is applicable for all the supported RudderStack SDKs (<Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/">JavaScript</Link>, <Link to="/sources/event-streams/sdks/rudderstack-android-sdk/">Android</Link>, and <Link to="/sources/event-streams/sdks/rudderstack-ios-sdk/">iOS</Link>).
```

2022-09-12 02:42 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +
```suggestion

<div class="infoBlock">
RudderStack also lets you start and end user sessions manually. Refer to the <Link to="#manual-session-tracking">Manual session tracking</Link> section below for more information.
</div>
```

2022-09-12 02:46 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +Every time the user interacts with the website, the SDK triggers a new event (`track`, `page`, `identify`, etc.), and resets the session expiration time by adding `timeout` (default **30 minutes**) t
```suggestion
Every time the user interacts with the website, the SDK triggers a new event (`track`, `page`, `identify`, etc.), and resets the session expiration time by adding `timeout` (default **30 minutes**) to the last received event's <Link to="/event-spec/standard-events/common-fields/#clock-skew-considerations">`timestamp`</Link>.
```

2022-09-12 02:51 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +To automatically track sessions in the Android and iOS SDK, <code class="inline-code">withTrackLifecycleEvents</code> should also be set to true. This is because RudderStack considers the <Link to="/
@pallabmaiti for the mobile SDKs, are we considering `Application Updated` event too? This was mentioned in the [spec](https://www.notion.so/rudderstacks/User-Session-Specs-Mobile-8584038dffc94b90bae3ec8877995356).

2022-09-12 02:58 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +<Tabs>
@pallabmaiti please verify the accuracy of all the code snippets.

2022-09-12 02:59 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +  .withAutomaticSessionTracking(true) // To disable automatic session tracking, set to false
@pallabmaiti In Android, we have `withAutoSessionTracking` and in iOS, we have `withAutomaticSessionTracking`. Please verify if this is accurate.

2022-09-12 03:00 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +
@pallabmaiti we need the Objective C snippet here for the timeout parameter.

2022-09-12 03:02 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +RudderStack saves the time of each received event to keep track of the last event, in case the app is force-closed or closed prematurely.
@pallabmaiti would it be accurate to simply say "RudderStack saves the time of the last received event..." or does it actually save the timestamp of **each** received event?

2022-09-12 03:03 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | RudderStack creates a new session and passes the event's `timestamp` (in ms) as the `sessionId`. |
```suggestion
| `startSession()` | RudderStack creates a new session and passes the event's `timestamp` (in ms) as the <Link to="/sources/event-streams/sdks/session-tracking/faq/#how-does-rudderstack-determine-the-sessionid">`sessionId`</Link>. |
```

2022-09-12 03:05 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +3. Finally, the SDK updates the session expiration time, that is, the last event's `timestamp` + `timeout` (default **30 minutes**).
```suggestion
3. Finally, the SDK updates the session expiration time, that is, the last event's <Link to="/event-spec/standard-events/common-fields/#clock-skew-considerations">`timestamp`</Link> + `timeout` (default **30 minutes**).
```

2022-09-12 03:06 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +<img src="../../../../assets/event-stream-sources/session-tracking-web.png" alt="Session tracking in JavaScript SDK" />
@pallabmaiti please confirm if this diagram is accurate? Also, we can have a similar flowchart for mobile SDKs too, but would need some inputs.

2022-09-12 03:07 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +- RudderStack sets the `context.sessionStart` field to `true` in the first event to indicate the start of the session.
This was mentioned in the spec, but is it specific to the JS SDK only? Or do we use this logic in the mobile SDKs too?

2022-09-12 09:21 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/faq.mdx
> +If you set the session's `timeout` to 0, RudderStack disables automatic session tracking.
Add this [info](https://www.notion.so/rudderstacks/User-Session-Specs-JS-1c25f7f907d54eca8052abef16ec2d1d#c94a0d02ecc14e2cbb10dd7cae03d429) too.

2022-09-12 09:32 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +<img src="../../../../assets/event-stream-sources/session-tracking-web.png" alt="Session tracking in JavaScript SDK" />
Updated the diagram [here](https://whimsical.com/rudderstack-overview-HB1Z5mvzeXE1eVZZDCmUCe).

2022-09-14 06:27 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> +| `sessionTimeout` | Integer | Maximum inactivity period before the session expires. | `300000 ms` |
```suggestion
| `sessionTimeout` | Integer | Maximum inactivity period before the session expires. | `300000 ms (5 mins)` |
```

2022-09-14 06:27 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +To automatically track sessions in the Android and iOS SDK, <code class="inline-code">withTrackLifecycleEvents</code> should also be set to true. This is because RudderStack considers the <Link to="/
Please include `Application Installed` also.

2022-09-14 06:27 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +```swift
```suggestion
```objectivec
```

2022-09-14 06:27 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +```objectivec
```suggestion
```swift
```

2022-09-14 06:27 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +1. RudderStack starts the session once it receives the <Link to="/event-spec/standard-events/application-lifecycle-events-spec/#application-opened">`Application Opened`</Link> or <Link to="/event-spe
Include `Application Installed`

2022-09-14 06:52 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +RudderStack saves the time of each received event to keep track of the last event, in case the app is force-closed or closed prematurely.
we've removed this.

2022-09-14 07:21 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +[builder withSessionTimeoutMillis:300000];
```suggestion
[builder withSessionTimeoutMillis:(5*60*1000)];
```

2022-09-14 07:21 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +            .withTrackLifecycleEvents(true)
`.withTrackLifecycleEvents(true)`
Remove this.

2022-09-14 07:23 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +            .withTrackLifecycleEvents(true)
```suggestion
```

2022-09-14 08:51 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +        .withTrackLifecycleEvents(true)
`withTrackLifecycleEvents`
Remove this.

2022-09-14 08:51 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +        .withTrackLifecycleEvents(true)
`withTrackLifecycleEvents`
Remove this.

2022-09-14 08:51 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `timestamp` (in ms) | RudderStack creates a new session and passes the event's `timestamp` as the <Link to="/sources/event-streams/sdks/session-tracking/faq/#how-does-rudderstack
Remove `timestamp` parameter.

2022-09-15 04:22 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `timestamp` (in ms) | RudderStack creates a new session and passes the event's `timestamp` as the <Link to="/sources/event-streams/sdks/session-tracking/faq/#how-does-rudderstack
```suggestion
| `startSession()` | - | RudderStack creates a new session and passes the event's `timestamp` as the <Link to="/sources/event-streams/sdks/session-tracking/faq/#how-does-rudderstack-determine-the-sessionid">`sessionId`</Link>. |
```

2022-09-15 04:22 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +        .withTrackLifecycleEvents(true)
```suggestion
```

2022-09-15 04:22 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +        .withTrackLifecycleEvents(true)
```suggestion
```

2022-09-15 04:46 UTC, pallabmaiti approved these changes

2022-09-16 06:13 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `sessionId` (String) | You can pass a custom `sessionId` and trigger a new user session. |
`sessionId` will be in long and minimum length of 10. Recommending to use decimal number.

2022-09-16 06:13 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +  <td><Link to="/destinations/streaming-destinations/google-analytics-4/">Google Analytics 4</Link></td>
Remove GA4.

2022-09-16 06:28 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +  <td><Link to="/destinations/streaming-destinations/google-analytics-4/">Google Analytics 4</Link></td>
Incorporated.

2022-09-16 06:28 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `sessionId` (String) | You can pass a custom `sessionId` and trigger a new user session. |
Added this information.

2022-09-16 06:39 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `sessionId` (**Long** integer with minimum length of 10 characters) <br /><br /> It is recommended to use a decimal number. | You can pass a custom `sessionId` and trigger a new
```suggestion
| `startSession()` | `sessionId` (**Long** integer with minimum length of 10 characters). **It is recommended to use a decimal number**. | You can pass a custom `sessionId` and trigger a new user session. |
```

2022-09-16 06:44 UTC, pallabmaiti approved these changes

2022-09-20 05:11 UTC, MoumitaM commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +```
As the feature is enabled by default. We do not need this snippet here. Rather move it after line 48 and set `autoTrack: false`.

2022-09-20 05:13 UTC, MoumitaM requested changes
Please address the comment.

2022-09-20 05:58 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +```
this is done.

2022-09-20 06:02 UTC, MoumitaM approved these changes

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +In case of the JavaScript SDK, RudderStack considers the <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/">SDK initialization</Link> to be the start of the session.
```suggestion
In case of the JavaScript SDK, RudderStack considers the <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/">SDK initialization</Link> as the start of a user session.
```

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +## Session tracking flows
```suggestion
## Session tracking flow
```

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +For more information on how session tracking works in the JavaScript SDK, refer to the <Link to="#session-tracking-flows">Session tracking flows</Link> section below.
```suggestion
For more information on how session tracking works in the JavaScript SDK, refer to the <Link to="#session-tracking-flow">Session tracking flow</Link> section below.
```

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +For more information on how session tracking works in the mobile SDKs, refer to the <Link to="#session-tracking-flows">Session tracking flows</Link> section below.
```suggestion
For more information on how session tracking works in the mobile SDKs, refer to the <Link to="#session-tracking-flow">Session tracking flow</Link> section below.
```

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/faq.mdx
> +RudderStack passes the event's `timestamp` (in milliseconds) as the `sessionId`. It **does not** attach any user information to this `sessionId` so that they cannot be traced back or identified only
```suggestion
RudderStack passes the event's `timestamp` (in milliseconds) as the `sessionId`.
```

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/session-tracking/faq.mdx
> +### What is the `timeout` option in automatic session tracking?
As discussed, can remove this

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> +By default, the Android SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time configure
We can add that
- `withTrackLifecycleEvents` should also be set to `true`
-  set `withAutoSessionTracking` to `false` to disable session tracking

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +By default, the iOS SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time configured in
We can add that
- `withTrackLifecycleEvents` should also be set to `true`
-  set `withAutoSessionTracking` to `false` to disable session tracking

2022-09-20 06:55 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +By default, the JavaScript SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time config
We can add that
-  set `withAutoSessionTracking` to `false` to disable session tracking

2022-09-20 07:37 UTC, MoumitaM commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +
Suggestion:
We can add the properties here. So, that customer will understand what to expect from this feature.

`Expect the below properties in the event context:`
```
1. sessionId(number): Session id 
2. sessionStart(boolean): This property will only be there for the first event of the session. 
```

2022-09-20 07:50 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +By default, the iOS SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time configured in
Added this information.

2022-09-20 07:54 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +A session is a group of user interactions with your website or mobile app within a given time frame. It is usually triggered when a user opens a mobile app or a website in their browser and ends afte
actually, it's the session that ends, so this change would cause some confusion.

2022-09-20 07:54 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +
Incorporated this feedback.

2022-09-20 07:57 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> +By default, the Android SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time configure
incorporated this feedback.

2022-09-20 08:03 UTC, ishachopra0401 approved these changes

2022-09-20 08:06 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/faq.mdx
> +### What is the `timeout` option in automatic session tracking?
Done!

2022-09-20 08:07 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/session-tracking/faq.mdx
> +RudderStack passes the event's `timestamp` (in milliseconds) as the `sessionId`. It **does not** attach any user information to this `sessionId` so that they cannot be traced back or identified only
Made this change.

2022-09-20 11:40 UTC, MoumitaM commented on docs/sources/event-streams/sdks/session-tracking/index.mdx
> +| `startSession()` | `sessionId` (**Long** integer with minimum length of 10 characters). **It is recommended to use a decimal number**. | You can pass a custom `sessionId` and trigger a new user ses
```suggestion
| `startSession()` | `sessionId` (**Long** integer with minimum length of 10 characters). **It is not recommended to use a decimal number**. | You can pass a custom `sessionId` and trigger a new user session. |
```

2022-09-20 13:56 UTC, pallabmaiti commented on docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> +By default, the Android SDK automatically tracks the user sessions. This means that RudderStack automatically determines the start and end of a user session depending on the inactivity time configure
> set withAutoSessionTracking to false to disable session tracking

This information is not accurate. Set it to `false` will disable **`automatic`** session tracking only.

2022-09-20 14:33 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-ios-sdk/index.mdx
> +To disable automatic session tracking, set `withAutoSessionTracking` to `false`.
@pallabmaiti just verified, the current sentence accurately reflects that only automatic session tracking is disabled.

2022-09-20 14:36 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-android-sdk/index.mdx
> +To disable automatic session tracking, set `withAutoSessionTracking` to `false`.
@pallabmaiti just verified, the current sentence accurately reflects this.

2022-09-22 15:05 UTC, merged