Mailmodo destination doc
rudderlabs/rudderstack-docs pull request #891
Opened 2022-09-13 05:50 UTC by ishachopra0401

## What do these changes do?

Created Mailmodo destination doc

2022-09-21 06:35 UTC, rohithkaza commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +RudderStack supports Mailmodo as a destination where you can seamlessly send your event data.
We are supporting Mailmodo as a source too. Do we need this line here?

2022-09-21 06:36 UTC, rohithkaza commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +- **List Name**: This field is **only applicable** for the `identify` call. Enter the name of the Mailmodo list where contacts should be added. If not provided, `rudderstack` is taken as the default
```suggestion
- **List Name**: This field is **only applicable** for the `identify` call. Enter the name of the Mailmodo list where contacts should be added. If not provided, `Rudderstack` is taken as the default list name. 
```

2022-09-22 06:38 UTC, rohithkaza commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +| `traits.zipcode`/`context.traits.zipcode` | `values.data.postal_code` | Optional |
lets add `postalcode` and `postal_code`

2022-09-22 06:39 UTC, rohithkaza commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +| `traits.lastName`/`context.traits.lastName` | `values.data.lastName` | Optional |
```suggestion
| `traits.lastName`/`context.traits.lastName` | `values.data. last_name ` | Optional |
```

2022-09-22 06:47 UTC, ItsSudip requested changes

2022-09-22 06:47 UTC, ItsSudip commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +[Mailmodo](https://www.mailmodo.com/) is an interactive email marketing tool that provides several useful features such as, sending transactional campaigns, email automation and drip emails with cust
```suggestion
[Mailmodo](https://www.mailmodo.com/) is an interactive email marketing tool that provides several useful features such as sending transactional campaigns, email automation and drip emails with customer journeys, WYSIWYG email editor, and many other tool integrations.
```

2022-09-22 07:14 UTC, rohithkaza approved these changes

2022-09-22 15:24 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +[Mailmodo](https://www.mailmodo.com/) is an interactive email marketing tool that provides several useful features such as sending transactional campaigns, email automation and drip emails with custo
```suggestion
[Mailmodo](https://www.mailmodo.com/) is an interactive email marketing tool. It provides several useful features like sending transactional campaigns, email automation, and drip emails with customer journeys, WYSIWYG email editor, and many other tool integrations.
```

2022-09-22 15:25 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +Apart from Mailmodo destination, RudderStack also supports <a href ="/sources/event-streams/cloud-apps/mailmodo/">Mailmodo as a source</a>.
```suggestion
RudderStack also supports Mailmodo as a data source. For more information, refer to the <a href ="/sources/event-streams/cloud-apps/mailmodo/">Mailmodo source documentation</a>.
```

2022-09-22 15:26 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +<div class="infoBlock">
```suggestion
<div class="successBlock">
```

2022-09-22 15:27 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/mailmodo.mdx
> +- **List Name**: This field is **only applicable** for the `identify` call. Enter the name of the Mailmodo list where contacts should be added. If not provided, `Rudderstack` is taken as the default
```suggestion
- **List Name**: This field is **only applicable** for the `identify` call. Enter the name of the Mailmodo list where the contacts should be added. If not provided, `Rudderstack` is taken as the default list name. 
```

2022-09-22 16:15 UTC, merged