Device mode transformation
rudderlabs/rudderstack-docs pull request #892
Opened 2022-09-13 11:55 UTC by ishachopra0401

## What do these changes do?

- Add device mode transformation details
- Refactor the Transformations content into separate guides to make it less overwhelming

2022-09-15 15:40 UTC, saikumarrs requested changes

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +In case you plan to use both the above-mentioned features, your events will be filtered (based on the <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#integrationopts">`i
The integrationsOpts object is not relevant here.

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +### Is there any added cost to use the transformations in device mode?
```suggestion
### Is there any added performance cost to using the transformations in device mode?
```

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +However, there is a chance of events getting lost while sending them via JavaScript SDK in case of a network error.
```suggestion
However, there is a chance of events getting lost while sending them via JavaScript SDK in case of a network error as they are not persisted. However, the SDK retries multiple times before dropping the event.
```

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/index.mdx
> +/>
Should it be "Pro and Enterprise" customers?

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +- **Transformations**: When you need to mask the data, enrich events, implement specific actions on events or remove sensitive PII information from the events.
This option also enables filtering events.

We should rather be highlighting the fact that the event filtering based on "event names" takes place within the SDK while transformation is a more generic approach to manipulating the events, which involves a call to an external RudderStack service.

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +Yes, RudderStack sends a network call for each event when the transformations are used in the device mode. It leads to extra overhead and latency.
```suggestion
Yes, RudderStack makes a network call for each event when the transformations are used in the device mode.
```

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +Yes, RudderStack sends a network call for each event when the transformations are used in the device mode. It leads to extra overhead and latency.
The redacted part is implicit.

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +Yes, RudderStack sends a network call for each event when the transformations are used in the device mode. It leads to extra overhead and latency.
Also, "for each event" is applicable only for JS SDK. In the case of mobile SDKs, the events are batched.
CC @desusai7 @itsdebs

2022-09-15 15:40 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +    - If installed through NPM, it's possible to downgrade the SDK version and choose whether to use the transformation or not.
```suggestion
    - If installed through NPM, it's possible to downgrade the SDK version. However, the transformation might not be supported in the previous version.
```

2022-09-19 10:12 UTC, ishachopra0401 commented on docs/features/transformations/index.mdx
> +/>
Not sure, it specifies the availability of the feature whether someone is a Pro or an Enterprise customer. Mentioning "Pro and Enterprise" can create confusion whether both are required

2022-09-19 10:13 UTC, ishachopra0401 commented on docs/features/transformations/faq.mdx
> +Yes, RudderStack sends a network call for each event when the transformations are used in the device mode. It leads to extra overhead and latency.
@desusai7 can you please confirm?

2022-09-19 10:46 UTC, ishachopra0401 commented on docs/features/transformations/faq.mdx
> +- **Transformations**: When you need to mask the data, enrich events, implement specific actions on events or remove sensitive PII information from the events.
@saikumarrs Confirming my understanding on the same:

Apart from setting 'event filtering' in the dashboard, users can write a transformation to filter events.

So, the actual question is which option to use to filter events: event filtering in the dashboard or writing a transformation:

* In dashboard event filtering, filtering happens within the SDK
* In transformation, a call to an external RudderStack service is made

2022-09-19 13:09 UTC, saikumarrs commented on docs/features/transformations/faq.mdx
> +- **Transformations**: When you need to mask the data, enrich events, implement specific actions on events or remove sensitive PII information from the events.
Dashboard event filtering is purely by "event names". So, it's only applicable for track events. This feature is the best option if users have just this specific use case.

However, transformations is a powerful feature but has it's caveats which we've discussed already in this doc.

2022-09-20 09:28 UTC, desusai7 commented on docs/features/transformations/faq.mdx
> +Yes, RudderStack sends a network call for each event when the transformations are used in the device mode. It leads to extra overhead and latency.
Yes, @saikumarrs is right, we do send events in batches to the transformations service.

2022-09-21 04:19 UTC, 1abhishekpandey commented on docs/get-started/cloud-vs-open-source.mdx
> +| <Link to="/features/transformations/">Transformations</Link> |  ✅ |  ✅ | <ul><li>For Open Source users, transformations are available only in the [RudderStack-hosted control plane](https://app.rudd
Should we add info related to device mode transformation as well?
This line: `In device mode, the Transformations feature is only available for the Enterprise users.`

2022-09-22 06:37 UTC, ishachopra0401 commented on docs/get-started/cloud-vs-open-source.mdx
> +| <Link to="/features/transformations/">Transformations</Link> |  ✅ |  ✅ | <ul><li>For Open Source users, transformations are available only in the [RudderStack-hosted control plane](https://app.rudd
Good catch! I have added this.

2022-10-14 02:08 UTC, ameypv-rudder commented on docs/features/transformations/index.mdx
> +<li>In <Link to="/destinations/rudderstack-connection-modes/#cloud-mode">cloud mode</Link>, you can use up to 3 transformations in the free plan. To use unlimited Transformations, you need to be a <a
```suggestion
<li>In <Link to="/destinations/rudderstack-connection-modes/#cloud-mode">cloud mode</Link>, you can use up to 3 transformations in the free plan. To use unlimited Transformations, you need to be a <a href="https://rudderstack.com/pricing/">Pro or Enterprise</a> user.</li>
```

2022-10-14 02:10 UTC, ameypv-rudder commented on docs/features/transformations/index.mdx
> +
Instead of "In cloud mode..." or "In device mode..." , should we instead say "For cloud mode destinations..." / "For device mode destinations..."? Just for more clarity, I feel.

2022-10-14 02:29 UTC, ameypv-rudder commented on docs/features/transformations/index.mdx
> +Some key features of RudderStack Transformations are listed below:
Use of `Transformations` vs `transformations` in regular sentences - Let's discuss more on this in our call.

2022-10-18 12:23 UTC, ishachopra0401 commented
Closing this as the changes are being taken up in the new PR: https://github.com/rudderlabs/rudderstack-docs/pull/950

2022-10-18 12:23 UTC, closed without merging