User.com doc
rudderlabs/rudderstack-docs pull request #896
Opened 2022-09-15 08:10 UTC by ishachopra0401

## What do these changes do?

Created User.com doc

2022-09-15 09:34 UTC, mihir-4116 requested changes

2022-09-15 09:34 UTC, mihir-4116 commented on docs/destinations/streaming-destinations/user-com.mdx
> +| `userId` | `custom_id` | Required  |
can we updated all values of a key like traits.userId, context.traits.userId (updated in notion all possible value of Rudderstack property key)

2022-09-20 10:36 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/user-com.mdx
> +| `userId` | `custom_id` | Required  |
done

2022-09-22 06:41 UTC, mihir-4116 approved these changes

2022-09-22 17:50 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +- **Map Rudder user attributes to User.com attributes**: Enter the custom user attributes you want to map for RudderStack and User.com correspondingly.
```suggestion
- **Map Rudder user attributes to User.com attributes**: With this setting, you can map the RudderStack event properties to specific User.com user attributes.
```

2022-09-22 17:53 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +- **Map RudderStack event name to User.com event name**: Enter the event names you want to map for RudderStack and User.com correspondingly. You can map one or more RudderStack events to a single Use
```suggestion
- **Map RudderStack event name to User.com event name**: Use this setting to map the RudderStack event names to specific User.com events. You can map one or more RudderStack events to a single User.com event but **not** vice-versa.
```

2022-09-22 17:55 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +- **Map your event property**: Enter the RudderStack and User.com event properties you want to map for the above-mentioned event names. You can map a RudderStack property to a single User.com propert
```suggestion
- **Map your event property**: Enter the RudderStack and User.com event properties you want to map for the above-mentioned event names. You can map a RudderStack property only to one User.com property and vice-versa.
```

2022-09-22 17:57 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +- **Map Rudder company attributes to User.com company attributes**: Enter the custom company attributes you want to map for RudderStack and User.com correspondingly.
```suggestion
- **Map Rudder company attributes to User.com company attributes**: Use this setting to map the RudderStack company attributes to specific User.com company attributes.
```

2022-09-22 17:58 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +This algorithm to look up a user is applicable only for the <code class="inline-code">identify</code>, <code class="inline-code">track</code>, and <code class="inline-code">page</code> calls.
```suggestion
The algorithm to look up a user is applicable only for the <code class="inline-code">identify</code>, <code class="inline-code">track</code>, and <code class="inline-code">page</code> calls.
```

2022-09-22 17:59 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +This algorithm to look up a user is applicable only for the <code class="inline-code">identify</code>, <code class="inline-code">track</code>, and <code class="inline-code">page</code> calls.
```suggestion
This functionality is applicable only for the <code class="inline-code">identify</code>, <code class="inline-code">track</code>, and <code class="inline-code">page</code> calls.
```

2022-09-22 17:59 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +RudderStack looks up for a user using the `user_key`, `email` or `phone` properties.
```suggestion
RudderStack looks up a user in User.com using the `user_key`, `email`, or `phone` properties.
```

2022-09-22 18:02 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +You can use the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to create a new user in User.com. If the user already exists, the user details are updated.
```suggestion
You can use the <Link to="/event-spec/standard-events/identify">`identify`</Link> call to create a new user in User.com. If the user already exists, RudderStack updates the user details.
```

2022-09-22 18:06 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +You can use the <Link to="/event-spec/standard-events/track">`track`</Link> call to record a new event, which in turn, can be used to filter and bucket users in User.com.
```suggestion
You can use the <Link to="/event-spec/standard-events/track">`track`</Link> call to record a new event which, in turn, can be used to filter and bucket users in User.com.
```

2022-09-22 18:07 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +The following table lists the mappings between RudderStack and User.com properties for `track` call:
```suggestion
The following table lists the mappings between RudderStack and User.com properties for the `track` call:
```

2022-09-22 18:08 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +The following table lists the mappings between RudderStack and User.com properties for `group` call:
```suggestion
The following table lists the mappings between RudderStack and User.com properties for the `group` call:
```

2022-09-22 18:08 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +1. Log into <a href="https://app.user.com/accounts/login/">User.com dashboard</a> and go to your App.
```suggestion
1. Log into your <a href="https://app.user.com/accounts/login/">User.com dashboard</a> and go to your app. 
```

2022-09-22 18:09 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/user-com.mdx
> +1. Log into <a href="https://app.user.com/accounts/login/">User.com dashboard</a> and go to your App.
```suggestion
1. Log into your <a href="https://app.user.com/accounts/login/">User.com dashboard</a> and go to your app. 
```

2022-09-23 05:22 UTC, ameypv-rudder approved these changes
LGTM

2022-09-23 05:55 UTC, merged