Recurly Docs
rudderlabs/rudderstack-docs pull request #91
Opened 2021-06-01 12:24 UTC by Shivam4415

## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-06-01 12:52 UTC, arnab-p requested changes

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +- **Custom Fields Mapping** - This will map any RudderStack event to Recurly Event. To do successful mapping make sure you have created a custom fields in your recurly dashboard. If you wish to map r
```suggestion
- **Custom Fields Mapping** - This will map any RudderStack event to a Recurly Event. To do successful mapping make sure you have created a custom field on your Recurly dashboard. If you wish to map RudderStack properties to Recurly Custom fields then list them here. These properties are case-sensitive and can be nested. For example, you have created `paymentValue` and `personalMailId` in your Recurly dashboard now if you want to send `rudderanalytics.track('Event', {customProperty: { customValue: 2 }, someRandomMailId: 'user@gmail.com'})` then input these two property `customProperty.customValue` and `someRandomMailId` in RudderStack payload and `paymentValue` and `personalMailId` in Recurly payload
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +When you make an identify call with new userId, we create a new account.
```suggestion
When you make an `identify` call with the new `userId`, we create a new account.
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +When you make an identify call with existing userId, we update the existing account with new traits passed.
```suggestion
When you make an `identify` call with an existing `userId`, we update the existing account with new traits passed.
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +Following property mapping happens when you make an identify calls ::
```suggestion
Following property mapping happens when you make an identify calls :
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +The `track` call to recurly is supported only for two of our ecommerce event.
```suggestion
The `track` call to Recurly is supported only for two of our e-commerce events.
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +
```suggestion
- Checkout Started
- Order Completed
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +- To make a successful track call, an account must be present in recurly. Our `track` calls gets mapped to `line_items` for that account in recurly.
```suggestion
- To make a successful track call, an account must be present in Recurly. Our `track` calls get mapped to `line_items` for that account in Recurly.
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +- Any `products` that you send in payload is associated with `items` in recurly.
```suggestion
- All the `products` that you send in the payload are associated with `items` in Recurly.
```

2021-06-01 12:52 UTC, arnab-p commented on destinations/recurly.md
> +- If a products is not present in recurly dashboard, we create a new `items` for that product and associated it with `line_items`.
```suggestion
- If a product is not present in Recurly dashboard, we create new `items` for that product and associated it with `line_items`.
```

2021-06-01 13:01 UTC, Shivam4415 commented on destinations/recurly.md
> +- **Custom Fields Mapping** - This will map any RudderStack event to Recurly Event. To do successful mapping make sure you have created a custom fields in your recurly dashboard. If you wish to map r
done

2021-06-01 13:01 UTC, Shivam4415 commented on destinations/recurly.md
> +When you make an identify call with existing userId, we update the existing account with new traits passed.
done

2021-06-03 11:14 UTC, ameypv-rudder commented on destinations/billing-platforms/recurly.md
> +![Recurly Connection Settings in RudderStack](../.gitbook/assets/recurly.png)
I was unable to preview the image. Please re-upload the screenshot @Shivam4415

2021-06-03 11:16 UTC, ameypv-rudder commented on destinations/billing-platforms/recurly.md
> +- **Custom Fields Mapping** - This field lets you map any RudderStack event to a Recurly Event. To do successful mapping, make sure you have created a custom field on your Recurly dashboard. You can
"make sure you have created a custom field on your Recurly dashboard."

can we add a reference / Recurly support link to show the readers how to do this? we can also add this as a FAQ, if required.

2021-06-03 11:20 UTC, ameypv-rudder reviewed
Left a few comments for your review / approval. @Shivam4415 @arnab-p @ruchiramoitra

2021-06-03 11:20 UTC, ameypv-rudder commented on destinations/billing-platforms/recurly.md
> +
The code snippet below is missing some context. Can we add something like the following:

"A sample `track` event which demonstrates this is as shown below:" 

Also, please review the text for accuracy.

2021-06-04 04:27 UTC, Shivam4415 commented on destinations/billing-platforms/recurly.md
> +![Recurly Connection Settings in RudderStack](../.gitbook/assets/recurly.png)
Since we nested this file in billing-platforms folder so the path was broken. Fixed that

2021-06-04 07:48 UTC, Shivam4415 commented on destinations/billing-platforms/recurly.md
> +
done

2021-06-04 07:55 UTC, Shivam4415 commented on destinations/billing-platforms/recurly.md
> +- **Custom Fields Mapping** - This field lets you map any RudderStack event to a Recurly Event. To do successful mapping, make sure you have created a custom field on your Recurly dashboard. You can
Added FAQ section.

2021-06-04 08:18 UTC, ameypv-rudder approved these changes

2022-01-28 05:04 UTC, ameypv-rudder commented
Closing this PR as it is quite old. Its contents can be revisited if/when the work on this integration restarts.

2022-01-28 05:04 UTC, closed without merging