June destination
rudderlabs/rudderstack-docs pull request #919
Opened 2022-09-27 08:16 UTC by ishachopra0401

## What do these changes do?

Create June destination doc

2022-09-27 09:22 UTC, Gauravudia requested changes

2022-09-27 09:22 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +To create a company or update the company details, the <code class="inline-code">groupId</code> should be passed in the <code class="inline-code">track</code> call.
This statement is wrong. We are not creating/updating company details in track call.
We can use :- 
`If you're identifying companies, you should pass the `groupId` in track call.
`groupId`  in track call allows you to specify what company performed an event`

2022-09-27 09:22 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to create new users or update existing users' details in June. RudderStack sends the `identify` call to June as
Can attach `JUNE` Identify API link here.
https://www.june.so/docs/api#:~:text=Copy-,Identifying%20users,-You%20can%20use

2022-09-27 09:22 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events along with the properties associated with them. RudderStack sends the `track` call to June as a `trac
Can attach JUNE Track API link here.
https://www.june.so/docs/api#:~:text=Copy-,Send%20track%20events,-In%20order%20to

2022-09-27 09:22 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +You can use the <Link to="/event-spec/standard-events/group/">`group`</Link> call to create a new company or update an existing company's details in June.
Can attach `JUNE` group API link here
https://www.june.so/docs/api#:~:text=Identifying%20companies%20(optional)

2022-09-27 09:42 UTC, Gauravudia requested changes

2022-09-27 09:42 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +rudderanalytics.track("Product Reviewed", {
Please use the update snippet from research spec.

2022-09-27 09:42 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +rudderanalytics.track("Product Reviewed", {
Please use the updated snippet from research spec.

2022-09-27 09:42 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +| `context.externalId.id` (when `context.externalId.type` = `juneGroupId`/`properties.groupId`)   | `context.groupId`    | String | Optional |
same as [here](https://github.com/rudderlabs/rudderstack-docs/pull/919/files#r980965089)

2022-09-27 09:42 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +To create a company or update the company details, the <code class="inline-code">groupId</code> should be passed in the <code class="inline-code">track</code> call.
same as [here](https://github.com/rudderlabs/rudderstack-docs/pull/919/files#r980982234)

2022-09-27 12:31 UTC, Gauravudia requested changes

2022-09-27 12:31 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +To identify a company, pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</code> call. It allows you to specify which company performed that specific event.
- Statement seems incorrect. We are not `identifying companies `in track call.
`Group` call is used to identify company. It is recommended to pass `groupId` in `track` call If user is using the group call (Identify company)
- Also, please move this `note` to track call.

2022-09-27 12:31 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +To identify a company, pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</code> call. It allows you to specify which company performed that specific event.
- Statement seems incorrect. We are not `identifying companies` in track call.
`Group` call is used to identify company. It is recommended to pass `groupId` in track call If user is using the group call (Identify company)
- Also, please move this `note` to track call.

2022-09-27 13:00 UTC, Gauravudia approved these changes

2022-09-28 05:19 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/index.mdx
> +[June](https://www.june.so/)is a lightweight product analytics tool that helps you define and measure product usage intuitively by tracking user retention, active users, acquisition funnel, engagemen
```suggestion
[June](https://www.june.so/) is a lightweight product analytics tool that helps you define and measure product usage intuitively by tracking user retention, active users, acquisition funnel, engagement, feature usage, etc.
```

2022-09-28 05:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +To successfully configure June as a destination, configure the following settings:
```suggestion
To successfully set up June as a destination, configure the following settings:
```

2022-09-28 05:22 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +To successfully configure June as a destination, configure the following settings:
Made a similar change in our destination template, as "configure" is repeated here.

2022-09-28 05:22 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +1. Login to the [June dashboard](https://www.june.so/).
```suggestion
1. Login to the [June dashboard](https://analytics.june.so/login).
```

2022-09-28 05:23 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +2. Click on your workspace and select **Settings & Integrations**.
```suggestion
2. Go to your workspace and select **Settings & Integrations**.
```

2022-09-28 05:23 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +2. Click on your workspace and select **Settings & Integrations**.
Would this be accurate?

2022-09-28 05:25 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +RudderStack lets you send your event data to June via <Link to="/destinations/rudderstack-connection-modes/#cloud-mode">cloud mode</Link>.
```suggestion
RudderStack lets you send your event data to June via the <Link to="/destinations/rudderstack-connection-modes/#cloud-mode">cloud mode</Link>.
```

2022-09-28 05:34 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to create new users or update existing users' details in June. RudderStack sends the `identify` call to June as
```suggestion
You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to create new users or update an existing user's details in June. RudderStack sends the `identify` call to June as an [`identify`](https://www.june.so/docs/api#:~:text=Copy-,Identifying%20users,-You%20can%20use) event. 
```

2022-09-28 05:35 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +| `originalTimestamp`/`timestamp`  | `timestamp`      |String *(ISO 8601 date format yyyy-MM-ddTHH:mm:ss.SSSZ)* | Required |
```suggestion
| `originalTimestamp`/`timestamp`  | `timestamp`      |String (ISO 8601 date format `yyyy-MM-ddTHH:mm:ss.SSSZ`) | Required |
```

2022-09-28 05:38 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events along with the properties associated with them. RudderStack sends the `track` call to June as a [`tra
```suggestion
The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events along with the properties associated with them. RudderStack sends the `track` call to June using their [`track`](https://www.june.so/docs/api#:~:text=Copy-,Send%20track%20events,-In%20order%20to) API.
```

2022-09-28 05:55 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/june/setting-up-june-in-rudderstack.mdx
> +2. Click on your workspace and select **Settings & Integrations**.
Actually you dont need to click on the workspace, it is there by default

2022-09-28 07:00 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +June categorizes a user as `Unknown` if the `firsName`, `lastName`, `name`, `username`, or `email` is not present in the `identify` call's `traits`.
```suggestion
June categorizes a user as `Unknown` if the `firstName`, `lastName`, `name`, `username`, or `email` is not present in the `traits` object of the `identify` call.
```

2022-09-28 07:03 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +No, you can't. June does not stitches identities together or offers anonymous user merging. It is rather used for logged-in experiences where you can measure user activation and retention.
```suggestion
No, you can't. June does not stitch identities together or support merging anonymous users. Rather, it is best used to measure user activation and retention when the user is logged in.
```

2022-09-28 07:03 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +No, you can't. June does not stitches identities together or offers anonymous user merging. It is rather used for logged-in experiences where you can measure user activation and retention.
LMK if this change makes sense.

2022-09-28 07:04 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +| `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id`       | `userId`        | String | <ul><li>Required while creating a company.</li><li>Optional while updating the co
```suggestion
| `userId`/`traits.userId`/`traits.id`/`context.traits.userId`/`context.traits.id`       | `userId`        | String | <ul><li>Required for creating a company.</li><li>Optional for updating the company details.</li></ul>  |
```

2022-09-28 07:08 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-cloud-mode.mdx
> +If you are using a <code class="inline-code">group</code> call to identify a company, it is recommended to pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</co
```suggestion
If you are using a <code class="inline-code">group</code> call to identify a company, it is recommended to pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</code> call. It allows you to specify which company performed that specific event. For more information, refer to the <a href="https://www.june.so/docs/api#:~:text=Copy-,Send%20track%20events,-In%20order%20to">June documentation</a>.
```

2022-09-28 07:11 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +Make sure that you make an <code class="inline-code">identify</code> call before a <code class="inline-code">track</code> call.
Should we include this information in the cloud mode doc too? 
From the FAQ, I understood this destination works best with identified users, so this is applicable for both modes.

2022-09-28 07:19 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +If you are using a <code class="inline-code">group</code> call to identify a company, it is recommended to pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</co
```suggestion
If you are using a <code class="inline-code">group</code> call to identify a company, it is recommended to pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</code> call. It allows you to specify which company performed that specific event. For more information, refer to the <a href="https://www.june.so/docs/api#:~:text=Copy-,Send%20track%20events,-In%20order%20to">June documentation</a>.
```

2022-09-28 07:21 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +Make sure that you make an <code class="inline-code">identify</code> call before a <code class="inline-code">group</code> call to create a company successfully.
Applicable for the cloud mode doc too. An alternative would be to just specify in the `identify` section that the user needs to make an `identify` call before making any `track`, `group`, or `page` calls.

2022-09-28 07:22 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +No, you can't. June does not stitches identities together or offers anonymous user merging. It is rather used for logged-in experiences where you can measure user activation and retention.
```suggestion
No, you can't. June does not stitch identities together or support merging anonymous users. Rather, it is best used to measure user activation and retention when the user is logged in.
```

2022-09-28 07:23 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +June categorizes a user as `Unknown` if the `firsName`, `lastName`, `name`, `username`, or `email` is not present in the `identify` call's `traits`.
```suggestion
June categorizes a user as `Unknown` if the `firstName`, `lastName`, `name`, `username`, or `email` is not present in the `traits` object of the `identify` call.
```

2022-09-28 07:30 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +Make sure that you make an <code class="inline-code">identify</code> call before a <code class="inline-code">group</code> call to create a company successfully.
Yes, We can add a note in `Identify` call.

2022-09-28 07:50 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +Make sure that you make an <code class="inline-code">identify</code> call before a <code class="inline-code">group</code> call to create a company successfully.
@Gauravudia I remember we had a discussion over this. [Ref](https://github.com/rudderlabs/rudderstack-docs/pull/919/commits/df0d615d711cb421d24882b460746e5038588a8b#r980968061)

Also, another one for track call in device mode. [Ref](https://www.notion.so/June-Cloud-and-Device-mode-Destination-1e02191a9d0e4f579c5ec2cd2609cb27?d=a514b1c39eaa4f5b8950ae9969229320#8dccdfd4b61f476c945ca5acb48f2503)

Can you please confirm again if the latest note is valid for both the modes?

2022-09-28 09:07 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +Make sure that you make an <code class="inline-code">identify</code> call before a <code class="inline-code">group</code> call to create a company successfully.
@ishachopra0401 Above `note` is valid for both modes. We can add a `note` in Identify call as suggested by Amey.

2022-09-28 09:46 UTC, ameypv-rudder approved these changes

2022-10-11 06:55 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +You can use the <Link to="/event-spec/standard-events/identify/">`identify`</Link> call to create new users or update existing users' details in June. RudderStack sends the `identify` call to June as
Link pointing to Rest API endpoint.
sdk identify call doc link :- https://www.june.so/docs/identifying-users

2022-10-11 06:55 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events along with the properties associated with them. RudderStack sends the `track` call to June as a [`tra
Link pointing to Rest API endpoint. 
sdk track event doc link :- https://www.june.so/docs/tracking-events

2022-10-11 06:55 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +You can use the <Link to="/event-spec/standard-events/group/">`group`</Link> call to create a new company or update an existing company's details in June. Refer to the [June documentation](https://ww
Link pointing to Rest endpoint doc.
sdk group call doc link :- https://www.june.so/docs/tracking-groups

2022-10-11 06:55 UTC, Gauravudia commented on docs/destinations/streaming-destinations/june/june-device-mode.mdx
> +If you are using a <code class="inline-code">group</code> call to identify a company, it is recommended to pass the <code class="inline-code">groupId</code> in the <code class="inline-code">track</co
Link pointing to Rest endpoint doc.
sdk group call doc link :- https://www.june.so/docs/tracking-groups

2022-10-12 10:02 UTC, merged