Content security policy
rudderlabs/rudderstack-docs pull request #922
Opened 2022-09-27 11:35 UTC by ishachopra0401

## What do these changes do?

Add details for Content security policy in JS SDK

2022-09-27 13:38 UTC, saikumarrs requested changes

2022-09-27 13:38 UTC, saikumarrs commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you need to allowlist the domain from where the destinatio
This is incorrect. The SDK does not have anything to do with the CSP. The website owners define their own CSP.

Moreover, it's not always a requirement for users to allowlist the domain in their CSP as it depends on how the CSP is defined.

```suggestion
While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the destination SDK will load in your content security policy (CSP). A CSP adds an extra layer of protection from any type of cross-site scripting, clickjacking, and data injection attacks.
```

2022-09-27 13:38 UTC, saikumarrs commented on docs/destinations/streaming-destinations/bugsnag.mdx
> +While using the RudderStack <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">JavaScript SDK </Link> source with Bugsnag, you need to allowli
It's better to put this info into a section to establish uniformity across destination docs and allows us to point to the standard section name in the SDK documentation.

```suggestion
In the web device mode integration (<Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link>), the Bugsnag native SDK is loaded from <code class="inline-code">https://d2wy8f7a9ursnm.cloudfront.net/</code> domain. You might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist</Link> this domain in your website's content security policy to load Bugsnag successfully.
```

2022-10-04 06:33 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/bugsnag.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Bugsnag native SDK is loaded from <code cla
```suggestion
In the web device mode integration, the Bugsnag native SDK is loaded from <code class="inline-code">https://d2wy8f7a9ursnm.cloudfront.net/</code> domain. Based on your website's content security policy, you might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist this domain</Link> to load the Bugsnag SDK successfully.
```

2022-10-04 06:34 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/bugsnag.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Bugsnag native SDK is loaded from <code cla
We don't need to explain what web device mode is explicitly.

2022-10-04 06:41 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
```suggestion
While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the destination SDK will load in your content security policy (CSP). 

<div class="infoBlock">
A CSP adds an extra layer of protection from any type of cross-site scripting, clickjacking, and data injection attacks.
</div>
```

2022-10-04 06:45 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +You can refer to the **Getting started** section of the specific <Link to="/destinations/streaming-destinations/">destination's documentation</Link> to obtain the domain that might need to be allowli
When we say might, it looks like the allowlisting the domain may or may not be required. From what I understand, if we're using the destination in the device mode, allowlisting the domain is required, right?

2022-10-04 06:46 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +You can refer to the **Getting started** section of the specific <Link to="/destinations/streaming-destinations/">destination's documentation</Link> to obtain the domain that might need to be allowli
```suggestion
You can refer to the **Getting started** section of the specific <Link to="/destinations/streaming-destinations/">destination's documentation</Link> to obtain the domain that needs to be allowlisted. 
```

2022-10-04 06:46 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +You can refer to the **Getting started** section of the specific <Link to="/destinations/streaming-destinations/">destination's documentation</Link> to obtain the domain that might need to be allowli
If the action is mandatory - we can include this change.

2022-10-04 06:46 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
```suggestion
While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you need to allowlist the domain from where the destination SDK will load in your content security policy (CSP). A CSP adds an extra layer of protection from any type of cross-site scripting, clickjacking, and data injection attacks.
```

2022-10-04 06:47 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
Same here- unless it's optional.

2022-10-04 06:51 UTC, ishachopra0401 commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
It actually depends on the type of content security policy a user is using for their website. Based on that, they might or might not need to allowlist the domain. Hence, its optional

2022-10-04 06:53 UTC, ameypv-rudder commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
thanks for clarifying, Isha!

2022-10-04 06:56 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/bugsnag.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Bugsnag native SDK is loaded from <code cla
as discussed, we'll retain this.

2022-10-04 06:57 UTC, ameypv-rudder approved these changes

2022-11-10 10:03 UTC, saikumarrs requested changes
LGTM overall. I didn't verify the domain for each of the integrations though.

2022-11-10 10:03 UTC, saikumarrs commented on docs/destinations/streaming-destinations/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Adobe Analytics native SDK is loaded from <
The domain name is incorrect. It points to our CDN.

2022-11-10 10:03 UTC, saikumarrs commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
Instead of cross-referencing the repository, we should point them to the definition in the docs.

2022-11-10 10:03 UTC, saikumarrs commented on docs/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk.mdx
> +While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the dest
```suggestion
While using the JavaScript SDK with any [device mode destination](https://github.com/rudderlabs/rudder-sdk-js/tree/production/integrations), you might need to allowlist the domain from where the destination SDK will load in your content security policy (CSP).
```

2022-11-10 11:30 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Adobe Analytics native SDK is loaded from <
@MoumitaM Can you please confirm the domain here?

2022-11-11 07:25 UTC, MoumitaM commented on docs/destinations/streaming-destinations/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Adobe Analytics native SDK is loaded from <
@saikumarrs, for Abode we load it from our CDN.

2022-11-11 07:32 UTC, saikumarrs commented on docs/destinations/streaming-destinations/adobe-analytics/setting-up-adobe-analytics-in-rudderstack.mdx
> +In the web device mode integration, that is, using <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk">JavaScript SDK</Link> as a source, the Adobe Analytics native SDK is loaded from <
Oops. Resolving this.

2022-11-11 07:32 UTC, saikumarrs approved these changes

2022-11-11 07:46 UTC, utsabc commented on docs/destinations/streaming-destinations/optimizely-web.mdx
> +Based on your website's content security policy, you might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist the domain</Li
We are not linking ant reference is it fine?

2022-11-11 07:46 UTC, utsabc commented on docs/destinations/streaming-destinations/post-affiliate-pro.mdx
> +Based on your website's content security policy, you might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist the domain</Li
This one as well

2022-11-11 07:46 UTC, utsabc commented on docs/destinations/streaming-destinations/profitwell/profitwell-cloud-mode.mdx
> +</div>
Do we need to mention this for cloud mode>

2022-11-11 08:22 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/optimizely-web.mdx
> +Based on your website's content security policy, you might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist the domain</Li
@utsabc This is so, as you mentioned in the sheet that this URL is user defined: https://docs.google.com/spreadsheets/d/1Ikxp5kYVJbY03Lt9L630POSEj_9BaCpt78VgChTLrD0/edit?disco=AAAAhN5zS30

Let me know if my understanding is not correct

2022-11-11 08:24 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/profitwell/profitwell-cloud-mode.mdx
> +</div>
You are right, I ll revert this change

2022-11-11 08:58 UTC, utsabc commented on docs/destinations/streaming-destinations/optimizely-web.mdx
> +Based on your website's content security policy, you might need to <Link to="/sources/event-streams/sdks/rudderstack-javascript-sdk/load-js-sdk/#allowlist-destination-domain">allowlist the domain</Li
Got it its basically set by user so yeah make sense

2022-11-11 08:59 UTC, utsabc approved these changes

2022-11-11 09:10 UTC, merged