Snowplow migration doc
rudderlabs/rudderstack-docs pull request #955
Opened 2022-10-20 12:49 UTC by ishachopra0401

## What do these changes do?

Created doc for Snowplow migration

2022-10-25 14:37 UTC, MoumitaM requested changes

2022-10-25 14:37 UTC, MoumitaM commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports only the v2 Snowplow JavaScript tracker.
This `setUserId` method is only supported in the Snowplow v2 JS tracker.
The rest of the events are from the v3 JS tracker.
So, `setUserId` is the only method supported by Rudderstack from the v2 version of the Snowplow tracker.
@ishachopra0401 , please rephrase the sentence.

2022-10-26 02:45 UTC, pallabmaiti requested changes

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +You can migrate your existing events from RudderStack to Snowplow as described below:
```suggestion
You can migrate your existing events from Snowplow to RudderStack as described below:
```

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +### Tracking users
```suggestion
### Tracking events
```

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack SDKs support the following types of Snowplow events to track users:
```suggestion
RudderStack SDKs support the following types of Snowplow events:
```

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +  <TabList>
Let's have two tabs. iOS/Android & JavaScript
Then show 4 tabs(Objective C, Swift, Java, Kotlin) under the code snippets of iOS/Android.

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +### Tracking users' activities
Let's follow the same:
```
Let's have two tabs. iOS/Android & JavaScript
Then show 4 tabs(Objective C, Swift, Java, Kotlin) under the code snippets of iOS/Android.
```

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> + RudderStack maps the <code class="inline-code">previousName</code> to RudderStack event name and the rest of the properties, like <code class="inline-code">screenId</code>, <code class="inline-code"
```suggestion
 RudderStack maps the <code class="inline-code">name</code> to RudderStack event name and the rest of the properties, like <code class="inline-code">screenId</code>, <code class="inline-code">previousType</code>, <code class="inline-code">previousId</code>, etc. to the RudderStack properties.
```

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">TrackerConfiguration</code></a> class can be us
This is similar to `RudderConfigBuilder`
Can you change the description?

2022-10-26 02:45 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">SubjectConfiguration</code></a> class can be us
```suggestion
The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">SubjectConfiguration</code></a> class can be used to capture basic information about the user which is attached on all events as context entity.
```

2022-10-26 06:42 UTC, MoumitaM approved these changes

2022-10-26 06:43 UTC, 1abhishekpandey commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +);
Actually, we are internally ignoring the first argument i.e., first argument is a dummy argument

> new SessionConfiguration(
>   ~new TimeMeasure(1, TimeUnit.MINUTES),~
>   new TimeMeasure(1, TimeUnit.MINUTES)
> );

Although the user needs to pass both the arguments but internally we will only consider the second argument.

- So, can you please add a info block at the appropriate place which mention this info.
- Can we add a reference to our (Mobile) Session Tracking doc. It'll could help in understanding the session behaviour properly. (Actually, Snowplow default timeout session is of 30 minutes in case of mobile but we have only of 5 minutes for mobile. Hence I want the first time user to navigate to the proper doc).

2022-10-26 06:43 UTC, 1abhishekpandey commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +| sessionContext      |         true      |
Can we add a info block stating that we're internally ignoring all fields other than mentioned in the table.
I mean even if the user do something like this:
`val trackerConfiguration = TrackerConfiguration()
  .base64Encoding(false)`

We'll internally ignore `base64Encoding` value. 
Note: This kind of methods are kept for easy migration and they don't play a role in any way for tracking events. It doesn't matter user uses them or not there value will be ignored internally.

2022-10-26 06:43 UTC, 1abhishekpandey commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +|           | **Java** | **Kotlin** | **Objective-C** | **Swift** |
We need to add one more class `LogLevel` in the table. Corresponding class name for all other column will also be same (i.e., LogLevel).

2022-10-26 07:07 UTC, ishachopra0401 commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +);
@1abhishekpandey for the first point, is it applicable only for the Android SDK as I see different arguments for the iOS SDK?

2022-10-26 07:16 UTC, 1abhishekpandey commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +);
It is applicable for both Android and iOS.

In iOS we've this code: 
> RSSessionConfiguration *sessionConfig = [[RSSessionConfiguration alloc] initWithForegroundTimeout: ~[[NSMeasurement alloc] initWithDoubleValue:30 unit:NSUnitDuration.minutes]~ backgroundTimeout:[[NSMeasurement alloc] initWithDoubleValue:30 unit:NSUnitDuration.minutes]];

In short, for mobile we'll only consider `backgroundTimeout` and it is the second argument in both cases (Android & iOS).

2022-10-26 08:09 UTC, ishachopra0401 commented
@1abhishekpandey @pallabmaiti All the comments are addressed.

2022-10-26 08:40 UTC, 1abhishekpandey approved these changes

2022-10-26 09:49 UTC, pallabmaiti approved these changes

2022-10-26 11:47 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +      <li>Add the following lines of code in your project level <code class="inline-code">app/build.gradle</code> file:
```suggestion
      <li>Add the following lines of code in your project-level <code class="inline-code">app/build.gradle</code> file:
```

2022-10-26 12:09 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +This document covers the necessary steps to migrate from [Snowplow](https://snowplow.io/) to RudderStack and replace your instrumentation code. Once done, you can start using the RudderStack SDKs to
```suggestion
This document covers the necessary steps to migrate from [Snowplow](https://snowplow.io/) to RudderStack and replace your instrumentation code. You can then start using the RudderStack SDKs to track your events with minimal code changes.
```

2022-10-26 12:09 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +1. [Sign up](https://app.rudderstack.com/signup) for the RudderStack dashboard.
```suggestion
1. [Sign up](https://app.rudderstack.com/signup) for RudderStack Cloud.
```

2022-10-26 12:09 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +      <li>Add the following lines of code in your project level <code class="inline-code">app/build.gradle</code> file:
@pallabmaiti if we're saying "project-level", does including only `build.gradle` as opposed to `app/build.gradle` make more sense?

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +<li>Update your SDK initialization to any one of the following snippet (method 1, 2, or 3). Also, replace the <code class="inline-code">WRITE_KEY</code> and <code class="inline-code">DATA_PLANE_URL</
Took me some time to figure out where these methods were, hence the addition.

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports setting values for the following Snowplow configuration objects in the mobile SDKs (iOS/Android). If not set, the default values are assigned.
What are the default values in this case? Should we clarify this bit? @pallabmaiti

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/configuring-how-events-are-sent/"><code class="inline-code">NetworkConfiguration</code></a>
```suggestion
The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/configuring-how-events-are-sent/"><code class="inline-code">NetworkConfiguration</code></a> class can be used to specify the collector endpoint, as shown:
```

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#session"><code class="inline-code">SessionConfiguration</code></a> class c
```suggestion
The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#session"><code class="inline-code">SessionConfiguration</code></a> class can be used to capture sessions to track the user activity in the app, as shown:
```

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +For mobile SDKs, Snowplow's default timeout session is 30 minutes whereas RuddeStack's default timeout session is 5 minutes. Refer to the <Link to="/sources/event-streams/sdks/session-tracking/#mobil
```suggestion
For mobile SDKs, Snowplow's default timeout session is 30 minutes whereas RudderStack's default timeout session is 5 minutes. Refer to the <Link to="/sources/event-streams/sdks/session-tracking/#mobile-sdks">RudderStack Session Tracking</Link> documentation for more information.
```

2022-10-26 12:10 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">TrackerConfiguration</code></a> class can be us
```suggestion
The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">TrackerConfiguration</code></a> class can be used to configure contexts and automatic events of the tracker and the general behavior, as shown in the below snippets:
```

2022-10-26 12:11 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +
Should we style the above variable names and their default values in backticks, i.e., code in text?

2022-10-26 12:11 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">SubjectConfiguration</code></a> class can be us
```suggestion
The <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/"><code class="inline-code">SubjectConfiguration</code></a> class can be used to capture basic user information which is attached to all the events as the context entity.
```

2022-10-26 12:11 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +Snowplow does not provide any call to identify a user. Although, RudderStack sends an <Link to="/event-spec/standard-events/identify/"><code class="inline-code">identify</code></Link> call if you ini
```suggestion
Snowplow does not provide any call to identify a user. However, RudderStack sends an <Link to="/event-spec/standard-events/identify/"><code class="inline-code">identify</code></Link> call if you initialize the <code class="inline-code">SubjectConfiguration</code> class while initializing the SDK. <strong>Note that a user is not identified if the SDK is not initialized</strong>. 
```

2022-10-26 12:11 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +Note that <code class="inline-code">userId</code> is a mandatory field. If not provided, the <code class="inline-code">identify</code> call is ignored.
```suggestion
<code class="inline-code">userId</code> is a mandatory field. If not provided, the <code class="inline-code">identify</code> call is ignored.
```

2022-10-26 12:36 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports only the <code class="inline-code">setUserId</code> method of the Snowplow v2 JS tracker.
Should we add some reference / link to the v2 JS tracker?

2022-10-26 12:36 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +In the below sample call, <code class="inline-code">alex@example.com</code> is the <code class="inline-code">userId</code> and the <code class="inline-code">firstName</code>, <code class="inline-code
```suggestion
In the below sample call, <code class="inline-code">alex@example.com</code> is the <code class="inline-code">userId</code>, while <code class="inline-code">firstName</code>, <code class="inline-code">lastName</code>, and <code class="inline-code">city</code> are the user traits.
```

2022-10-26 12:36 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-appli
```suggestion
RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for the Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#creating-a-structured-event"><code class="inline-code">Structured</code></a> class.
```

2022-10-26 12:36 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +In the below example, RudderStack maps <code class="inline-code">Action_example</code> to RudderStack event name and the rest of the properties, like <code class="inline-code">Category_example</code>
```suggestion
In the below example, RudderStack maps <code class="inline-code">Action_example</code> to the RudderStack event name and the rest of the properties like <code class="inline-code">Category_example</code>, <code class="inline-code">label</code>, <code class="inline-code">value</code>, etc. to the RudderStack properties.
```

2022-10-26 12:36 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-appli
```suggestion
RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for the Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/tracking-events/#creating-a-structured-event"><code class="inline-code">SelfDescribing</code></a> class.
```

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-appli
```suggestion
RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for the Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/previous-versions/objective-c-tracker/objective-c-1-0-0/#foreground-and-background-events"><code class="inline-code">Foreground</code></a> class.
```

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack sends the event name as <code class="inline-code">Application Opened</code> and maps the rest of the properties, like <code class="inline-code">index</code>, <code class="inline-code">pro
```suggestion
RudderStack sends the event name as <code class="inline-code">Application Opened</code> and maps the rest of the properties like <code class="inline-code">index</code>, <code class="inline-code">properties</code>, etc. to the RudderStack properties.
```

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +This is not an automatic lifecycle event. Hence, the properties like <code class="inline-code">version</code>, <code class="inline-code">build</code>, etc. are not present under <code class="inline-c
"automatic lifecycle event" could be confusing IMO. Should we instead say "default application lifecycle event" and link it to our lifecycle events doc? @pallabmaiti @ishachopra0401

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-appli
```suggestion
RudderStack sends a <Link to="/event-spec/standard-events/track/">track</Link> call for the Snowplow events containing the <a href="https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/mobile-trackers/previous-versions/objective-c-tracker/objective-c-1-0-0/#foreground-and-background-events"><code class="inline-code">Background</code></a> class.
```

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +This is not an automatic lifecycle event. Hence, the properties like <code class="inline-code">version</code>, <code class="inline-code">build</code>, etc. are not present under <code class="inline-c
Same comment as above.

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +        RudderStack JavaScript SDK supports the Snowplow's <code class="inline-code">trackStructEvent</code> and <code class="inline-code">trackSelfDescribingEvent</code> calls. They capture user eve
```suggestion
        The RudderStack JavaScript SDK supports the Snowplow's <code class="inline-code">trackStructEvent</code> and <code class="inline-code">trackSelfDescribingEvent</code> calls. These Snowplow calls capture user events along with their associated properties and trigger the <Link to="/event-spec/standard-events/track/"><code class="inline-code">track</code></Link> call in the RudderStack JavaScript SDK.
```

2022-10-26 12:37 UTC, ameypv-rudder commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +        RudderStack JavaScript SDK supports the Snowplow's <code class="inline-code">trackStructEvent</code> and <code class="inline-code">trackSelfDescribingEvent</code> calls. They capture user eve
Current sentence has some scope for confusion. Let me know if this tweak is accurate.

2022-10-26 13:47 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +This is not an automatic lifecycle event. Hence, the properties like <code class="inline-code">version</code>, <code class="inline-code">build</code>, etc. are not present under <code class="inline-c
Yes.

2022-10-26 14:03 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports setting values for the following Snowplow configuration objects in the mobile SDKs (iOS/Android). If not set, the default values are assigned.
Then we need to explain a lot.

2022-10-26 14:09 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports setting values for the following Snowplow configuration objects in the mobile SDKs (iOS/Android). If not set, the default values are assigned.
For NetworkConfiguration,
dataPlaneUrl: https://hosted.rudderlabs.com
controlPlaneUrl: https://api.rudderlabs.com
SessionConfiguration:
backgroundTimeout: 5 mins
TrackerConfiguration:
Already present in the doc.

2022-10-26 14:10 UTC, pallabmaiti commented on docs/user-guides/migration-guides/snowplow-migration-guide.mdx
> +RudderStack supports setting values for the following Snowplow configuration objects in the mobile SDKs (iOS/Android). If not set, the default values are assigned.
I don't know how you can fit this information there.

2022-10-26 14:54 UTC, merged