Refiner documentation
rudderlabs/rudderstack-docs pull request #958
Opened 2022-10-26 10:48 UTC by ameypv-rudder

## What do these changes do?

> Added docs for Refiner destination

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-10-26 10:56 UTC, mihir-4116 requested changes

2022-10-26 10:56 UTC, mihir-4116 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +| `properties.email` | `email` |
@ameypv-rudder here if email is sent from context.traits.email then it will be considered as email and if email is sent from traits.email then it will be considered as account.email

something like below is expected : 
`context.traits.email` | `email`
`traits.email` | `account.email`

2022-10-26 10:56 UTC, mihir-4116 commented on docs/destinations/streaming-destinations/refiner/refiner-device-mode.mdx
> +| `properties.email` | `email` |
same as above comment

2022-10-27 06:55 UTC, shrouti1507 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +| `properties.email` <br/> <span style="color: #4D4DFF;font-size:12px;">Required, userId is absent.</span> | `email` |
Required, **if** userId is absent

2022-10-27 07:40 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +| `properties.email` <br/> <span style="color: #4D4DFF;font-size:12px;">Required, userId is absent.</span> | `email` |
```suggestion
| `properties.email` <br/> <span style="color: #4D4DFF;font-size:12px;">Required, if userId is absent.</span> | `email` |
```

2022-10-28 06:20 UTC, ishachopra0401 approved these changes

2022-10-28 06:20 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +Find the open source transformer code for this destination in the <a href="https://github.com/rudderlabs/rudder-transformer/tree/master/v0/destinations/refiner">GitHub repository</a>.
```suggestion
Find the open source code for this destination in the <a href="https://github.com/rudderlabs/rudder-transformer/tree/master/v0/destinations/refiner">GitHub repository</a>.
```

2022-10-28 06:20 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +To make an <code class="inline-code">identify</code> call successfully, either of <code class="inline-code">email</code> or <code class="inline-code">userId</code> is required.
```suggestion
To make an <code class="inline-code">identify</code> call successfully, either the <code class="inline-code">email</code> or <code class="inline-code">userId</code> is required.
```

2022-10-28 06:20 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +| `traits` + `context.traits` | traits |
Should it be `traits`, `context.traits`?

2022-10-28 06:20 UTC, ishachopra0401 commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events and send them to Refiner as `trackEvent` events. If a `track` event contains a `userId`, then Refiner
```suggestion
The <Link to="/event-spec/standard-events/track">`track`</Link> call lets you capture user events and send them to Refiner as `trackEvent` events. If a `track` event contains a `userId`, then Refiner updates the corresponding user's information. Otherwise, it creates a new user.
```

2022-10-28 10:44 UTC, ameypv-rudder commented on docs/destinations/streaming-destinations/refiner/refiner-cloud-mode.mdx
> +| `traits` + `context.traits` | traits |
```suggestion
| `traits` <br /> `context.traits` | traits |
```

2022-10-31 10:19 UTC, mihir-4116 approved these changes

2022-10-31 10:31 UTC, merged