Amplitude Extract source documentation
rudderlabs/rudderstack-docs pull request #961
Opened 2022-10-27 06:19 UTC by ameypv-rudder

## What do these changes do?

> Added documentation for Amplitude Cloud Extract source

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

2022-10-27 06:20 UTC, ameypv-rudder commented on docs/sources/extract/amplitude.mdx
> +| `events` |  Yes | Yes | `uuid` |  `export` |
@a-rampalli please verify if all the fields in this table are correct, especially the Amplitude endpoints.

2022-10-27 06:37 UTC, nidhilashkari17 requested changes
@a-rampalli We need to cleanup the spec file by removing airbyte doc links so that they don't show up in the UI. Can you build an updated image with these changes.
@ameypv-rudder Once Aasish updates the image, please update the connection-settings image.

2022-10-27 11:06 UTC, a-rampalli approved these changes
lgtm

2022-10-27 11:16 UTC, nidhilashkari17 approved these changes

2022-10-28 07:14 UTC, ishachopra0401 approved these changes

2022-10-28 07:14 UTC, ishachopra0401 commented on docs/sources/extract/amplitude.mdx
> +3. Assign a name to your source and click on **Next**.
```suggestion
3. Assign a name to your source and click **Continue**.
```

2022-11-04 09:23 UTC, merged